### ISSUE TITLE
Refactor internal/config package and have it checks the necessary config values

### ISSUE THREAD

**Issue by yfei1** [googleforgames/open-match#1013]
This issue tracks the progress on refactoring the `internal/config` package. Our current config package directly read the config files from viper and wont check what fields are missing at all. It would be great if we could refactor/add a tool to check what fields are missing from the config and document the default config values for the optional fields instead.

**Comment by sawagh** [comment]
Would this be usage impacting? or just making Open Match more resilient to misconfigurations? If the later, we can move this to v0.10

**Comment by akremsa** [comment]
I can take a loot at this one. 
@yfei1  @Laremere where can I check which values are mandatory or not?
Some default value I've found here: https://open-match.dev/site/docs/installation/helm/#configuration
