### ISSUE TITLE
Inaccurate Grafana Metrics

### ISSUE THREAD

**Issue by yfei1** [googleforgames/open-match#1018]
Open Match's Grafana chart has some inaccuracy metrics that are **very** misleading - e.g. The read operation counts in the storage tab gives me 9.11rps for the FilterTicket reads, while the gRPC metrics shows the QueryTicket request rate is 371rps. We should spend some time to audit those metrics, and make sure they are needed and up-to-date.  

![image](https://user-images.githubusercontent.com/15369702/70588016-60156480-1b80-11ea-85b6-362b455b3bbe.png)
![image](https://user-images.githubusercontent.com/15369702/70588082-83401400-1b80-11ea-9c86-5ded10c575be.png)

**Comment by sawagh** [comment]
@yfei1 - since we are visiting a lot of Open Match metrics for scale benchmarking, if there are any issues here, should we bundle them up as a part of current efforts?

**Comment by yfei1** [comment]
> @yfei1 - since we are visiting a lot of Open Match metrics for scale benchmarking, if there are any issues here, should we bundle them up as a part of current efforts?

Yes, the metrics newly added for scale tests are checked in for faster development iterations but need future updates. I’m going to revisit all the metric related issues later this month, but still aiming to close this in v0.9

**Comment by yfei1** [comment]
Currently we create one new opencensus measure for each metric that we want to measure, e.g. having 
```go
mStateStoreCreateTicketTime = telemetry.HistogramWithBounds("time elapsed to create tickets", "ms", telemetry.HistogramBounds)
mStateStoreCreateTicketCount = telemetry.Counter("number of tickets created")
```

This is inefficient as our prometheus exporter is tracking and sending more measures than it should handle.

I plan to update the interfaces in our `internal/telemetry/metrics.go` file so that we could just create one measure and cast it into different prometheus views. e.g.

```diff
- func Gauge(name string, description string, tags ...tag.Key) *stats.Int64Measure
- func Counter(name string, description string, tags ...tag.Key) *stats.Int64Measure
- func HistogramWithBounds(name string, description string, unit string, bounds []float64, tags ...tag.Key) *stats.Int64Measure

+ type Measure struct {
+  *stats.Int64Measure
+ }
+ func (m Measure) ToCounter(name, description strings, tags ...tag.Key) *view.View
```
