### ISSUE TITLE
Creating a ticket with an assignment should be disallowed

### ISSUE THREAD

**Issue by Laremere** [googleforgames/open-match#1033]
ticket_test.go currently creates a ticket with an assignment.  This doesn't really make sense.

Corrected test here: https://github.com/Laremere/open-match/blob/d8be8e73d57ece9e9d59fc6e4e3f59df32b02591/test/e2e/ticket_test.go

Trying to create a ticket with an assignment should fail.  This should be tested.

**Comment by sawagh** [comment]
Removing the bug tag - as I think this was the behavior so far. We can change it - but i dont think the expectation that it should fail if assignment was set - was ever a stated / expected requirement. 

> Trying to create a ticket with an assignment should fail.
I understand that this may not be a common case - but do you think this is a strong enough concern that the system should disallow it? 

For instance, in backfill scenarios, we are recommending creating a ticket for the backfill request. Could that usage be a ticket that represents a partially complete group - with a pre-set assignment? 

Again, we may come up with a different recommendation here - but - is there a correctness reason why Open Match should just prevent this pattern?

**Comment by sawagh** [comment]
No compelling reason for this yet. The Backfill scenarios may need this behavior anyways. Allowing this today does not impact correctness in any way - so there is no need to enforce this behavior. Recommend closing this issue.

**Comment by Laremere** [comment]
TSC discussion is that it's easier to do this and then undo it, then not do it now and have problems later.

For backfill, the ticket should put info on the extensions.
Assignment is kind of a "final result" field, so having it populated at the start doesn't make much sense.  Additionally this makes tickets more uniform in their possible states: the ticket will have an assignment present if and only if the ticket is no longer looking for matches.
