### ISSUE TITLE
Test failures aren't visible to all PR authors

### ISSUE THREAD

**Issue by Laremere** [googleforgames/open-match#1036]
Trying to access a run using my personal account: https://console.cloud.google.com/cloud-build/builds/ba19df37-cc86-4e4f-b78f-b240a30b3dea?project=205790239254&pli=1
I get the error: `You don't have permission to view builds and triggers in this project.`

Is this a limitation of cloud build?  Maybe moving to prow will fix.

**Comment by yfei1** [comment]
You need to join the open-match-discuss group first to see the build result

**Comment by Laremere** [comment]
Ah, that worked.  Still think this is a mild issue.

**Comment by syntxerror** [comment]
Closing due to solution being found in the comments above.
