### ISSUE TITLE
Allow directors to return matched tickets to the match-making pool for transient failures

### ISSUE THREAD

**Issue by rib** [googleforgames/open-match#1037]
**Is your feature request related to a problem? Please describe.**

In my director it's possible for there to be an error allocating a server that may simply be a race condition as a result of clients trying to join a named private group before someone else has actually created that group.

In general errors are possible in the director after retreiving matches and it seems important that the director should be able to determine what happens to any tickets caught up in this condition.

There doesn't seem to be a way for the director to gracefully put those tickets back into the pool for matching and instead they will (as far as I understand it) remain in limbo for some time before being re-considered for matching.

Another example where I encountered this was while reviewing this example director:
https://github.com/Laremere/space-agon/blob/master/director/director.go
which currently has this commented code:
```go
// TODO: This drops matches, instead of properly allocating them.  Tickets will only return to
// the general pool after (iirc) one minute.  We should either tell OM that an assignment isn't
// coming, or retry for a little while.
if gsa.Status.State != allocationv1.GameServerAllocationAllocated {
	log.Printf("failed to allocate game server.\n")
	continue
}
```

Related to this, there also doesn't seem to be a clear way for Directors to propagate errors back to a clients if the director ultimately determines that a ticket in unallocatable.

My director is handling allocating servers for private groups where the ticket contains a unique group name. Allocation can fail when interacting with Agones to allocate a server because someone else has created a group with the same name. In this case it's not a race condition and I wouldn't want to simply put the ticket back into the pool for matching - rather I want to trigger an error state for the ticket that will be propagated back via the frontend to the client letting them know why their ticket will never get an assignment.

Maybe for this case the idea is that the ticket should be given a dummy 'assignment' which can contain custom metadata to communicate error conditions?

**Describe the solution you'd like**
For the first issue then maybe the Backend could have an `UnmatchTickets()` or anything along those lines that can be given ticket IDs that were previously got through `FetchMatches` to request that those tickets be re-considered for matching as soon as possible.

For the second issue if the recommendation is to use a dummy Assignment in this case - maybe it could be good if the documentation covered this. It would be good to know if anyone can see a problem with communicating errors back via Assignments.

**Describe alternatives you've considered**
For now I just leave the tickets in limbo for join failures and I think they may eventually be re-considered for matching but not quickly.

For the group creation failures I'm currently also just leaving the tickets in limbo. I had been considering deleting the ticket before realising that a fake assignment would probably be better for communicating error state back to clients.

**Comment by calebatwd** [comment]
This exact problem is something we've discussed quite a bit and also recently had an issue with. I really like the addition of an api for "releasing" tickets back into the matchmaking pool. I've made a pr here #1059
