### ISSUE TITLE
synchronizer: withCancelCause does not work expected

### ISSUE THREAD

**Issue by bigflood** [googleforgames/open-match#1045]
https://github.com/googleforgames/open-match/blob/5b18dcf6f3a2fec4755906284f3b15917fccccf6/internal/app/synchronizer/synchronizer_service.go#L555-L557

(i think) condition shoud be `ctx.err == nil && parent.Err() == nil`

**Comment by Laremere** [comment]
Thanks for reporting this.  I'm curious how you found it?

**Comment by bigflood** [comment]
> Thanks for reporting this. I'm curious how you found it?

I accidentally found it while reviewing the code.
