### ISSUE TITLE
Generated C# files do not include GRPC bindings

### ISSUE THREAD

**Issue by JoelOtter** [googleforgames/open-match#1047]
**What happened**: Generating the C# files - or using the ones included in the repo - does not include the GRPC service bindings. In C#, the `--grpc_out` parameter is required to build these; it is missing in the `Makefile`.

**What you expected to happen**: I'd expect the GRPC bindings to be built.

I attempted to PR this myself by adding the necessary line. However, the `grpc_csharp_plugin` doesn't seem to be included in the toolchain, and so this makes the build fail. My understanding of how the toolchain is built is limited, but it does seem like `dotnet` is supposed to be installed - which could be used to fetch the necessary NuGet package containing the plugin binary - but right now it isn't.

**Comment by yfei1** [comment]
Hey @JoelOtter,

Thanks for pointing it out! The csharp generated code are supposed to be moved to the open-match-ecosystem repo so I didn't focus on its usability after getting its prototype doing. Just opened a PR #1051 to have the missing grpc bindings check in. Could you take a look into it?

I only have intermediate experience in using csharp so any inputs are welcome!

**Comment by JoelOtter** [comment]
Will do, thanks!
