### ISSUE TITLE
API change: Remove rosters from profiles

### ISSUE THREAD

**Issue by calebatwd** [googleforgames/open-match#1049]
## Overview
Now that `MatchProfiles` have `extension`, which allows the user to submit additional data for their functions (in whichever format they prefer), do we still need the `roster` field? We've also recently started moving backfill discussions into a "frontend" concern (aka, backfill tickets). Maybe it's time we ask some users how they're using rosters, and then make a call based on their use cases.

## Motivation
In general, simplify or formalize. In the case of formalizing, we could make a new issue and decide how open match is going to help solve problems with rosters.

## Impact
Deprecation of a field on an api contract. Because rosters are still completely unknown to open match outside of a match function, there will be no breakage to open match if profiles had extra deprecated values flowing in... but the roster field would no longer be sent to match functions as part of the profile.

## Change Proto
Removal of rosters from MatchProfile

**Comment by yfei1** [comment]
I can take it

**Comment by yfei1** [comment]
Closed by #1084
