### ISSUE TITLE
Documentation: example to use Redis sentinel for service discovery

### ISSUE THREAD

**Issue by yfei1** [googleforgames/open-match#1068]
Open Match still use direct connection to Redis master by default in v0.9, yet we should provide documentation for how to enable and use Redis sentinel using our helm chart.

**Comment by sawagh** [comment]
If we stick to redis, then we should frontload this in v0.10 - If we choose not to go with Redis, then this completely goes off radar. Hence bringing this in v0.10 for tracking.

**Comment by yfei1** [comment]
#1038 implements the ability to use Sentinel for HA and master discovery.
