### ISSUE TITLE
Proposal: Migrate Build Automation to k8s prow.

### ISSUE THREAD

**Issue by jeremyje** [googleforgames/open-match#107]
Proposal Document: https://docs.google.com/document/d/1BOhIKP3N9TjOEUSn28jZvLSTFWrE7DKg66LANNerLdg
Agones Issue: https://github.com/GoogleCloudPlatform/agones/issues/649

**Comment by jeremyje** [comment]
Proposal Document: https://docs.google.com/document/d/1BOhIKP3N9TjOEUSn28jZvLSTFWrE7DKg66LANNerLdg

**Comment by calebatwd** [comment]
Tabled indefinitely (target future release). Kinda following the agones investigation for results

**Comment by yfei1** [comment]
Made Prow with its default Kubernetes agent works in my personal repo https://github.com/yufan-org/open-match/pull/9, yet identified several issues when doing the migration:
1. Prow with its native Kubernetes agent does not support having jobs running in pipeline. An workaround to it is having a shell script that executes everything step by step but the log will stay in one file without any formatting - which looks hairy.
2. Open Match's CI pipeline need to build and push its Docker images to an registry and do the deployment. This requires setting up a DinD (Docker in Docker) environment. There is a [workaround](https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/) with it (and it works) and it seems like Kubernetes is also using such settings [[1](https://github.com/kubernetes/test-infra/blob/f71320b51a541bfdd743186eaf75f2fbf5b55e8a/images/bootstrap/runner.sh#L77)], [[2](https://github.com/kubernetes/test-infra/blob/14f1bd1d880528fc87a416e217ca041e13b9647e/config/jobs/kubernetes-csi/external-attacher/external-attacher-config.yaml#L180)] yet I'm not sure if it is a good practice.
3. IAM permission in Prow environment. Prow agent will need the corresponding permissions to deploy release/upload artifacts to GCS container, and we have to reflect the changes in our terraform files accordingly.
4. Prow is going to support tekton pipeline agent which fits our need but the integration is not mature. 

[kubernetes/test-infra#13874](https://github.com/kubernetes/test-infra/issues/13874) 
[tektoncd/pipeline#1187](https://github.com/tektoncd/pipeline/issues/1187)

**Comment by sawagh** [comment]
This is not in scope for Open Match v1.0

**Comment by thisisnotapril** [comment]
Closing - not going to move to prow
