### ISSUE TITLE
Error handling around match ids collisions and missing values

### ISSUE THREAD

**Issue by Laremere** [googleforgames/open-match#1079]
There are two error cases which should be handled better:
- If two match functions (or even one match function) return multiple matches with the same id, it should be an error.
- If the evaluator returns a match id which does not correspond to a match sent to it, it should also be an error.

Currently these are ignored and or logged.

See also https://github.com/googleforgames/open-match/issues/990

**Comment by sawagh** [comment]
The other option is to base matches on unique match Ids generated by Open Match: https://github.com/googleforgames/open-match/issues/990
