### ISSUE TITLE
Create a Security Best Practices/Design Document for Open Match

### ISSUE THREAD

**Issue by jeremyje** [googleforgames/open-match#109]
As Open Match expands we'll need to provide guidance to customers on how to securely deploy it. More importantly we'll need best practices to make security informed decisions during our future designs to make sure that OM is secure by default.

I'll publish a draft for community review/edits once it's ready. As a preview it'll be simply just an index of all the best practices and recommendations for the dependencies of the project and how it relates to the project.

**Comment by sawagh** [comment]
I am moving this to 1.0 milestone - per earlier discussion, these production readiness tasks need not necessarily be tied to intermediate milestones (wont block the releases) except that they need to be ready before 1.0 - hence setting the milestone accordingly. They can come in at any earlier milestone.

**Comment by sawagh** [comment]
Yufan.. can you please confirm and close this if there is guidance already here?

**Comment by yfei1** [comment]
Closed as there is a security tech note available that Jeremy created.
