### ISSUE TITLE
Explore automatic logging of GRPC response errors

### ISSUE THREAD

**Issue by Laremere** [googleforgames/open-match#1102]
When error handling, it is generally bad practice to both log an error, and also return it.  This results in noisy logs for errors which may be properly handled, or logged again at a lower level with more context.

Generally, the pattern should be one of:
- Handle the error without propagating if possible (eg, retries where appropriate).
- Wrap the error with additional useful info/context if useful.  Then return the wrapped error to the caller.

One place where we reasonably violate this is in GRPC services, where we log the error before returning it to GRPC.  However this leads to inconsistency in the code, where some functions do or don't log returned errors, and only manual review is keeping it correct.  It would be nice to use a GRPC plugin or something which is able to intercept the error and log it. (I haven't checked, is this already done?)

Once errors are logged by the system, the service code should no longer log and return errors.

**Comment by yfei1** [comment]
Yes, this is possible. I digged into the grpc interceptors while working on the monitoring stuffs a few months ago but haven't prioritize this task since this is not the main topic for v0.9. I can take it - some of our grpc interceptors need extra configurations to work properly.

**Comment by akremsa** [comment]
Should we consider this ticket as done?

**Comment by Laremere** [comment]
yes, thanks
