### ISSUE TITLE
API change: One to one bulk assign tickets api

### ISSUE THREAD

**Issue by calebatwd** [googleforgames/open-match#1112]
## Overview
Add an api for giving tickets unique assignments in bulk.

## Motivation
Tickets don't necessarily receive the same assignment just because they're matched together. In many game scenarios... a director or function may want to assign unique fields to tickets. E.g. Who is on the team, an encryption key per ticket, or a player secret. These are not generally applicable values for "assignment for several tickets," which is what we currently have. In order to achieve this today, a developer must call the `AssignTickets` endpoint for every ticket in the match with different assignment values. Meaning they only use the bulk api for 1 ticket at a time.
This works, but it's not ideal.
If possible, we could add an additional api to `AssignTickets` that takes a map of ticketids to assignments.

## Impact
Could be backwards compatible by just adding an additional api.

## Alternative
We could add an api that assigns an individual ticket... but making it a streaming api so the director could stream all the assignments in one at a time at high speed.

## Change Proto
```
message BuklAssignTicketsRequest {
  // Assignments is a map of TicketIds to Assignments for updating the associated ticket with the assignment value.
  repeated TicketAssignment assignments = 1;
}

message TicketAssignment{
  // TicketId is a string representing the Open Match generated ticket to write the Assignment to.
  string ticket_id = 1;

  // An Assignment specifies game connection related information to be associated with the TicketIds.
  Assignment assignment = 2;
}

...

  // AssignTickets overwrites the Assignment field of the TicketIds with the mapped assignments.
  rpc BulkAssignTickets(BuklAssignTicketsRequest) returns (AssignTicketsResponse) {
    option (google.api.http) = {
      post: "/v1/backendservice/ticket:assign"
      body: "*"
    };
  }
```

In the Alternative case... we may not need to change anything besides making the existing AssignTicketsRequest a streaming api... which would result in a breaking change

**Comment by sawagh** [comment]
@calebatwd - Once we fix the bulk assign API to behave correctly, wondering if there is a strong requirement for this API. Is this a usability thing? or is there perf implications here? Having 2 APIs on the same service to assign in different cardinality seems strange - and for a common use-case, assigning every ticket from a match together seems ok as an abstraction to expose?

**Comment by sawagh** [comment]
Proposal: https://github.com/googleforgames/open-match/issues/1155 covers this and other assignment api changes.
