### ISSUE TITLE
Optimistic bulk ticket assign

### ISSUE THREAD

**Issue by calebatwd** [googleforgames/open-match#1121]
**What happened**:
Bulk api assignments fail if the assignment doesn't exist or if a write fails for an individual ticket

**What you expected to happen**:
The bulk ticket assign api should create tickets that no longer exist with an assignment field AND not fail the bulk api call based on whether the ticket exists or if the write of and individual succeeds or fails.

**Comment by sawagh** [comment]
Would like to get more context on the expectation here. I see the value in not failing the bulk assignment. However, the auto Ticket creation concerns me. 

If a Ticket has explicitly been deleted, creating it automatically in assignment seems strange. Who is the owner of this created Ticket? Who is aware (from the frontend) that this exists then - assuming it was explicitly deleted automatically? Who will eventually cleanup  / delete this Ticket? 

Also, today a Ticket creation in Open Match assigns a generated ID to the Ticket (not taken from the user).  Should in this case, we make an exception and take the ID from the given Ticket? Can you elaborate on the scenario requiring auto ticket creation on assign?

**Comment by sawagh** [comment]
Based on TSC discussion, 

It is not a key requirement that the missing Ticket be created. The primary requirement is that a failure to create a single Ticket should NOT fail the entire assignment call. 

The reasonable approach here would be to return a status object in the response that indicates the list of TicketIds that failed creation. This can be used by the caller to debug / know that some assignments failed, while the other assignments on the call still succeed.

**Comment by sawagh** [comment]
I will write up a proposal for this one.

**Comment by sawagh** [comment]
Proposal: Assignment will succeed even if individual assignments fail due to ticket not being present. The information about the failed assignments will be populated in the response object. The caller may use this for debugging / alerting purposes. Here is a proposed change to the proto to achieve this:

Option1: Concise but ugly! 
```
message AssignmentFailure {
  string ticket_id = 1;
  google.rpc.Status error = 2;
}

message AssignTicketsResponse {
  repeated AssignmentFailure failed = 1;
}
```

Option2 (Cleaner but redundant)
```
message AssignmentStatus {
  string ticket_id = 1;
  google.rpc.Status status = 2;
}

message AssignTicketsResponse {
  repeated AssignmentStatus status = 1;
}
```

**Comment by sawagh** [comment]
Proposal: #1155 covers this and other assignment api changes.
