### ISSUE TITLE
Proposal: Use query for caching and filtering

### ISSUE THREAD

**Issue by Laremere** [googleforgames/open-match#1123]
This is a proposal to switch from doing any indexing and filtering with redis to doing most of that work in memory with query.

Query's memory contains a map from ticket id to ticket pb.

Query would operate in a loop:

1. Wait for a first request.
2. Collect all waiting requests.
3. Query for list of current ids.
4. Delete all tickets in the query map that are in the active list.
5. Query for all tickets bytes for missing ticket ids.
6. Run the request(s) on the pool in parallel.
7. Loop back to 1.

In the event that a request is received after 1or2, the request will wait for the next iteration.  The expectation is that under load, many requests may be waiting for the iteration.

Few notes:

- Getting all ids uss the same methodology as is used today, so no change in correctness.
- Reading the whole state sounds scary, but it's really what OM is doing already:  Tickets are very quickly created, read many times, then deleted.  If a ticket isn't in any pools, then it won't get matches.  As such in the current implementation tends to read the tickets at least once (possibly many times) from redis every iteration.  This leads to a constant read load, once for every query instance.  Unless you're draining the entire pool every iteration, this will lead to fewer requests on redis.
- Filtering in memory is very fast.  As a bonus, it's also flexible, which means that we can very easily add new filter types in the future.
- Ticket creation no longer requires indexing each field.  So that will reduce load.

A working prototype is available here: https://github.com/googleforgames/open-match/compare/master...Laremere:queryCache

Here's the scale test showing that it was able to handle 960 profiles with ease: https://snapshot.raintank.io/dashboard/snapshot/evdz1XK1E701owZr2u47wUVMrQYg5k5K?orgId=2

**Comment by Laremere** [comment]
Oh, and if a ticket is in the all-tickets index, but not present when the whole bytes is queried for, it will not be added to the cache.  This is equivalent to what we do today.

**Comment by sawagh** [comment]
Quick Question before I leave my detailed notes here. 

In the Synchronizer, when we cancel a pending function that over-runs past the synchronization window, do we wait for that cancelled function to terminate? or is the cancellation best effort and the function could possibly continue to do work but will fail to stream results?

**Comment by Laremere** [comment]
The cancellation notification from the sycnchronizer to backend is purely an fyi.
Once the backend get it, it cancels the context used to call the mmf.  This will cancel the call from the backend's point of view.
If the mmf does proper cancel propagation (go's context does this, unsure about other languages), the call to query will be canceled.

This all is already in.

With my prototype, the call will properly back out at any time while waiting for the loop, or updating the cache.  
The loop to filter tickets out of the pool into a slice does not check the context, but is fast.
If it's canceled while streaming results back, it will err and stop.

**Comment by Laremere** [comment]
Implemented in https://github.com/googleforgames/open-match/pull/1135
