### ISSUE TITLE
Add metrics in Open Match concept

### ISSUE THREAD

**Issue by yfei1** [googleforgames/open-match#1124]
This is the last bit of Open Match's monitoring story before v1.0.

Right now, Open Match provides dashboards for monitoring k8s pod usage, grpc-level latency and error rate, and Redis performance, but lack of a story of monitoring Open Match related concepts. I plan to add a new dashboard to track the following metrics:

Ticket related metrics:
- [x] Ticket size and ticket extension size.
- [x] Number of SearchFields per ticket
- [ ] Time that a ticket spent & number of tickets in each match making stage - created, addedtoignorelist, deindexed, deleted.

Match related metrics:
- [x] Match size and Match extension size.
- [x] Number of tickets per match.

QueryService related metrics:
- [x] Number of tickets per QueryTickets call returned.
- [x] (the step after query cache) metrics related to the performance of query cache.

Evaluator related metrics:
- [x] Number of matches sent to the evaluator
- [x] Number of matches returned from the evaluator
- [x] (optional) number of collided matches using the default evaluator - the evaluator is a replaceable component so this metric applies only if one is using the default evaluator.

Synchronizer related metrics (1-3 copied from #1104 )
- [x] A metric for number of iterations started. - @Laremere I'm not sure what is the value-added for this metric, can you explain?
- [x] Time waiting for registration: indicates reg window too small
- [x] Time wasted in reg window with done mmfs: indicates reg window too big
- [x] Number of registered call per synchronization cycle

**Comment by Laremere** [comment]
> A metric for number of iterations started. - @Laremere I'm not sure what is the value-added for this metric, can you explain?

This is just how many synchronizer iterations we have.  Currently is on the scale tests.  It might actually be more useful to have this divided up into buckets for how long each iteration took.

When this goes low, you're cycles are taking too long and you're unhealthy.

**Comment by sawagh** [comment]
What milestone are we targeting this for?

**Comment by yfei1** [comment]
> What milestone are we targeting this for?

This is a must-have for 1.0 and I'm working on it this week when I'm running out of tasks. Aiming to close this in v0.10.

**Comment by Laremere** [comment]
Per comments in #1135, it'd be nice to have metrics on time spent updating the query service.

**Comment by yfei1** [comment]
Moving this issue to v1.0. Almost done with the metrics part yet I'm not sure if there is anything that needs to be further changed when setting up the grafana dashboards.
