### ISSUE TITLE
Proposal: New mechanism for waiting for assignments

### ISSUE THREAD

**Issue by Laremere** [googleforgames/open-match#1137]
Currently we have a mechanism for waiting for an assignment, however it's not very efficient.  I think there's a fairly simple way to do much better:

# Current assignment behavior
Tickets are saved in a key identical to their id, eg ticket "ABC123" will be on redis field "ABC123".

To set assignment:
1. Read ticket bytes from redis, and deserialize.
2. Add assignment to the ticket.
3. Serialize and write the ticket back to redis.

To get ticket:
1. Request ticket bytes from redis, deserialize.
2. Return ticket.

To Wait for assignment:
1. Request ticket bytes from redis, deserialize.
2. If ticket has assignment, return assignment.
3. Wait (less than a second)
4. Loop to #1

# Proposed new behavior
Tickets are split on two key values: ticket (eg, "t_ABC123") and assignment ("a_ABC123").

To set assignment:
1. Serialize the assignment, write it to the assignment key in redis.

To get ticket:
1. Request bytes from redis for both ticket and assignment, deserialize.
2. Set the assignment field on the ticket. (if the assignment is found)
3. Return ticket.

**To Wait for assignment**:
Request go routine:
1. Join or start (if not running, then afterwords join) the mutual go routine
2. Wait for response from mutual go routine.
3. return assignment

Mutual Go routine:
1. Collect new go routines while waiting.
2. On a time.ticker, continue,
3. Do an mget on all of the waiting for assignment fields.  As unassigned tickets won't be present, it will return only the assignments which have a value.
4. Return any assignments which were found, removing them from waiting for assignment.
5. If there are still assignments waiting, loop.

I think this has a chance to be a more efficient use of redis.  Would be useful to have a prototype with scale numbers if we think it's worth improving.  I was thinking that the assignment mgets could be aligned with the synchronizer cycle, before realizing that assignments are made asynchronously, so that doesn't work.

**Comment by sawagh** [comment]
> Tickets are split on two key values: ticket (eg, "t_ABC123") and assignment ("a_ABC123").

I assume this is orthogonal to https://github.com/googleforgames/open-match/issues/1139 (this just changes the storage semantics as opposed to the exposed concepts - so completely transparent to API exposure).

I agree with your comment that this change can be justified by perf numbers from a prototype. I would say, lower on priority compared to other v0.10 issues - so am setting the v1.0 milestone to begin with. We can pull that in if we have room in v0.10 toward end game.

**Comment by Laremere** [comment]
We now have a contract to indicate whether a ticket is still present when assigning, so this doesn't work as proposed.

Closing.  If we need to improve assignment performance in the future the change will come out of investigations into that.
