### ISSUE TITLE
Switch to new protobuf api

### ISSUE THREAD

**Issue by Laremere** [googleforgames/open-match#1138]
Note: This does not affect Open Match users.  This is merely a new library for interacting with proto buffers, the serialization is unchanged.

https://blog.golang.org/a-new-go-api-for-protocol-buffers

Seems like it looks nice.  Should switch to it.  Not sure how the rest server will interact with it.
As a followup to this, consider using https://pkg.go.dev/google.golang.org/protobuf/compiler/protogen?tab=doc to generate http/json clients for the mmf and evaluator, that implement the client interface, to simplify our code using the clients.

**Comment by syntxerror** [comment]
@andrewgrundy was this closed by #1358 ?

**Comment by andrewgrundy** [comment]
I think it was actually closed by this commit: https://github.com/googleforgames/open-match/commit/a9b8eec9e0c2d500668a75bd93b398b85d86e4f5

**Comment by syntxerror** [comment]
thanks. closing
