### ISSUE TITLE
Helm test is running on helm template

### ISSUE THREAD

**Issue by Laremere** [googleforgames/open-match#1141]
Reported on slack by Luna.

Running in `install/helm/open-match/`:
```
helm dep up
helm template open-match-0.9.0 . -f my-values.yaml
```
(Where my-values.yaml is a customized but reasonable values.yaml)
Will briefly start up the integration test, and leave around open-match-test-service service account.

Looks like helm is including the test folder.  I guess the helm magic for helm test isn't magic enough.

**Comment by yfei1** [comment]
I encountered this issue before and it turns out it’s a bug in helm2. Upgrading it to use helm3 can mitigate this issue.

**Comment by yfei1** [comment]
Closing this issue as this can be resolved by using helm3 with `helm template --no-hooks` flag.
