### ISSUE TITLE
Look into leader election in k8s for the synchronizer

### ISSUE THREAD

**Issue by Laremere** [googleforgames/open-match#1143]
Discussing how to do deployments updates on the synchronizer in slack, Luna pointed out that k8s has a leader election capability.

> This syncs up pretty nicely with how leaders are elected in k8s deployments
> Which k8s provides helpers for
> 
> k8s provides helper functions that lets you do leader election via a configmap
> Cycle starts, synchronizer takes lead
> cycle ends, it lets it go
> Healthcheck is set to not go healthy till leader is claimed
> end result: old one will finish its cycle before new one goes healthy and then causes the old one to shutdown

This would be good as an alternative to https://github.com/googleforgames/open-match/issues/771
Potentially we could get higher availability for the synchronizer as well.

**Comment by Laremere** [comment]
Found an example here: https://github.com/kubernetes/client-go/blob/master/examples/leader-election/main.go

Per https://pracucci.com/graceful-shutdown-of-kubernetes-pods.html, pods will get a sigterm on the pid1 (should be the go app) when they are to terminate within 30 seconds.  
We could capture that, finish any current synchronization cycle, and shut down.  

Any backend FetchMatches which were waiting for the next cycle to start would need to be messaged that its synchronizer is going away, and it needs to retry.

**Comment by syntxerror** [comment]
Closing due to staleness. If this is needed, we'll reopen.
