### ISSUE TITLE
Publish guidelines for implementing backfill, lobby based matchmaking 

### ISSUE THREAD

**Issue by sawagh** [googleforgames/open-match#1148]
Backfill is a core scenario that most Open Match customers need to implement. Currently, Open Match do not have any published guidelines / recommendations on how to implement this scenario. Based on explorations by the community, there are some implementations (a profile per backfill) that do not scale well. 

Please publish guidelines on how to implement backfill for an Open Match based Matchmaker, listing out any gotchas / design considerations that the developer should consider. 

Some developers have also requested for a lobby based matchmaking (trickle matchmaking) where a lobby of n players gets gradually populated till finally, a match can be started once it reaches a certain threshold. In most such cases, the game also wants to provide an experience to the clients where they can see the lobby being populated. Open Match model of matchmaking does not naturally lend itself to this style of matchmaking (as common recommendation is for Match Functions to generate complete matches). However, this scenario may be very similar to backfill where a sparsely populated lobby is (almost) equivalent to a match that needs backfill. 

Please provide guidelines on implementing this scenario using Open Match (possibly same guidelines as Backfill?)

**Comment by Laremere** [comment]
Some more context: https://github.com/googleforgames/open-match/issues/1114

**Comment by Laremere** [comment]
Moving backfill discussions to a new issue:
#1240
