### ISSUE TITLE
Modify AssignTickets API to support Bulk and Optimistic assignments. 

### ISSUE THREAD

**Issue by sawagh** [googleforgames/open-match#1155]
**Overview**

This proposal combines motivations and proposals from the following issues:
https://github.com/googleforgames/open-match/issues/1121 
https://github.com/googleforgames/open-match/issues/1112

Please see those issues for details of motivations for these changes. Here is an overview of the changes needed:

1. Provide an ability to set multiple assignments in the same AssignTickets call
2. Do not fail the AssignTickets call for a single assignment failure, but rather provide this as status information. 

Proposal:

This issue converges proposals in both the linked issues. A minor change though is that in #1112, each assignment is to a single Ticket - which actually will make the originally supported scenario (multiple tickets to one assignment) very verbose. Hence, this proposal enables assigning an assignment to one or more ticket and supports multiple such assignment units in the same TicketAssignment call. 

```
message TicketAssignment{
  // TicketIds is a list of strings representing Open Match generated Ids which apply to an Assignment.
  repeated string ticket_id = 1;

  // An Assignment specifies game connection related information to be associated with the TicketIds.
  Assignment assignment = 2;
}

// AssignmentFailure contains information about the Ticket and the Assignment that failed and the failure status.
message AssignmentFailure {
  string ticket_id = 1;
  Assignment assignment = 2;
  google.rpc.Status error = 2;
}

message AssignTicketsRequest {
  // Assignments is a map of TicketIds to Assignments for updating the associated ticket with the assignment value.
  repeated TicketAssignment assignments = 1;
}

message AssignTicketsResponse {
  // Failed is a list of all the Assignments that failed, along with failure status. 
  repeated AssignmentFailure failed = 1;
}

rpc AssignTickets(AssignTicketsRequest) returns (AssignTicketsResponse) {
  option (google.api.http) = {
    post: "/v1/backendservice/tickets:assign"
    body: "*"
  };
}
```

**Comment by Laremere** [comment]
Mostly looks good.

Naming wise, everything looks good but `TicketAssignment` is a little unintuitive for having multiple tickets.  Consider `TicketsAssignment`, or `TicketAssignmentGroup`, or maybe just leaving what you have, idk.

For functionality, I am wondering about two things:
What is the purpose of `AssignmentFailure.assginment`?  The client sent this assignment, so why should they get it back?  What info does it have?

For `AssignmentFailure.error`, I'm not sure the rpc.Status makes sense?  It's not clear to me how to interpret that.  I would say consider:

```protobuf
// AssignmentFailure contains information about the Ticket and the Assignment that failed and the failure status.
message AssignmentFailure {
  enum Cause {
    UNKNOWN = 0;
    TICKET_NOT_FOUND = 1;
  }

  string ticket_id = 1;
  Cause cause = 2;
}
```

So that way the reason the ticket isn't assigned successfully is clear.

Depending on what we want to do later, we can consider adding other reasons, such as ticket already assigned.

**Comment by sawagh** [comment]
Thanks Scott. Great recommendations, makes the proposal more crisp. Incorporating your changes, here is updated proposal. WDYT of AssignmentGroup? (short for TicketAssignementGroup as thats too long):

```
// AssignmentGroup contains an Assignment and the Tickets to which it should be applied. 
message AssignmentGroup{
  // TicketIds is a list of strings representing Open Match generated Ids which apply to an Assignment.
  repeated string ticket_id = 1;

  // An Assignment specifies game connection related information to be associated with the TicketIds.
  Assignment assignment = 2;
}

// AssignmentFailure contains the id of the Ticket that failed the Assignment and the failure status.
message AssignmentFailure {
  enum Cause {
    UNKNOWN = 0;
    TICKET_NOT_FOUND = 1;
  }

  string ticket_id = 1;
  Cause cause = 2;
}

message AssignTicketsRequest {
  // Assignments is a list of assignment groups that contain assignment and the Tickets to which they should be applied.
  repeated AssignmentGroup assignments = 1;
}

message AssignTicketsResponse {
  // Failed is a list of all the Tickets that failed assignment along with the cause of failure. 
  repeated AssignmentFailure failed = 1;
}

rpc AssignTickets(AssignTicketsRequest) returns (AssignTicketsResponse) {
  option (google.api.http) = {
    post: "/v1/backendservice/tickets:assign"
    body: "*"
  };
}
```

**Comment by Laremere** [comment]
LGTM!

**Comment by sawagh** [comment]
Assigning to @Laremere based on discussion in the Open Match sync. Here is a transient PR that simply changes the state store interface to accommodate for returning assignment failures. 

https://github.com/sawagh/open-match/commit/78ebaac408732c348b69c48136001fd25898e08b

My recommendation would be to focus on putting the external API change in place with minimal changes to state store as step 1. There is room to rethink if the current state store interface to update assignments can just completely change for the new API but i ll leave that to your judgement and scope.
