### ISSUE TITLE
Proposal: Release all tickets to pool

### ISSUE THREAD

**Issue by Laremere** [googleforgames/open-match#1159]
In the event that the director crashes, it know that any pending tickets are currently reserved for matches which will never receive an assignment.  There is a timeout, but it can speed things along by indicating to open match to immediately return tickets to the pool.

This would additionally be helpful for the frequently requested "Delete all tickets" operation.  Currently we don't have any direct method to do it, and recommend querying all tickets and then deleting manually.  This would exclude any tickets which are currently in a pending state.

```protobuf
message ReleaseTicketsRequest{
  // TicketIds is a list of string representing Open Match generated Ids to be re-enabled for MMF querying
  // because they are no longer awaiting assignment from a previous match result
  repeated string ticket_ids = 1;

  // If true, ticket_ids is ignored, and instead all tickets which are pending are returned to the
  // active pool.
  bool release_all_tickets = 2;
}
```

Implementation wise, this is simply a `DEL proposed_ticket_ids` to remove the key of the sorted set.

**Comment by sawagh** [comment]
Having release_all_tickets and repeated string ticket_ids feels strange. Even though documented that specifying one overrules the other, that is not obvious / intuitive. (something to the effect of oneof is probably clear but slightly more complicated to use)

Alternatively, why not just provide basic primitives and let users build these scenarios? Here is a proposal (achieves this and more)

```
// Just for reference, actual state details worked on in #1100
enum TicketState {
  ACTIVE = 0;
  PENDING = 1;
  ASSIGNED = 2;
}

message ListTicketIdsRequest {
  TicketState state = 1
}

message ListTicketIdsResponse {
  repeated string ids = 1;
}

service QueryService {
  rpc ListTicketIds(ListTicketIdsRequest) returns (stream ListTicketIdsResponse) {
    option (google.api.http) = {
      post: "/v1/queryservice/ticketids:query"
      body: "*"
    };
  }
}
```

If we have the above API, that can then be used with any of the release / delete / get primitives to build scenarios. Thoughts?

**Comment by sawagh** [comment]
Pulling this into v0.10 for visibility - This is very much related to https://github.com/googleforgames/open-match/issues/766 which was a v0.10 issue and I do not think completely addresses the user requirement.

**Comment by sawagh** [comment]
Discussed this on 03/23 in triage discussion. This may involve providing additional capability to allow listing Tickets in pending / assigned states - however, that may need additional indexing. Out of scope for v0.10 - the changes here will not be breaking in nature but rather additive. Moving to v1.0
