### ISSUE TITLE
Add links to traces for unified calls in synchronizer and query

### ISSUE THREAD

**Issue by Laremere** [googleforgames/open-match#1186]
Open Census has a concept of linking traces: https://opencensus.io/tracing/span/link/
This would be good to use for when multiple calls are unified into one.  This happens in two places at the moment:
- Multiple synchronizer.Syncrhonize calls unify into a synchronization cycle, and their call to the evaluator is shared.
- Multiple calls to queryservice.Query result in one call to redis that refreshes the cache.

It should probably always start a trace only if the first call is currently being traced.  (That way if all are being traced, they can link properly.)  It can't just be a span because all of the unified calls are equal.  So each of the call traces is linked to the unified trace.

**Comment by syntxerror** [comment]
Closing due to shift to OTel in the future. Look out for updates
