### ISSUE TITLE
om-test job references non-existent image for 0.10.0

### ISSUE THREAD

**Issue by neprune** [googleforgames/open-match#1199]
**What happened**:

Installing open-match (0.10.0) creates an `om-test` job. The job fails to be scheduled because `gcr.io/open-match-public-images/openmatch-base-build:0.10.0` appears to not exist.

**What you expected to happen**:

The image exists and the job completes successfully.

**How to reproduce it (as minimally and precisely as possible)**:

Install helm with 0.10.0

**Anything else we need to know?**:

We are using open-match as a dependency of our chart.

**Output of `kubectl version`**:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-10T21:53:58Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2020-01-14T00:28:37Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Open Match Release Version**:

0.10.0

**Install Method(yaml/helm):**:

Helm

**Comment by neprune** [comment]
This appears to be blocking us from setting up `helm test` to succeed when our own tests pass. Would really appreciate this being fixed / an exposed helm value we can use to disable this.

**Comment by Laremere** [comment]
dup of https://github.com/googleforgames/open-match/issues/1199

**Comment by Laremere** [comment]
Actually a dup of https://github.com/googleforgames/open-match/issues/1198
