### ISSUE TITLE
How to use Open Match with Unity?

### ISSUE THREAD

**Issue by TechnicalGP** [googleforgames/open-match#1221]
I just want to know that how to use open match sdk in unity.
Is there any tutorial?
Please help me.

**Comment by markmandel** [comment]
You will need to write a [Game Frontend](https://open-match.dev/site/docs/guides/matchmaker/frontend/) to interact with your Unity Game Client.

Depending on your needs, you could connect via http/s, websockets or even gRPC -- but that aspect is up to you and your game needs.

**Comment by Laremere** [comment]
> Is there any tutorial?

There is no Unity specific tutorial.  Currently Open Match expects you to bring your own frontend and director infrastructure.

If you want to build less, you may be interested in Unity Multiplayer Services, which has a matchmaker service in closed beta: https://unity.com/solutions/multiplayer-services

Please re-open if you have any other questions.
