### ISSUE TITLE
Add affinity, nodeSelector, toleration, resources for open-match-customize subchart

### ISSUE THREAD

**Issue by govargo** [googleforgames/open-match#1222]
**Is your feature request related to a problem? Please describe.**

When we install the open-match with helm, we can select affinity & nodeSelector & toleration & resources for open-match core component(thanks for https://github.com/googleforgames/open-match/issues/834).
But when we install subchart's open-match-customize as we'd like to install evaluator or matchfunctions, we cannot select affinity & nodeSelector & toleration & resources for evaluator/matchfunctions.
It is because evaluator/matchfunctions has no field for affinity & nodeSelector & toleration & resources in helm subchart.

**Describe the solution you'd like**

I hope evaluator/matchfunctions has affinity & nodeSelector & toleration & resources fields in helm chart.

**Comment by Laremere** [comment]
It looks like it's relatively simple to add the required include: https://github.com/googleforgames/open-match/pull/1015/files

**Comment by Laremere** [comment]
I would like to actually remove the customize subchart, but the replacement chart for the default evaluator will need this: https://github.com/googleforgames/open-match/issues/1244

**Comment by SealTV** [comment]
Hi. This issue fixed in my PR [1311](https://github.com/googleforgames/open-match/pull/1311).
I was wrong in PR description when set number of issue to close.

**Comment by Deusald** [comment]
Is this ready? After installing open-match with helm evaluator is missing the nodeSelector.

**Comment by syntxerror** [comment]
Closed by PR 11311
