### ISSUE TITLE
File 01-open-match-core.yaml could not be applied

### ISSUE THREAD

**Issue by aLekSer** [googleforgames/open-match#1242]
There is an issue with yaml config file. It seems that helm templates should be fixed.

**What happened**:
`om-config-volume-override` could not be mounted:
```
Unable to mount volumes for pod "om-query-7748467fdd-c6b6w_open-match(7bf0a78a-d344-11ea-b628-42010a8a0103)": timeout expired waiting for volumes to attach or mount for pod "open-match"/"om-query-7748467fdd-c6b6w". list of unmounted volumes=[om-config-volume-override]. list of unattached volumes=[om-config-volume-default om-config-volume-override open-match-unprivileged-service-token-xvrxm] | FailedMount | Jul 31, 2020, 6:44:51 PM | Jul 31, 2020, 6:47:08 PM | 2 |  
-- | -- | -- | -- | -- | --
MountVolume.SetUp failed for volume "om-config-volume-override" : configmap "om-configmap-override" not found | FailedMount | Jul 31, 2020, 6:42:49 PM | Jul 31, 2020, 6:46:59 PM | 10 |  
Successfully assigned open-match/om-query-7748467fdd-c6b6w to gke-om-cluster-2-default-pool-b9721cad-pjrz

```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
```
kubectl apply --namespace open-match \
  -f https://open-match.dev/install/v1.0.0/yaml/01-open-match-core.yaml
```

**Anything else we need to know?**:

**Output of `kubectl version`**: 

**Cloud Provider/Platform (AKS, GKE, Minikube etc.)**:  GKE_VERSION = 1.14.10-gke.45 

**Open Match Release Version**: 1.0

**Install Method(yaml/helm):**:

**Comment by Laremere** [comment]
You're required to provide the config map override -  it's not something in that yaml file.
However I'm seeing a lot of people hit this issue, so there's clearly a need for better documentation.

**Comment by Jriles** [comment]
@Laremere that was super helpful, I missed in the docs that you have to either install your own evaluator or use the default one that is provided. [https://open-match.dev/site/docs/installation/yaml/#install-the-default-evaluator](scroll up a bit and you'll see the note)

**Comment by syntxerror** [comment]
Closing due to resolution in thread
