### ISSUE TITLE
Unhelpful '500' failure when assigning an empty list of tickets

### ISSUE THREAD

**Issue by TBBle** [googleforgames/open-match#1266]
**What happened**:

Due to a local bug in my code, our Director sent an [`AssignTicketsRequest`](https://open-match.dev/site/docs/reference/api/#openmatch.AssignTicketsRequest) via REST to the backend containing an empty list of tickets.

We got a 500 error back from the RPC gateway without any useful information.

The om-backend logs contained only:
```
time="2020-10-09T12:38:09Z" level=error msg="failed to update assignments" app=openmatch component=app.backend error="ERR wrong number of arguments for 'mget' command"
time="2020-10-09T12:38:09Z" level=error msg="failed to update assignments for requested tickets" app=openmatch component=app.backend error="ERR wrong number of arguments for 'mget' command"
```

**What you expected to happen**:

Either:
* No tickets were assigned, and life continues on; or
* A failure indicating that 'no tickets' is not a rational `AssignTicketsRequest`.

In this case, the latter would have been more useful, and pointed me towards the real issue; but the former is quite acceptable, and fits the more-general use-case.

**How to reproduce it (as minimally and precisely as possible)**:

Untested: Add a test similar to [`TestEmptyReleaseTicketsRequest`](https://github.com/googleforgames/open-match/blob/6f05e526fb258d390fb277de0d53623ce5194316/internal/testing/e2e/ticket_test.go#L190-L202) to test an empty `AssignTicketsRequest`.

**Anything else we need to know?**:

The actual error message being logged is because we call the redis `mget` command with the ticket list, but `mget` *fails* when given an empty array, e.g., https://github.com/NodeRedis/node-redis/issues/125.

I would suggest either this case be caught and short-cut to "success" before passing down to Redis, or the API be respecified to be 1-or-more ticket IDs so that code-gen won't let me call this sort of thing, and the server can send a 400-series error instead, so I know the call was incorrect.

(I'm not sure how the GRPC/REST bridge works, so I don't know if perhaps you would get a 400-series error automatically from the definition, or if perhaps you cannot actually specify "1-or-more ticket IDs" in the API spec)

**Output of `kubectl version`**:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:08:59Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:47:43Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Cloud Provider/Platform (AKS, GKE, Minikube etc.)**: 

Bare-metal Kubernetes cluster.

**Open Match Release Version**:

Open Match master, not sure of the exact date. 

**Install Method(yaml/helm):**:

Helm subchart.

**Comment by mridulji** [comment]
hello @TBBle 

I assume there may be two approaches in case there are multiple assignments in the group i.e. `*pb.AssignTicketsRequest.Assignments`
1. To let others proceed for execution except ones that are not having ticket ids in `*pb.AssignmentGroupTicketIds`. When doing so we can see `*pb.AssignTicketsResponse.Failures` to find out the cause
2. To stop execution of invoked function and respond with error.

I think first approach would be efficient. Please share your thoughts😊

**Comment by TBBle** [comment]
I assume that for (1), the failure response would have to be for ticket `""`, because the problem was missing ticket IDs.

Personally, I'd lean towards (2) (failing _before_ any assignments are processed), simply because an `AssignmentGroup` with an empty `ticket_ids` list seems likely to be a bug, but I can see how it might be possible for a Director implementation to allocate all their groups, and then add `ticket_ids`, and expect that `AssignmentGroup` with an empty `ticket_ids` list is simply a no-op.

In the latter case, it'd be (3): Silently ignore `AssignmentGroup` with empty `ticket_ids` as valid-but-no-op.

Although I understand OpenMatch does not look at `Assignment` data now, perhaps in future there will be some meaning to the mere mention of an `Assignment`, even if no `ticket_ids` are assigned to it.

**Comment by mridulji** [comment]
yes, I also think that it should be considered as a bug if all the `AssignmentGroup` have empty `ticket_ids` and (2) can be a good approach then. 

> Personally, I'd lean towards (2) (failing before any assignments are processed), simply because an AssignmentGroup with an empty ticket_ids list seems likely to be a bug, but I can see how it might be possible for a Director implementation to allocate all their groups, and then add ticket_ids, and expect that AssignmentGroup with an empty ticket_ids list is simply a no-op.

**Comment by mridulji** [comment]
Hey @TBBle, would you please like to see if the above PR fixes this bug.

**Comment by TBBle** [comment]
I had a quick look; I'm not in a position to test this, as I've moved teams and am no longer working on Open Match integration.

The failure appears to be based on _all_ `AssignmentGroup`s being empty, as it checks the resulting ticketID-keyed map. My understanding from the conversation above (but I may have mistook) was that the failure would happen if _any_ `AssignmentGroup` is empty.

Perhaps some multi-group assignment unit tests would clarify this behaviour.

**Comment by syntxerror** [comment]
I agree with a unit test for the multi-group assignment may been needed and would help clarify this behavior. We should update the documentation to state a _singular_ empty `AssignmentGroup`s within a multi-group assignment will be ignore and an entirely empty `AssignmentGroup` will result in failure.
