### ISSUE TITLE
Cycle gets canceled when duplicated match IDs are evaluated

### ISSUE THREAD

**Issue by HazWard** [googleforgames/open-match#1267]
**What happened**:
A function returned a list of proposals where the match IDs were duplicated. This causes the whole matchmaking cycle gets canceled.

**What you expected to happen**:
I would expect to get a warning for the function that produced the duplicate ID and the duplicate match would be dropped.

**How to reproduce it (as minimally and precisely as possible)**:

1. Setup a simple match function that generates a single match.
2. Make the function add the match multiple times to the list with a constant ID
3. Call `backend.FetchMatches` and an error will be returned.

**Anything else we need to know?**:

**Output of `kubectl version`**:

**Cloud Provider/Platform (AKS, GKE, Minikube etc.)**: GKE

**Open Match Release Version**: 1.0.0

**Install Method(yaml/helm):** YAML

**Comment by HazWard** [comment]
If the `DefaultEvaluationCriteria` is available in in the extensions, we should select the match with the highest score instead of losing the canceling the whole cycle.

**Comment by Laremere** [comment]
This error is intentionally noisy - producing matches with the same ID is something your system should never do.  It indicates a severe bug in client code.

If it was just a warning, I fear that it would go unnoticed.  Currently the only channel for producing errors is through logs, which easily go unchecked.
