### ISSUE TITLE
Proposal for adding Version field to Backfill

### ISSUE THREAD

**Issue by hsorellana** [googleforgames/open-match#1294]
**Is your feature request related to a problem? Please describe.**
Scenario explained [here](https://github.com/googleforgames/open-match/pull/1280#issuecomment-729236126)

**Describe the solution you'd like**
Add a new field called `Version` to `Backfill` structure.

**Describe alternatives you've considered**

**Additional context**

**Comment by hsorellana** [comment]
> If Version gets always updated on GS and Backend, then we can leave only one.
BF Version 2
GS Update to Version 3 should have a priority over Backend Update Version 3.

> Generation is not enough when one MMF cycle is ended, the second cycle has started, then Acknowledge from GS has not came. BF Cache should update itself when the second MMF cycle would start to work.

**Comment by hsorellana** [comment]
We have discussed a need to make an update to the design: include `Version` field.
Point to have it: easy way to invalidate Backfill updates from the backend, when the result of the MMF (outdated Backfill queried) has a previous version and a resulting match proposal should not be taken into account, as an attempt to Update Backfill with an outdated version in it would be rejected.

Imagine there is a `Version1` Backfill sits in the query. It was used to form a matchProposal and lead to updated `Backfill`. Redis has a Backfill `Version2` now.
Next round of MMF for some reason `queryBackfills` and received old `Version1` Backfill, form a matchProposal but this match even if it passes Evaluator. An update of the Backfill from 1->2nd version would be rejected, since Redis already know version 2. So no Tickets would be associated with this `Backfill`.

Two options to achieve the aforementioned behaviour:

1. Include `Version` along with `Generation` into `Backfill` protobuf definition. It would also be contained in the matchProposal as part of the `Match`.
2. Include `Version` to the InternalBackfill representation also stored in Redis. (Along with `Backfill`, `TicketIds` - `Version` field). This leads to a need to change `Match` protobuf - new field `backfill_version`, along with current Backfill and `allocate_gameserver`

**Comment by hsorellana** [comment]
@yeukovichd @akremsa @aLekSer I'm opening this issue to have an open discussion about Version field. If i'm missing some, or you have a scenario useful to this context, please share

**Comment by hsorellana** [comment]
> If Version gets always updated on GS and Backend, then we can leave only one.
Currently, BF Version 2
GS Update to Version 3 should have a priority over Backend Update Version 3.

> Generation is not enough when one MMF cycle is ended, the second cycle has started, then Acknowledge from GS has not came. BF Cache should update itself when the second MMF cycle would start to work.

**Comment by aLekSer** [comment]
Other way would be to increment Generation always from Backend (after MMF) and Frontend.

**Comment by Laremere** [comment]
As long as we hold the lock when doing the update, and get the previous generation then add one, I think increasing generation every time will work.
