### ISSUE TITLE
Recent builds failing. Need to update location for stable and incubator charts

### ISSUE THREAD

**Issue by jonfoust** [googleforgames/open-match#1313]
**What happened**:
Looking at recent builds that have failed, it seems most of them are failing at the same point. Looking deeper, it seems the charts are not being downloaded.
**How to reproduce it (as minimally and precisely as possible)**:
No need, most builds are failing at the moment
**Anything else we need to know?**:

- Here is a link detailing the EOL of the current chart locations used in Open Match:
https://helm.sh/blog/new-location-stable-incubator-charts/

- An update to the minimum Helm version will auto-detect if the repos are correct.

**Comment by sfro** [comment]
Seeing issues with this as well. Is there any workaround until there is an update?
