### ISSUE TITLE
The 1.0.0 release is broken

### ISSUE THREAD

**Issue by luna-duclos** [googleforgames/open-match#1333]
**What happened**: Right now, its impossible to actually run helm for the 1.0.0 release of openmatch

**What you expected to happen**: I can get the release and run helm

**How to reproduce it (as minimally and precisely as possible)**:

Download the release and run `helm dep up`, you'll get the following error:

```
Error: could not find : chart redis not found in https://kubernetes-charts.storage.googleapis.com/
```

**Anything else we need to know?**: Nothing

**Output of `kubectl version`**: No kubectl used

**Cloud Provider/Platform (AKS, GKE, Minikube etc.)**: Not relevant

**Open Match Release Version**: 1.0.0

**Install Method(yaml/helm):**: helm

**Comment by luna-duclos** [comment]
Would be great if we could either:

- fix the 1.0.0 release
OR
- Mark 1.0.0 as broken and make a fixed 1.0.1 release

**Comment by Laremere** [comment]
@luna-duclos it looks like 1.1.0 has this fix already in it.  Would doing an upgrade work for you?  (There's very little difference in the versions, so it should be an easy upgrade.)

**Comment by luna-duclos** [comment]
If 1.1.0 is a trivial upgrade, that could do! Its still a bit annoying though as we're a bit busy as a team, it'd be super helpful if we could have a 1.0.1 if it isn't too much work

**Comment by luna-duclos** [comment]
Thinking about it more, I'd want to do the 1.1.0 upgrade in a month or so, a 1.0.1 would be greatly appreciated

**Comment by jonfoust** [comment]
@luna-duclos v1.0.1 has been merged. Should be good to go. I'll leave the issue open until I've finished the complete release steps necessary for the patch
