### ISSUE TITLE
API change: Return 404 Not Found on DELETE ticket/backfill ticket requests when the ticket does not exist

### ISSUE THREAD

**Issue by lucy-yuan** [googleforgames/open-match#1354]
## Overview

Currently, Open Match returns a success response 200 on the DELETE requests for ticket (`/v1/frontendservice/tickets/{ticket_id}`) and backfill ticket (`/v1/frontendservice/backfills/{backfill_id}`), regardless whether the ticket was actually found. Proposal to return 404 Not Found in these situations.

## Motivation

* To align with the GET requests on the same endpoints, which return 404 Not Found when the resource is not found.
* To provide more visibility on the DELETE request.

## Impact

Clients that expect a successful response to a delete ticket request when sending an ID that does not exist or when sending the same ID multiple times will be impacted.

## Change Proto

Proto is the same for successful requests. 404 Not Found response code to be returned when requested ticket not found.

Please see PR #1352 for proposed changes.

**Comment by HazWard** [comment]
@jonfoust Do you know what's the process when introducing breaking changes?

**Comment by jonfoust** [comment]
@HazWard There is a bunch of things to consider. Normally it would go under review and discussion before being approved if it were breaking the main branch. This change seems to be for backfill which is considered beta at this point. Happy to discuss other approaches to breaking changes.

**Comment by lucy-yuan** [comment]
PR has been merged.
