### ISSUE TITLE
regahere.

### ISSUE THREAD

**Issue by javablockef** [googleforgames/open-match#1362]
`issues back means Regahawlery  its same anonymous"
![2E17BA07-85C3-4E90-80D3-5EC279CC1488](https://user-images.githubusercontent.com/79735594/111146793-e518d600-859a-11eb-8b38-12b039f1b393.jpeg)
**Is` your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by syntxerror** [comment]
Closing for lack of context
