### ISSUE TITLE
Documentation : Typo in DoubleRangeFilter description

### ISSUE THREAD

**Issue by MeltdownInteractive** [googleforgames/open-match#1371]
DoubleRangeFilter 
Filters numerical values to only those within a range. double_arg: "foo" max: 10 min: 5 matches: {"foo": 5} {"foo": 7.5} {"foo": 10} does not match: {"foo": 4} {"foo": 10.01} _**{"foo": "7.5"}**_ {}

{"foo": "7.5"} should not be in the 'does not match list'.

**Comment by syntxerror** [comment]
Issue moved to docs repo. Closing
