### ISSUE TITLE
Values.yaml from doc page

### ISSUE THREAD

**Issue by Maxiimeeb** [googleforgames/open-match#1372]
I was following the helm installation from the doc page (https://open-match.dev/site/docs/installation/helm/#install-the-open-match-helm-chart) and I wanted to use a Values.yaml file with the install command `helm install my-release --namespace open-match open-match/open-match -f Values.yaml`. However, there is no clear link to such file with all the possible values. I did find a file on the github (open-match/install/helm/open-match/values.yaml), but the values didn't match the specified list on the doc page.

E.G. open-match-override.enabled is missing in the file.

It would be nice to have a link to a Values.yaml from the doc page. That anybody could start with and modify for their needs

**Comment by joeholley** [comment]
SGTM, I'll work up a PR

**Comment by joeholley** [comment]
Migrating to the docs repo

**Comment by joeholley** [comment]
@syntxerror Please close this, it has been moved to https://github.com/googleforgames/open-match-docs/issues/232
