### ISSUE TITLE
There are multiple redis masters in v1.2.0-rc.1

### ISSUE THREAD

**Issue by castaneai** [googleforgames/open-match#1374]
**What happened**:

I expected one master and one slave, but there are two masters.
The ticket retrieval fails because the writes are distributed across two masters.

```sh
$ kubectl exec -it -n open-match openmatch-redis-node-1 -c redis -- redis-cli info replication | grep role
# role:master
$ kubectl exec -it -n open-match openmatch-redis-node-0 -c redis -- redis-cli info replication | grep role
# role:master
```

**What you expected to happen**:

I expected one master and one slave, but there are two masters.

**How to reproduce it (as minimally and precisely as possible)**:

1. Install open-match v1.2.0-rc.1 via helm
2. Run the following commands

```
kubectl exec -it -n open-match openmatch-redis-node-0 -c redis -- redis-cli info replication | grep role
kubectl exec -it -n open-match openmatch-redis-node-1 -c redis -- redis-cli info replication | grep role
```

**Anything else we need to know?**:

**Output of `kubectl version`**:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T23:30:39Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.13", GitCommit:"39a145ca3413079bcb9c80846488786fed5fe1cb", GitTreeState:"clean", BuildDate:"2020-07-15T16:10:14Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Cloud Provider/Platform (AKS, GKE, Minikube etc.)**: 

minikube

**Open Match Release Version**:

v1.2.0-rc.1

**Install Method(yaml/helm):**:

```
helm repo add open-match https://open-match.dev/chart/stable
helm upgrade --install openmatch --namespace open-match --create-namespace open-match/open-match \
	  --version=v1.2.0-rc.1 \
	  --set open-match-customize.enabled=true \
	  --set open-match-customize.evaluator.enabled=true \
	  --set open-match-override.enabled=true
```

**Comment by syntxerror** [comment]
Thanks for catching this. We'll investigate why this is happening soon

**Comment by castaneai** [comment]
This also happens in v1.2.0. Any updates?

**Comment by castaneai** [comment]
As a temporary workaround, I specified the following value for helm install.

```
 --set redis.cluster.slaveCount=1
```

**Comment by dzmitry-lahoda** [comment]
may be use build in clustering with no sentinel https://github.com/googleforgames/open-match/issues/1409 ?
