### ISSUE TITLE
k8s go-client version is too old

### ISSUE THREAD

**Issue by hulucc** [googleforgames/open-match#1384]

**Comment by syntxerror** [comment]
Thank you for filing the issue. In the release notes we specify the minimum go version. If you believe there is benefit in updating the minimum go version, please provide some details as to why.

**Comment by markmandel** [comment]
I believe this is specifically talking about:
https://github.com/googleforgames/open-match/blob/main/go.mod#L61

Which targets Kubernetes 1.14, which is a tad old.

I'm not that familiar with Open Match architecuture - but not sure if it even needs client-go? Seems like it's only needed in [some tooling](https://github.com/googleforgames/open-match/search?p=1&q=client-go) that maybe should be pulled out in some way?

**Comment by syntxerror** [comment]
Ah I misread the title of the issue. Thanks for the clarification. 

@hulucc do you mind submitting a PR upgrading the go-client version?

**Comment by syntxerror** [comment]
Created an issue to resolve this. See #1448
