### ISSUE TITLE
query tickets returns old results

### ISSUE THREAD

**Issue by dzmitry-lahoda** [googleforgames/open-match#1407]
**What happened**:

1. At some point, query API started to return one very specific old ticket. 
2. I went to redis via port forward and found that there are many tickets
3. I cleared redis with flushall - did not help
4. I killed all OM pods in cluster
5. And query started to work well

On screenshot you see what query returned, and what Redis contained:

![image](https://user-images.githubusercontent.com/757125/128832411-157a31f3-123a-41d7-9ab3-b25d008c4091.png)

Original message https://open-match.slack.com/archives/CCD3H0L2D/p1628577448025500

**What you expected to happen**:

- Query returns actual results, not one day old. 

**How to reproduce it (as minimally and precisely as possible)**:

Not sure how that is possible. I doubt POST response are cached (and I did not setup caching on ingress which is nginx).

**Cloud Provider/Platform (AKS, GKE, Minikube etc.)**: 
AKS 1.18

**Open Match Release Version**:
chart: open-match-1.2.0

**Install Method(yaml/helm):**:
yaml

**Comment by dzmitry-lahoda** [comment]
I use backfill and i see query has cache 

![image](https://user-images.githubusercontent.com/757125/128834301-b700765f-ba01-4da5-815a-9bf9bbd6a90a.png)

**Comment by joeholley** [comment]
Could be a few things.  Could you post the contents of each of your Open Match k8s configMaps so we can assist in troubleshooting?
`# add -n <namespace> if necessary`
`kubectl get configMap <your-om-config-map> -o yaml `

**Comment by dzmitry-lahoda** [comment]
sorry for delay, will do before replacing build in redis with managed redis

**Comment by syntxerror** [comment]
@dzmitry-lahoda Were you able to resolve? We see that we're waiting for a dump of configmaps to continue.

**Comment by dzmitry-lahoda** [comment]
I do not observe issue for a long. so we use cloud redis on latest openmatch. we observe that ticket pile up and we need to clean them up (no ttl). but that afaik expected. 

I do not know if it still issue on sentinel in cluster redis.
