### ISSUE TITLE
control over/access to backfill id in MMF

### ISSUE THREAD

**Issue by dzmitry-lahoda** [googleforgames/open-match#1408]
**Is your feature request related to a problem? Please describe.**

I want to allow player ticket to target specific [backfill](https://github.com/googleforgames/open-match/issues/1240) , so players can join existing target servers.

**Describe the solution you'd like**

When I create backfill in MMF, I want to be able to generate its id via provided OM function to do so.  I want to put backfill ids into its search fields, so that tickets which target that game server can find it.

**Describe alternatives you've considered**

Right now I am scanning new created backfills and update these manually.

I did not considered allowing to connect not via MMF, as it has its own issues. 

Other alternative could be using match id. So when match ID is ready, it is added to backfield search fields, and later on to Agones label. So initial match which lead to backfill creation will be id to join.

**Additional context**

Because backfill update resets tickets assigned to it as I recall, it makes things harder to handle that out of MMF. I do not consider using Agones gameserver id as identifier because it will change on game crash migration, so I can retain backfill id.  (So reconnection tickets will include backfill id, and new backfill will be created with this)

**Comment by mridulji** [comment]
Hi @dzmitry-lahoda As we look at the problem statement I think:

1. We can implement a third case in [func createOrUpdateBackfill](https://github.com/googleforgames/open-match/blob/main/internal/app/backend/backend_service.go#L369) when `backfill.Id` is not `nil` or `empty` and backfill is not present in redis data so we can create a new backfill. And `backfill.Id` can be generated in MMF using `backfill.Id = xid.New().String()`.
2. There can be a workaround if we use `frontend_service.CreateBackfill` and then `frontend_service.UpdateBackfill` and then use that backfill created in our next steps. Only thing is `Generations` count will be 2 when backfill is being used for first time.

Let us know your thoughts on above points and workflow you are currently following.
Thanks

**Comment by dzmitry-lahoda** [comment]
we want all backfills to be unique identifiers, so when we crate them, and backfills exists - we prefer hard error, no upsert. so if id was provided from MMF, then when it up into storage, it is `insert or fail`, not `insert or update`. we assume that if there are 2 mmfs, they will not pick same backfill by filters. and if 2 matches creates  with backfills at same time, we can have them eliminated on stage of syncrhonizer/evaluator same way same ticket id does not gets 2 matches(backfill ticket id will not get 2 matches too),

**Comment by dzmitry-lahoda** [comment]
I thought how to do team join (players join in lobby and then connect to same server),  join running (one friends sends identifier of game to other players) and may be reconnect rejoin.  I think that backfill is potentially good ID to connect to. Agones server id is bad as it restarts on other cluster, etc. Backfill can be send to players, shared, etc. And it is active only if server is active.  So having more control over ids, can put into more places where users can grab it to work with. So BI can came from tickets, they matches and backfill is set.

**Comment by dzmitry-lahoda** [comment]
2. workaround is good if that works. so need to be sure that backfill will not be cleaned before TTL. also i dislike it as there will be backfill, but no game behind it. I am thinking that backfill represents server invite to player. no server - no active backfill. so kind of this backfill should be marked as non active until it goes thought MMF? but than it is like having own mapping GAME ---> nullable BACKFILL . so no sure.

**Comment by mridulji** [comment]
Workflow (2) can be implemented in MMF and then you can pass that created `backfill` in matches. So when there is an assignment to it, same is updated. Also you may use `backfill.PersistentField` to store any information from open-match's `v1.5.0` version. Please let us know if it solves the problem statement of this issue.

**Comment by dzmitry-lahoda** [comment]
persistet field likely will work
