### ISSUE TITLE
Tutorial: mm101-tutorial-frontend got "Failed to Get Ticket" errors

### ISSUE THREAD

**Issue by kongbong** [googleforgames/open-match#1418]
**What happened**:
I am doing tutorial, most of time I got "Failed to Get Ticket" errors in frontend pod.
If I uninstall open-match and reinstall again then sometimes it is solved but most time I got this error.
I did delete statefulset.apps/open-match-redis-node and create again but it is not fixed.

In the log Ticket was created successfully but it failed to get ticket with same id.

----
2021/09/12 23:16:11 Ticket created successfully, id: c4v8kevte7aqq3mre73g
2021/09/12 23:16:11 Ticket created successfully, id: c4v8kevte7aqq3mre740
2021/09/12 23:16:11 Failed to Get Ticket c4v8kevte7aqq3mre73g, got rpc error: code = NotFound desc = Ticket id: c4v8kevte7aqq3mre73g not found
---

**What you expected to happen**:
Not getting error and working well tutorials.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Output of `kubectl version`**: 
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:10:22Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}

**Cloud Provider/Platform (AKS, GKE, Minikube etc.)**: Docker-Desktop windows Kubernetes service.

**Open Match Release Version**: 1.2.0

**Install Method(yaml/helm):**: yaml

**Comment by kongbong** [comment]
Looks like the redis nodes were not synched each other

First of all I connected redis master node and tried to get ticketIds that has NotFound error.
---
127.0.0.1:6379> get c50fgk10g63t26ocj7a0
"\n\x14c50fgk10g63t26ocj7a0\"0\x12\x1b\n\x0fattributes.role\x12\brole.dps\x1a\x11mode.battleroyale2\x0c\b\xd0\xf0\x83\x8a\x06\x10\x84\x85\x99\xc5\x03"
127.0.0.1:6379> get c50fgtv1pc4lkudr69d0
(nil)
127.0.0.1:6379> get c50fgvn1pc4lkudr6ae0
"\n\x14c50fgvn1pc4lkudr6ae0\")\x12\x1c\n\x0fattributes.role\x12\trole.tank\x1a\tmode.demo2\x0c\b\xfe\xf0\x83\x8a\x06\x10\x8c\xa5\xaa\xa2\x01"
127.0.0.1:6379>
---

c50fgk10g63t26ocj7a0, c50fgvn1pc4lkudr6ae0 have still values but c50fgtv1pc4lkudr69d0 is not.

and then I connected redis slave node and query same ticketIds

---
127.0.0.1:6379> get c50fgvn1pc4lkudr6ae0
(nil)
127.0.0.1:6379> get c50fgk10g63t26ocj7a0
(nil)
127.0.0.1:6379> get c50fgk10g63t26ocj7a0
(nil)
127.0.0.1:6379> get c50fgtv1pc4lkudr69d0
"\n\x14c50fgtv1pc4lkudr69d0\"0\x12\x1b\n\x0fattributes.role\x12\brole.dps\x1a\x11mode.battleroyale2\x0c\b\xf7\xf0\x83\x8a\x06\x10\xbc\xd6\x8c\x83\x03"
127.0.0.1:6379> exit
---

c50fgk10g63t26ocj7a0, c50fgvn1pc4lkudr6ae0 don't have values but c50fgtv1pc4lkudr69d0 exists.
so, I guess frontend connected one of master or slave and query the ticket but failed because it is not synced.
and looks like redis nodes are not synced later so it is not eventually consistent.

**Comment by JJhuk** [comment]
I got same errors

**Comment by gyusang** [comment]
Running `kubectl delete -n open-match pod open-match-redis-node-1` fixed the problem.

When open-match is installed, it seems that two redis nodes are competing, and are both assigned master.
You can check the logs by running
```
kubectl logs -n open-match open-match-redis-node-0 redis
kubectl logs -n open-match open-match-redis-node-1 redis
```
both nodes echo "I am master" in the beginning.

When we delete one redis pod, the ReplicaSet creates another redis pod.
This time, there is already a "master" redis, so no conflict occurs and the new pod becomes a redis slave node.
