### ISSUE TITLE
Backfill ticket can not be queried back

### ISSUE THREAD

**Issue by lihaif** [googleforgames/open-match#1434]
**What happened**:

We implemented the backfill logic based on Open Match backfill workflow. But the test randomly fails in our CI environment. After I recreated the issue, I found that it relates to the case that the backfill ticket can not be queried. The backfill ticket is creates successfully, but the query request returns nothing from Open Match Query service.

Below is the result I tried using curl command when this issue happened.

Firstly proxy forward the Open Match Frontend and Open Match Query pods to the local host so that I can run curl commands to verify the behavior.

```
$ kubectl port-forward kepler-32246-open-match-query-6d7f59899f-n4h8v -n kepler-ci 51503
$ kubectl port-forward kepler-32246-open-match-frontend-5866b7444c-8vjjc -n kepler-ci 51504
```

Then create a backfill ticket and a player ticket and try to query them back. You can find that the player ticket returns correctly while the backfill ticket is not returned.

```
$ curl -X POST http://localhost:51504/v1/frontendservice/backfills --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"backfill": {"id": "1", "search_fields": {"double_args": {"kepler.random": 0.048817882191964146, "tier": 1}, "string_args": {"kepler.id": "WG:10004803128", "kepler.poolId": "backfillmore"}}, "extensions":{}}}'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   464  100   255  100   209    208    170  0:00:01  0:00:01 --:--:--   379{"id":"c7cj2fq573498f430oag", "search_fields":{"double_args":{"kepler.random":0.048817882191964146, "tier":1}, "string_args":{"kepler.id":"WG:10004803128", "kepler.poolId":"backfillmore"}}, "create_time":"2022-01-08T06:37:51.406482220Z", "generation":"1"}
(python38vm2)
$ curl -X POST http://localhost:51503/v1/queryservice/backfills:query -H 'Content-Type: application/json' -d '{"pool":{"name":"backfillmore"}}'                                                                                           % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    32    0     0  100    32      0     26  0:00:01  0:00:01 --:--:--    26
(python38vm2)
$ curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"ticket": {"id": "b","search_fields":{"string_args":{"type":"test"}},"extensions":{}}}' http://localhost:51504/v1/frontendservice/tickets
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   213  100   126  100    87    102     70  0:00:01  0:00:01 --:--:--   173{"id":"c7cj2sq573498f430ob0", "search_fields":{"string_args":{"type":"test"}}, "create_time":"2022-01-08T06:38:43.634333666Z"}
(python38vm2)
$ curl -X POST http://localhost:51503/v1/queryservice/tickets:query -H 'Content-Type: application/json' -d '{"pool":{"name":"backfillmore"}}'                                                                                             % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   182    0   150  100    32    121     25  0:00:01  0:00:01 --:--:--   147{"result":{"tickets":[{"id":"c7cj2sq573498f430ob0","search_fields":{"string_args":{"type":"test"}},"create_time":"2022-01-08T06:38:43.634333666Z"}]}}
```

**What you expected to happen**:

We expect that Open Match Query service can always return the backfill tickets if the right filters are provided.

**How to reproduce it (as minimally and precisely as possible)**:

This issue does not always happen. Our CI install/delete Open Match deployment for each pipeline using exactly the same command. And this issue randomly happens in some cases. We are not sure how to accurately recreate this issue.

**Anything else we need to know?**:

**Output of `kubectl version`**:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Cloud Provider/Platform (AKS, GKE, Minikube etc.)**: 

Kubernetes cluster hosted by our IT

**Open Match Release Version**:

Open Match 1.3.0

**Install Method(yaml/helm):**:

Open Match helm chart is a sub-chart of our helm chart with below config:

```
open-match:
  enabled: true
  query:
    replicas: 1
  frontend:
    replicas: 1
  backend:
    replicas: 1
  evaluator:
    replicas: 1
  function:
    replicas: 1
  redis:
     master:
       persistence:
           enabled: false
     slave:
       persistence:
           enabled: false
```

**Comment by mridulji** [comment]
Hey @lihaif, I tried to reproduce this issue and found that scaling down redis deployment to 1 solves the problem. Also there is change in redis chart version in the latest [release](https://github.com/googleforgames/open-match/releases/tag/v1.4.0-rc.1). Could you try it with `v1.4.0-rc.1` to see if the probelm persists? I Hope it helps.

**Comment by lihaif** [comment]
Hey @mridulji, I also found that scaling down Redis to 1 solves this issue. But it does not sound like the proper solution. BTW, I left my previous company and I had no environment to test this. I will ask somebody else to follow up on this.

**Comment by ZakHam** [comment]
Hi @mridulji thanks for looking into this. I will test using version `v1.4.0-rc.1` and report back.

**Comment by mridulji** [comment]
Thanks for replying, I am closing the issue by assuming it is resolved. Feel free to re-open if still facing the problem.
