### ISSUE TITLE
values.yaml in Helm release looks broken

### ISSUE THREAD

**Issue by tmokmss** [googleforgames/open-match#1442]
**What happened**:
Hi team, though I'm not entirelly sure if it is a bug or not, could you check it when you get a chance? Thanks! 

When I `helm pull` the latest open-match release, the downloaded `values.yaml` looks broken.

The actual file is here: https://pastebin.pl/view/280b03ad 
We can find much duplicated code here and it looks totally different from [the file in repo](https://github.com/googleforgames/open-match/blob/main/install/helm/open-match/values.yaml).

**What you expected to happen**:
The file is same as [the file in repo](https://github.com/googleforgames/open-match/blob/main/install/helm/open-match/values.yaml).

**How to reproduce it (as minimally and precisely as possible)**:
```sh
helm pull open-match/open-match --version=1.3.0
tar zxvf open-match-1.3.0.tgz
cat open-match/values.yaml
```

**Anything else we need to know?**:

**Output of `kubectl version`**:
n/a

**Cloud Provider/Platform (AKS, GKE, Minikube etc.)**: 
n/a

**Open Match Release Version**:
1.3.0

**Install Method(yaml/helm):**:
helm

```
$ helm version
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.17.3"}
```

**Comment by mridulji** [comment]
Hey @tmokmss, Nice catch!!! the `values.yaml` [file in repo](https://github.com/googleforgames/open-match/blob/main/install/helm/open-match/values.yaml) is indeed different from what it is in packaged file downloaded from helm pull. Could you also share if you are facing any problem due to this or is it causing to break in installation process?

**Comment by tmokmss** [comment]
Hi @mridulji No it does not exactly have a runtime problem; it seemed to work properly even though yaml looks broken.
The only problem I faced was when I ran `helm pull` and manually edited the yaml to change unexposed variables for this helm package. Since it was somewhat obfuscated, it was difficult to edit manually 😅

**Comment by mridulji** [comment]
So did that work finally? 🤔 just wondering if you could use `make install/yaml` command to generate yaml files if need to make any customisation.

**Comment by tmokmss** [comment]
Yes it worked as far as I checked. If it is an expected behavior it's okay to close this issue :) I just created it to confirm if it's a bug or not.

**Comment by mridulji** [comment]
Thanks for your view. Let's wait for a week and see if anyone has objection before marking it as closed.
