### ISSUE TITLE
Not possible to deploy Open  Match to EKS

### ISSUE THREAD

**Issue by Bardin08** [googleforgames/open-match#1454]
**What happened**:
It's impossible to deploy an open match to the EKS (Amazon Kubernetes Service).

I strictly followed the installation instruction hosted at https://open-match.dev/site/docs/installation/yaml/.

1. I've created the EKS cluster with `eksctl` command
```sh
$ eksctl create cluster --region eu-central-1 --name <cluster-name> --kubernetes-version 1.21
```

2. Then, I've added the nodes group with a command
```sh
$ eksctl create nodegroup --config-file=<config-file-path>
```

3. I've copy-and-paste commands from the open-match docs
```sh
# Install the core Open Match services.
$ kubectl apply --namespace open-match \
  -f https://open-match.dev/install/v1.4.0-rc.1/yaml/01-open-match-core.yaml

$ kubectl apply --namespace open-match \
  -f https://open-match.dev/install/v1.4.0-rc.1/yaml/06-open-match-override-configmap.yaml \
  -f https://open-match.dev/install/v1.4.0-rc.1/yaml/07-open-match-default-evaluator.yaml
```

4. I've used a command to check the pods
```sh
$ kubectl get -n open-match pod
```
And it showed me that containers are in `ContainerCreation` status.
```
$ kubectl get -n open-match pod
NAME                                       READY   STATUS              RESTARTS   AGE
open-match-backend-54697ffc96-2hsgh        0/1     ContainerCreating   0          34s
open-match-backend-54697ffc96-kq599        0/1     ContainerCreating   0          34s
open-match-backend-54697ffc96-xlm87        0/1     ContainerCreating   0          34s
open-match-frontend-7f8d75f6dd-4crr5       0/1     ContainerCreating   0          34s
open-match-frontend-7f8d75f6dd-f6t8n       0/1     ContainerCreating   0          34s
open-match-frontend-7f8d75f6dd-vhmhf       0/1     ContainerCreating   0          34s
open-match-query-7c9ccf45bd-5cv7j          0/1     ContainerCreating   0          34s
open-match-query-7c9ccf45bd-kwlxx          0/1     ContainerCreating   0          34s
open-match-query-7c9ccf45bd-wxkd9          0/1     ContainerCreating   0          34s
open-match-redis-node-0                    0/3     Pending             0          32s
open-match-swaggerui-d78fbb7fb-llzt8       0/1     ContainerCreating   0          34s
open-match-synchronizer-86c556f7dd-f88c4   0/1     ContainerCreating   0          33s
```

I waited for 15 mins and rechecked the pods. The response was the same.

5. I've checked pods details at AWS Console and saw that there is no required volume `om-config-volume-override`.
![image](https://user-images.githubusercontent.com/67170413/164709080-830a75e8-3083-4224-94f0-8cda93f6b6c4.png)

**What you expected to happen**:
Open match successfully deployed and ran at EKS. All containers are created and run.

**How to reproduce it (as minimally and precisely as possible)**:
Follow my steps from the first section

**Anything else we need to know?**:

**Output of `kubectl version`**:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"windows/amd64"}

Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.9-eks-0d102a7", GitCommit:"eb09fc479c1b2bfcc35c47416efb36f1b9052d58", GitTreeState:"clean", BuildDate:"2022-02-17T16:36:28Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
```

**Cloud Provider/Platform (AKS, GKE, Minikube etc.)**: EKS

**Open Match Release Version**: 1.4.0-rc.1

**Install Method(yaml/helm):**: yaml

**Comment by syntxerror** [comment]
Hey @Bardin08. It looks like you need to deploy the default evaluator in the [next step](https://open-match.dev/site/docs/installation/yaml/#install-the-default-evaluator) and your pods should start running. Give it a shot and let me know if that resolves.

**Comment by mridulji** [comment]
Hey @Bardin08, May I get to know if you are still facing this issue? And also have you tried deploying any other version of Open-Match on EKS let's say `v1.3.0`?

**Comment by Bardin08** [comment]
@mridulji, I haven't tried to deploy the `v1.3.0`. I'd fix the `v1.4.0-rc1,` and it worked for me.

**Comment by mridulji** [comment]
Great!!👍🏻. Would love if you share what fix worked for you. That may be helpful to others as well.

**Comment by mridulji** [comment]
Closing the issue as it is resolved, Please re-open if facing this issue.
