### ISSUE TITLE
Is it possible to deploy open-match without using Kubernetes?

### ISSUE THREAD

**Issue by duong2179** [googleforgames/open-match#1466]

**Comment by mridulji** [comment]
There are couple of Issues 👉🏻 #1303 and #1451 In which deploying Open-Match on cloud run is being discussed. Also kubernetes is helpful as it provides functionalities like scaling, management of containerized applications etc. Would you like to share what exactly are you looking for?

**Comment by duong2179** [comment]
Hi, our system is pretty small but I still want to take this chance to learn open-match. I am thinking of deploying the system using minikube on my own server (not a cloud provider). But the open-match module needs to communicate with other modules of the system deployed by docker-compose. This makes things more complicated I believe. If it's possible then I would like to deploy open-match using docker-compose as well.

**Comment by mridulji** [comment]
It would be great if you share in this space or on slack with the folks about new and amazing ways you try out of using open-match.

**Comment by MaxHayman** [comment]
Here is an example of running openmatch in a docker compose.

[openmatch-docker.zip](https://github.com/user-attachments/files/17733680/openmatch-docker.zip)
