### ISSUE TITLE
How to setup up Match Funtion with Open Match using .net server

### ISSUE THREAD

**Issue by SomendraDev** [googleforgames/open-match#1473]
This package helps in interaction with Open Match :
https://github.com/FrozenStormInteractive/openmatch-csharp

![image](https://user-images.githubusercontent.com/106752882/177558514-dbfa1668-9446-4f60-bf27-f2bf0307c042.png)

But, I want to know how match function written using this package will interact with Open Match? Do I need to set ip and port in .yml for match function running in .net api server?

**Comment by SomendraDev** [comment]
Thank you @mridulji , but where do i define the function name that needs to be called?

**Comment by SomendraDev** [comment]
I tried to generate protobuf for .net for match function. But getting following errors : 
![image](https://user-images.githubusercontent.com/106752882/178108716-aba2f469-1221-4725-b7b6-44368bdab387.png)
Please help to fix it.

**Comment by SomendraDev** [comment]
I got solution to this problem by using this package : https://github.com/FrozenStormInteractive/openmatch-csharp
![image](https://user-images.githubusercontent.com/106752882/178143188-bde32924-4eed-426b-8428-22c0c99ffc54.png)

I am running the open match in minikube and I am easily able to communicate with frontend and backend of open match.
![image](https://user-images.githubusercontent.com/106752882/178143718-814ab1d6-4e7e-4c19-97a6-e7f3619e38d9.png)
But, now I am running match function grpc service at (https://127.0.0.1:50502), so I want this match function to be called by open match, whenever I call  FetchMatches with the specified MatchProfile. 

This helps in testing match function without deployment. Please help

**Comment by SomendraDev** [comment]
I tried deploying open-match-function from demo on minikube open-match namespace, but I am getting following error : 
![image](https://user-images.githubusercontent.com/106752882/178156312-ea35cba3-f2e2-42ac-bffa-2a21ab273dba.png)

Please help

**Comment by SomendraDev** [comment]
I had solved the issue many weeks ago, actually the issue was label selector was wrong, after fixing it, everything is working fine.

**Comment by mridulji** [comment]
Thanks @SomendraDev for your feedback, I am marking this issue as closed.

**Comment by ggrafhalfbrick** [comment]
> I had solved the issue two weeks ago, actually the issue was label selector was wrong, after fixing it, everything is working fine.

Hi @SomendraDev, can you elaborate on what the "label selector" was in your case. I'm trying the same and am stuck at the same issue as you had.
