### ISSUE TITLE
`open-match-redis-node-0` pod gets stuck at Pending due to `1 pod has unbound immediate PersistentVolumeClaims`

### ISSUE THREAD

**Issue by duong2179** [googleforgames/open-match#1478]
I downloaded the yaml file from https://open-match.dev/install/v1.4.0-rc.1/yaml/01-open-match-core.yaml and updated the replicas for backend, frontend, and query from 3 to 1. I then started the open-match core cluster on my single node kubernetes (with master node untainted already) as below:

```
$ kubectl apply --namespace open-match -f 01-open-match-core.yaml
$ kubectl apply --namespace open-match -f 06-open-match-override-configmap.yaml -f 07-open-match-default-evaluator.yaml
```

But the `open-match-redis-node-0` pod gets stuck at Pending due to `1 pod has unbound immediate PersistentVolumeClaims`:

```
$ kubectl get pods -n open-match
NAME                                       READY   STATUS    RESTARTS   AGE
open-match-backend-6d89b9b97b-t44v7        0/1     Running   0          9m30s
open-match-evaluator-bd58b67d4-kvsql       1/1     Running   0          9m30s
open-match-frontend-84bfd6f78-6gfcf        0/1     Running   0          9m30s
open-match-query-6998df8fb4-6w9nm          0/1     Running   0          9m30s
open-match-redis-node-0                    0/3     Pending   0          9m30s
open-match-swaggerui-6cb586ccbb-8qnnl      1/1     Running   0          9m30s
open-match-synchronizer-7fc6fcc8db-4jzx5   0/1     Running   0          9m30s
```

Describing `open-match-redis-node-0` gave me this:

```
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  4m57s (x2 over 10m)  default-scheduler  0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.
```

Getting PVCs returned `redis-data-open-match-redis-node-0` volume at `Pending`:

```
$ kubectl get pvc --all-namespaces
NAMESPACE    NAME                                 STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
open-match   redis-data-open-match-redis-node-0   Pending
```

Describing the persistent volume gave me `no persistent volumes available for this claim and no storage class is set` error:

```
Events:
  Type    Reason         Age                 From                         Message
  ----    ------         ----                ----                         -------
  Normal  FailedBinding  76s (x42 over 11m)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
```

What am I doing wrong?

**Comment by mridulji** [comment]
Hey @duong2179,  would you like to troubleshoot based on below queries ?

> replicas for backend, frontend, and query from 3 to 1

Is it the only change you are making ? I also updated `replicas: 3` to `replicas: 1` and open-match deploys successfully.

> started the open-match core cluster on my single node kubernetes (with master node untainted already)

Which platform are you using to delpoy open-match ?

> But the open-match-redis-node-0 pod gets stuck at Pending due to 1 pod has unbound immediate PersistentVolumeClaims

Is sufficient CPU provided to start-up redis node ?

**Comment by mridulji** [comment]
Interesting to see this. I actually encountered such an error but it was due to insufficient CPU so machine type was changed to `n1-standard-4` [Reference](https://github.com/googleforgames/open-match-docs/pull/243) . But I am still not clear which platform it is? (GKE, EKS, Minikube etc)

Would you like to try on GKE (if not doing on it) following the [documentation](https://open-match.dev/site/docs/installation/) and verify if same issue occurs?

**Comment by duong2179** [comment]
@mridulji Well, I run the system on my own desktop (yes, for learning purposes). I followed [Creating a cluster with kubeadm](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm) and created a single node cluster using `kubeadm`.

**Comment by syntxerror** [comment]
Is it possible to test this against minikube? I suspect that there are some features missing from kubeadm that aren't meant for running (semi) production use cases such as an Open Match tutorial. If it was required to move the number of replicas from 3 to 1 then there likely are some other things that were not accounted for. I want to ensure that this is a bug and not a use case that likely needs a solution with a commit to Open Match.

**Comment by mridulji** [comment]
Thanks for bringing up this issue and sharing the resolution steps, It would be very helpful when trying open-match on kubeadm. Marking this issue as closed. Feel free to re-open if needed.

Thanks 🙂
