### ISSUE TITLE
Helm chart broken when using Redis password with BYO-Redis

### ISSUE THREAD

**Issue by corradomatt** [googleforgames/open-match#1479]
**What happened**:
The OpenMatch helm chart is broken when using a custom Redis deployment which also uses a password.

---

**What you expected to happen**:
The helm chart should build the K8s manifests correctly as it would with version `1.0.0` when using a custom Redis deployment with a password set.

---

**How to reproduce it (as minimally and precisely as possible)**:
Run the following Helm template command...
```shell
helm template open-match/open-match --version 1.3.0 --set redis.usePassword=true --set open-match-core.redis.enabled=false
```

If you run the above command with `--version 1.0.0` the K8s manifests are generated correctly.

---

**Anything else we need to know?**:
Resulting error:
```shell
Error: template: open-match/templates/synchronizer.yaml:71:12: executing "open-match/templates/synchronizer.yaml" at <include "openmatch.volumes.withredis" .>: error calling include: template: open-match/templates/_helpers.tpl:115:19: executing "openmatch.volumes.withredis" at <include "call-nested" (list . "redis" "redis.fullname")>: error calling include: template: open-match/templates/_helpers.tpl:225:4: executing "call-nested" at <include $template (dict "Chart" (dict "Name" (last $subchart)) "Values" $values "Release" $dot.Release "Capabilities" $dot.Capabilities)>: error calling include: template: no template "redis.fullname" associated with template "gotpl"
```

**Output of `helm version`**:
```shell
$ helm version
version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.6"}
```

**Cloud Provider/Platform (AKS, GKE, Minikube etc.)**: N/A

**Open Match Release Version**: 1.3.0

**Install Method(yaml/helm)**: helm

**Comment by mridulji** [comment]
Hey @corradomatt, Would you like to try generate `yaml` using command `make install/yaml/01-open-match-core.yaml` after editing `makefile` like this👇🏻
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/94632788/181001587-e292f1b4-2791-4c4e-8302-d01b34b0f0ab.png">

**Comment by mridulji** [comment]
Closing this issue due to no response / staleness.

@corradomatt, Please feel free to re-open it if the still facing the problem.

**Comment by corradomatt** [comment]
Generating the YAML by downloading this repo and running a `make` command doesn't help me unfortunately since I'm installing Open Match with ArgoCD as a helm chart directly from your helm chart repo.

I did run the `make` command as suggested though and ran into dependency issues with the chart....

```shell
$ make install/yaml/01-open-match-core.yaml
mkdir -p ~/testing/open-match/build/toolchain/bin
mkdir -p ~/testing/open-match/build/toolchain/temp-helm
cd ~/testing/open-match/build/toolchain/temp-helm && curl -Lo helm.tar.gz https://get.helm.sh/helm-v3.8.0-darwin-amd64.tar.gz && tar xzf helm.tar.gz -C ~/testing/open-match/build/toolchain/bin --strip-components 1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.6M  100 13.6M    0     0  7735k      0  0:00:01  0:00:01 --:--:-- 7772k
rm -rf ~/testing/open-match/build/toolchain/temp-helm/
mkdir -p install/yaml/
~/testing/open-match/build/toolchain/bin/helm template open-match --no-hooks --namespace open-match --set usingHelmTemplate=true --set global.image.registry=gcr.io/rocket-league-prime-load-test --set global.image.tag=0.0.0-dev-4d6da16 \
		--set-string global.telemetry.jaeger.agentEndpoint="open-match-jaeger-agent:6831" \
		--set-string global.telemetry.jaeger.collectorEndpoint="http://open-match-jaeger-collector:14268/api/traces" \
		install/helm/open-match > install/yaml/01-open-match-core.yaml
Error: An error occurred while checking for chart dependencies. You may need to run `helm dependency build` to fetch missing dependencies: found in Chart.yaml, but missing in charts/ directory: redis, open-match-telemetry, open-match-customize, open-match-scale
make: *** [install/yaml/01-open-match-core.yaml] Error 1
```

**Comment by mridulji** [comment]
Thanks for your response, I am re-opening this issue.

Interesting to see this error because `build/toolchain` handles it which includes downloading and updating helm chart dependencies. Would you try once deleting `build` folder and then run the `make install/yaml/01-open-match-core.yaml`. if it doesn't resolves then change directory to `install/helm/open-match/` and run command `helm dependency update`. 

One other way could be to use command `make install-chart` for installing open-match. Please find if that is useful. 

Please let me know what you come up with above troubleshooting.

**Comment by mridulji** [comment]
Open-match `v1.4.0` stable release is out now. Would you like to try it on the latest version ? Please let us know what you come up with. Thanks.

**Comment by corradomatt** [comment]
We ended up creating our own Helm chart for Open Match.

**Comment by mridulji** [comment]
Thanks for your response, Marking this issue as closed.
