### ISSUE TITLE
'Matchmaking' metrics on player and profile behavior

### ISSUE THREAD

**Issue by syntxerror** [googleforgames/open-match#1482]
**Is your feature request related to a problem? Please describe.**
Open Match exposes metrics via Grafana/Prometheus on the performance of Open Match core functionality but many folks would find metrics on the behavior of the player population beneficial as well. There are several issues (#683 & #1312 ) are examples of this ask. Adding these (by default) on an evolving dashboard would be helpful to many.

**Describe the solution you'd like**
New metrics added to Open Match and new dashboard created to accompany it. A rolling update of new metrics on either matchmaking (player, profile, etc.) and matchmaker (matches made, memory usage, etc.) added on a steady basis. Issue can be reopened should new metrics be requested. 

**Describe alternatives you've considered**
The stats service (#683) and [its design ](https://github.com/googleforgames/open-match/issues/683#issuecomment-1106943731)was considered but leveraging the metrics and dashboards right now would be useful. Should a new feature be needed based on the added metrics, both the stats service issue and a new feature request should be opened.

**Additional context**

**Comment by scosgrave** [comment]
The following are metrics I think would be useful for gaining visibility into the tickets existing in Open Match:

1. Count of tickets that are currently seeking matches
   - Uses:
     - This metric helps users of Open Match get a better idea of the total number of tickets in Open Match's database
     - A long downward trend in this metric might indicate that there is trouble ingesting more players into Open Match
   - Implementation Notes:
     - this metric is incremented when:
       - ticket is created
       - ticket transitions back to active after being associated with a match and returned by FetchMatches (after the pendingReleaseTimeout)
     - this metric is decremented when:
       - tickets become assigned
       - go into pending release because they are associated with a match
       - ticket is deleted by user
2. Count of tickets that are in the Release Pending state
   - Uses:
     - A user may be able to detect that assignments are not happening by seeing an accumulation of tickets in this state
     - A user may be able to detect that backfill acknowledgement is not happening by seeing an accumulation of tickets in this state
     - This metric helps users of Open Match get a better idea of the total number of tickets in Open Match's database 
3. Count of tickets that are in the Assigned state
   - Uses:
     - This metric helps users of Open Match get a better idea of the total number of tickets in Open Match's database 
   - Reasons against implementing it:
     - Difficult to count because Redis does automatic cleanup of these tickets
     - There is a metric recording the number of tickets in an assignment already, so we can see the rate at which tickets are being assigned over time
4. Count of Backfill Tickets in any state in the Database
   - Uses:
     - Detect that game servers are able to create backfill tickets
     - If a game is issuing a single backfill ticket per needed player, then game teams will be able to see how many out-standing requests for players game servers have
     - This metric helps users of Open Match get a better idea of the total number of tickets in Open Match's database 
5. Count of calls to Fetch Matches per registration interval
   - Uses:
     - Detect that a Director is requesting matches
     - Detect that the Director is making FetchMatches requests for all the desired MatchProfiles
     - Detect that the Director is able to fit all the FetchMatches requests into a single registration interval, and if it should be expanded

**Comment by syntxerror** [comment]
Checklist for metrics pushed
- [ ] Count of tickets that are currently seeking matches
- [ ] Count of tickets that are in the Release Pending state
- [ ] Count of tickets that are in the Assigned state (optional)
- [ ] Count of Backfill Tickets in any state in the Database
- [ ] Count of calls to Fetch Matches per registration interval

**Comment by syntxerror** [comment]
going to close and ask for individual metric issues to be created
