### ISSUE TITLE
Release tag might be wrong

### ISSUE THREAD

**Issue by RY-2718** [googleforgames/open-match#1484]
**What happened**:
Git tag for release v1.4.0 is `1.4.0`, not `v1.4.0` .

**Anything else we need to know?**:
Latest version of Go SDK is still `v1.3.0` .

**Comment by mridulji** [comment]
Oh! looks like a typing mistake. Just added tag `v1.4.0` to the `release-1.4` branch and everything looks good now. Also updated indexing of Go SDK to `v1.4.0` as `latest`. Thanks for raising the issue, Closing it as it's now resolved but feel free to re-open still facing problem.
