### ISSUE TITLE
Add custom annotations to service account

### ISSUE THREAD

**Issue by sierrasoleil** [googleforgames/open-match#1485]
### Requirements
I need to be able to add custom annotations to the service account attached to the OpenMatch pods. My specific use case is for Workload Identity in GKE, but the change should allow arbitrary annotations.

[This PR](https://github.com/googleforgames/open-match/pull/1469) allows annotations to be added to the values file as a list under `serviceAccountAnnotations:`.

**Comment by syntxerror** [comment]
Thanks for filling the issue to go alongside the PR. I've reviewed the PR. In the future, we ask if you would follow the template when filing either a bug or feature request so it helps with labels and feature tracking. Thanks again for submitting the PR for this.

**Comment by sierrasoleil** [comment]
Thanks for the review! I did look at the templates, but it wasn't really clear to me which one was appropriate. I guess for future reference this would count as a "feature request."

**Comment by syntxerror** [comment]
Ah sorry if it confused you. We'll take a look at it to clear up some of the terminology to help you decide better. I approved and merged the PR. Thanks for contributing
