### ISSUE TITLE
Using Redis Enterprise for Openmatch core

### ISSUE THREAD

**Issue by laivu266** [googleforgames/open-match#1486]
Hi there,

For persistent data, I would like to using an external redis tool such as Redis enterprise for OM core.
How can custom helm chart?
Thanks.

**Comment by mridulji** [comment]
Hi @laivu266, you can configure your redis by disabling it and mention your custom redis deployment instead by following this 👉🏻 [documentation](https://open-match.dev/site/docs/guides/production/#use-alternative-to-included-redis-bitnami-image). Also if you want to install using yaml files, you would need to generate those files  by command ` make install/yaml/` making changes in `/install/helm/open-match/values.yaml` file.

**Comment by laivu266** [comment]
Hi @mridulji ,
Because I used Redis enterprise, I need to inject password in redis connection. So how can I inject redis password into helm values?
Thanks

**Comment by syntxerror** [comment]
@laivu266 how are you deploying Redis? That would give us some more insight on a path. You can deploy and set the password during deployment or store it as a k8s secret.

**Comment by laivu266** [comment]
hi @syntxerror ,
This is my helm value command
`helm install open-match open-match/open-match --set open-match-customize.enabled=true --set open-match-customize.evaluator.enabled=true --set open-match-override.enabled=true --set open-match-core.redis.enabled=false --set open-match-core.redis.hostname="user:password@redis-endpoint" --set open-match-core.redis.port=<redis-port> -nopen-match`
It looks like weakly security

**Comment by syntxerror** [comment]
@laivu266 This seems like the recommended approach for deploying Open Match with Redis Enterprise. We're publishing a tutorial on this soon and is recommended from some folks over at Redis. I will double check but I'm pretty sure this is the way to go
