### ISSUE TITLE
Too many redis connections

### ISSUE THREAD

**Issue by khanhsipher** [googleforgames/open-match#1489]
**What happened**:
I just did a load test with openmatch & agones and I got an unexpected result when monitoring redis. There are too many redis connections created. I am concerning that problem. Why not to re-use redis connections each process?

**What you expected to happen**:
Re-use redis connections.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Output of `kubectl version`**:

**Cloud Provider/Platform (AKS, GKE, Minikube etc.)**: 

**Open Match Release Version**:

**Install Method(yaml/helm)**:

**Comment by mridulji** [comment]
Hi @khanhsipher, There are multiple connections to redis because we need to connect to it from different microservices i.e. `frontend`, `backend`, `synchronizer` & `query` for the pools in config. I think if there are few connections, it may not be an issue so how many connections exactly you are seeing being created?

**Comment by khanhsipher** [comment]
![image](https://user-images.githubusercontent.com/102130038/187326688-5ec51cfa-bbfc-48e3-b27f-bf48911034da.png)
Thanks @mridulji for replying me. As you see I got 500 connections created

**Comment by khanhsipher** [comment]
I see config in source code. 
`// Maximum number of idle connections in the pool.
	MaxIdle int

	// Maximum number of connections allocated by the pool at a given time.
	// When zero, there is no limit on the number of connections in the pool.
	MaxActive int

	// Close connections after remaining idle for this duration. If the value
	// is zero, then idle connections are not closed. Applications should set
	// the timeout to a value less than the server's timeout.
	IdleTimeout time.Duration`
Currently, I set zero to MaxActive it may be the root cause. Can u share me best practice for these params.

**Comment by mridulji** [comment]
Hey @khanhsipher Thanks for sharing your investigations along with pictures. It is normal behaviour of `open-match` to create that many connections but it also depends on how many pools you have created in load test. I recommend calculating how many pools are being created and see if it aligns with the number of connection count. The configs in `values.yaml` and `values-production.yaml` are suggested as best practice to follow.

**Comment by mridulji** [comment]
I hope the calculation fits well in the situation. Closing this issue due to no response/ staleness. Please feel free to re-open if still having doubts/confusion.
