### ISSUE TITLE
Found CRITICAL Vulnerability in your website !

### ISSUE THREAD

**Issue by imchiragprajapati** [googleforgames/open-match#1521]
Hello I am Chirag Prajapati a Certified Penetration Tester and Ethical Hacker my License no is: 10188-161-078-1726.

We would like to inform you that, a security vulnerability affecting your website.

Affected Website: openmatch.dev

Following the ISO/IEC 29147 (“Information technology — Security techniques — Vulnerability disclosure”) guidelines, we verified the vulnerability's existence prior to notifying you. Please connect with us for technical details of the vulnerability, 
The researcher may also help remediate the vulnerability if you need any assistance.

For more information I request you to kindly revert me back so that I can share with you the report !
Looking forward to hearing from you !

**Comment by markmandel** [comment]
To report a security issue, please use http://g.co/vulnz. We use http://g.co/vulnz for our intake, and do coordination and disclosure here on GitHub (including using GitHub Security Advisory). The Google Security Team will respond within 5 working days of your report on g.co/vulnz.

Closing the issue and will respond to the report when it is made.

**Comment by imchiragprajapati** [comment]
Hello Sir,
I have reported the Vulnerability on Google VRP Portal.
Issue: 266817191

Thanks for guiding me Sir.

**Comment by imchiragprajapati** [comment]
Hello Sir,
Did you know about the CVE Bug in the Swagger File ?

**Looking forward to hearing from you ?**

**Comment by markmandel** [comment]
Received! Thanks for letting us know - we'll jump on it.
