### ISSUE TITLE
Add Skaffold configurations

### ISSUE THREAD

**Issue by jeremyje** [googleforgames/open-match#163]
The build to deployment cycle is quite long for Open Match with many moving parts. The Makefile eases a lot of the moving parts side but the time could be much faster for local development. [Skaffold](https://github.com/GoogleContainerTools/skaffold) is a tool that specializes in this and can even do fancy things like build on save and deploy to Minikube without the need for an image repository.

**Comment by thisisnotapril** [comment]
Closing; not applicable
