### ISSUE TITLE
Improvements to the instructions.

### ISSUE THREAD

**Issue by jeremyje** [googleforgames/open-match#168]
Split the instructions into user of Open Match and contributors of Open Match.
 * Add a codelab to create an MMF, Evaluator, and Director.
 * Users of Open Match instructions should not assume access to the Git repository unless it’s absolutely necessary and call it out.
 * Beef up the contributors section.

**Comment by sawagh** [comment]
https://github.com/googleforgames/open-match/issues/506 tracks all documentation changes. Have added a reference to this issue there. Aggregating all into a single documentation issue and closing the individual ones.
