### ISSUE TITLE
failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

### ISSUE THREAD

**Issue by somendra1221** [googleforgames/open-match#1680]
Please help in how to fix this issue : 
![image](https://github.com/googleforgames/open-match/assets/77610902/2936bd15-ff1a-483e-b047-3aed7ac353ec)

For this dockerfile of example provided :

`FROM open-match-base-build as builder

WORKDIR /go/src/open-match.dev/open-match/examples/functions/golang/soloduel
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o matchfunction .

FROM gcr.io/distroless/static:nonroot
WORKDIR /app/
COPY --from=builder --chown=nonroot /go/src/open-match.dev/open-match/examples/functions/golang/soloduel/matchfunction /app/

ENTRYPOINT ["/app/matchfunction"]`

**Comment by joeholley** [comment]
You're going to need to use the make file to build the open match docker images. The docker build steps in the makefile first builds images with all the prerequisites, which are then used as the base of later docker builds (one is used in the `FROM open-match-base-build as builder` Dockerfile line you quoted in your issue). In addition, all the container image builds rely on the variables defined at the top of the makefile, which you are expected to modify for your environment.  

Please follow the steps in the [development guide](https://github.com/googleforgames/open-match/blob/main/docs/development.md), and if you run into a  new problem, re-open this issue with the log of the failure.

Thanks!
