### ISSUE TITLE
Add Deployment Health Check for CI

### ISSUE THREAD

**Issue by jeremyje** [googleforgames/open-match#169]
CI for Open Match is currently limited to building and unit testing. It does not verify the correctness of the Helm charts are install/yaml files. We should add a build step that deploys Open Match to a Kubernetes cluster and verifies the healthiness of the cluster.

**Comment by yfei1** [comment]
I can take this. Any specific tools or resources I should look into?

**Comment by sawagh** [comment]
I am

**Comment by jeremyje** [comment]
This was pretty much done by 
https://github.com/googleforgames/open-match/pull/537
https://github.com/googleforgames/open-match/pull/536
