### ISSUE TITLE
Helm Install From Docs not working correctly

### ISSUE THREAD

**Issue by enderv** [googleforgames/open-match#1775]
**What happened**:
Was attempting to just do a base install to experiment and try out open match and using the commands in the docs under https://open-match.dev/site/docs/installation/helm/#install-open-match-using-a-specific-version -

```
# View available Open Match helm chart versions
helm search repo --versions open-match/open-match
# Install a specific Open Match helm chart version
helm install open-match --create-namespace --namespace open-match open-match/open-match --version=CHART_VERSION
```

Only the redis pod came up the rest were stuck in `ContainerCreating` with the status

```
MountVolume.SetUp failed for volume "om-config-volume-override"  ││ : configmap "open-match-configmap-override" not found
```

**What you expected to happen**:
The install command to work and bring up the full stack in kubernetes with no issues.

**How to reproduce it (as minimally and precisely as possible)**:
Follow the commands pasted above.

**Anything else we need to know?**:
Looks like the override configmap is optional but to create but always injected. Unsure if the right route would be to fix the docs to include the option or fix the helm chart 

**Output of `kubectl version`**:
```
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.2
```
**Cloud Provider/Platform (AKS, GKE, Minikube etc.)**: 
 N/A just installed in local docker cluster
**Open Match Release Version**: 
1.8.1
**Install Method(yaml/helm)**:
helm

**Comment by joeholley** [comment]
It's not well explained, but that section just highlights the command line flags required to specify the helm chart version when installing. The installation **requires** that you specify an evaluator component and config overrides, even if you want to just try out the [default ones we provide as samples for you to customize](https://open-match.dev/site/docs/installation/helm/#install-open-match-with-the-default-evaluator), which is explained further down in the installation instructions.
