### ISSUE TITLE
Make's OPEN_MATCH_DEMO_KUBERNETES_NAMESPACE doesn't work properly.

### ISSUE THREAD

**Issue by Laremere** [googleforgames/open-match#214]
It's not actually used by the make target "install-example-chart".  When I fix that, and then try setting it to something different than the OPEN_MATCH_KUBERNETES_NAMESPACE, the pods never start.  I think it's because the example assumes that the openmatch configmap will be in the same namespace.

Either the example templates need to properly reference the configmap's namespace, or the make variable should be removed.

**Comment by jeremyje** [comment]
Different namespaces for everything has not been tested yet. Though the variable was broken out early to begin that.
