### ISSUE TITLE
Make CI Faster

### ISSUE THREAD

**Issue by jeremyje** [googleforgames/open-match#231]
The continuous integration is taking a long time. It improve the build times there's a few things we can do.
Currently the build takes 15 minutes to complete.

* Add Kaniko cache. Currently: 2 min 36 sec
* Remove build steps that are unnecessary.
 * Binaries: Currently: 4 min 21 sec

Data points taken from, https://pantheon.corp.google.com/cloud-build/builds/01998d5b-ad3e-429b-8549-fc213529ca62?project=open-match-build

**Comment by yfei1** [comment]
The current docker build steps run too slow (up to 6min 51 sec) since it attempts to send all context under the root directory (~50MB) for each build step. We should specify the context needed for each image build to avoid wasting time on transferring unused data.

**Comment by yfei1** [comment]
Reopen this issue to track and benchmark CI time. Current CI time varies and takes around 15-19min to finish.

**Comment by yfei1** [comment]
#701 Removes the Create Cluster step from cloudbuild. This could saves about 3-5min build time

**Comment by yfei1** [comment]
Close this for now by a series of PRs.
Improved the CI build time from [19.5 min ](https://pantheon.corp.google.com/cloud-build/builds/8860a285-0761-4116-8f6b-3f933df0ce86?project=open-match-build) to [14.5 min](https://pantheon.corp.google.com/cloud-build/builds/3dbaf065-c8f4-4630-a4ae-b6cdffefc5d3?project=open-match-build).
