### ISSUE TITLE
Automate the Release Process

### ISSUE THREAD

**Issue by jeremyje** [googleforgames/open-match#250]
The release process is currently pretty painful as Open Match has many build artifacts and there's many manual changes required to get it out the door.

Here's a working list of enhancements for Open Match:
 * Use https://goreleaser.com/ci/ to automate creating the Github release and auto generating the release notes.
 * Create a new CI target for creating release artifacts {binaries, docker images, YAML files}.

At this point I don't expect these changes to land until 0.7.0 because there's a lot of things that need to fall into place before then.

**Comment by jeremyje** [comment]
https://github.com/GoogleCloudPlatform/open-match/issues/228 will be impacted.

**Comment by yfei1** [comment]
Will look into this issue in v0.8 after finishing the prioritized items

**Comment by yfei1** [comment]
This issue is too generic, closing it and will open a new issue with detailed execution plan to track this.
