### ISSUE TITLE
Proposal: Replace Viper for configuration.

### ISSUE THREAD

**Issue by jeremyje** [googleforgames/open-match#304]
Viper is not thread-safe and is plagued with issues when you couple that WatchConfig. There's 2 approaches here:

 * Fix viper to make it thread-safe for our purposes, my attempt which is not happy at the moment https://github.com/spf13/viper/pull/693.
 * Move to another configuration library.

I'd prefer to keep Viper in since it's already used throughout the codebase but fortunately has been mostly abstracted away. The concern with fixing Viper at this point is how long it will to get it checked in since that project has a lot of PRs outstanding, ~100.

**Comment by thisisnotapril** [comment]
Closing; not being used ATM
