### ISSUE TITLE
Wild card indexing in matchmaker config

### ISSUE THREAD

**Issue by psyonix-ish** [googleforgames/open-match#309]
In the matchmaker config, I would like to be able to use wildcards for `playerIndicies` to enable new indices without having to reapply the config.
e.g. 
```
playerIndices:
- region.*
```
allows additions of new regions without having to reapply the config.

**Comment by sawagh** [comment]
Specifying, processing indexes will take some revamp, added functionality in v0.7 with additional data type support, sophisticated filtering. This will be handled as a part of that.

**Comment by sawagh** [comment]
@Laremere - I think this can again be closed with context from: https://github.com/googleforgames/open-match/issues/765

**Comment by Laremere** [comment]
After the changes in https://github.com/googleforgames/open-match/issues/765, all fields within SearchFields are indexed, so this is now no longer a concern.
