### ISSUE TITLE
PersistentVolumeClaim "open-match-grafana" is invalid: spec

### ISSUE THREAD

**Issue by brasser** [googleforgames/open-match#333]
Release 0.5.0-rc.1

When running 
kubectl apply -f https://github.com/GoogleCloudPlatform/open-match/releases/download/0.5.0-rc.1/install.yaml --namespace open-match

Error, 

The PersistentVolumeClaim "open-match-grafana" is invalid: spec: Forbidden: is immutable after creation except resources.requests for bound claims

**Comment by afeddersen** [comment]
Thanks for opening the issue.  Can you provide your kubectl version?

$ kubectl version

**Comment by brasser** [comment]
kubectl version
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.9-dispatcher", GitCommit:"e3f5193e8f1091a162af7e17a781e6a3129bcfd0", GitTreeState:"clean", BuildDate:"2019-03-28T18:13:4
6Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-gke.6", GitCommit:"394ee507d00f15a63cef577a14026096c310698e", GitTreeState:"clean", BuildDate:"2019-03-30T19:31:43Z", 
GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by yfei1** [comment]
Hi brasser,

Thanks for using open-match!

Are you running open-match in GKE? It seems like there is a problem with GKE when you try to apply different yaml settings more than once. Could you possibly try to delete everything in the open-match namespace and try to redeploy again? This should resolve this issue.

**Comment by afeddersen** [comment]
kubectl is currently on 1.14 and they only support 3 minor versions (i.e. 1.14, 1.13, 1.12).  Would you mind upgrading to see if that addresses your issue?  I actually saw this and upgrading the client resolved it for me.

**Comment by sawagh** [comment]
Closing for now since this does not repro with the latest kubectl version.
