### ISSUE TITLE
Rename the API and server binaries for 0.6.0

### ISSUE THREAD

**Issue by jeremyje** [googleforgames/open-match#337]
Open Match currently has the following binary names:
 * frontendapi
 * backendapi
 * mmlogicapi
 * mmforc

With the new services coming online there's an opportunity to update the server names to something more meaningful.

 * frontendapi > frontend
 * backendapi > workflow
 * mmlogicapi > datastore
 * mmforc > synchronizer

I'm adding terrible names on purpose because I don't really know the best solution here.

**Comment by sawagh** [comment]
See comments in https://github.com/googleforgames/open-match/issues/337

**Comment by sawagh** [comment]
v0.6 drops the 'api' part for the services - and the mmforc is gone and new evaluator will be called synchronizer. Debated other proposals in TSC but failed to get better suggestions.
