### ISSUE TITLE
Update proto definitions to follow API design guide

### ISSUE THREAD

**Issue by yfei1** [googleforgames/open-match#380]
Our current proto service definitions has a few [custom methods](https://cloud.google.com/apis/design/custom_methods). It is a good practice to refactor these methods to use [standard methods](https://cloud.google.com/apis/design/standard_methods) to reduce complexity and increase consistency.

**Comment by sawagh** [comment]
We did some brainstorming and have some suggestions. However, it might be best to stick to the API surface we have for v0.6 and revisit this after feedback from v0.6 users. The primary suggestions were:

For Assignments: 

Getting stream of changing assignments - 
Current: 	GET: 	"/v1/frontend/tickets/{ticket_id}/assignments"
Proposed: POST: 	"/v1/frontend/tickets/{ticket_id}:watch"

Updating Assignments:
Current: 	     POST: "/v1/backend/tickets:assign"
Proposed:      PATCH: "/v1/backend/tickets:assign"

For Fetching Matches:

(Note OM does not itself store any Match resource any more so there is no create / update / delete of a match - only the custom verb currently)

Current:      POST: 	"/v1/backend/matches:fetch"
Proposed: POST: "/v1/backend/tickets:getmatches"  (or fetchmatches)

**Comment by sawagh** [comment]
No further changes targeted for v0.6 unless we get critical customer feedback - moving this to v0.7

**Comment by sawagh** [comment]
Further changes here only if we get specific feedback. Closing explicit issue tracking this since there is no current action item here.
