### ISSUE TITLE
Proposal: Move logs level from debug to trace

### ISSUE THREAD

**Issue by yfei1** [googleforgames/open-match#389]
open-match v.5 exposes too detailed logs which makes logs flood even when running test cases #167. Most of the logs are not necessary under most circumstances since current monitoring tools emit metrics/grpc call trace to user calls. However, it would be nice if we could add some trace logs to functions with complicated logic or over 100 lines for debugging purpose.

**Comment by sawagh** [comment]
We currently use too many log levels. Check if .Trace is really needed and if not, consolidate into .Debug

**Comment by sawagh** [comment]
OK with current logging levels - will revisit in v0.7 to fine tune.

**Comment by sawagh** [comment]
We only sparingly use trace - default disabled - and trace turned out pretty useful to debug in a customer usecase when trying openmatch first time - letting trace logs stay.
