### ISSUE TITLE
CI should fail if running presubmit changes files

### ISSUE THREAD

**Issue by Laremere** [googleforgames/open-match#491]
Basically, go.mod and the proto generated files can experience version skew because the CI doesn't detect if the files need to be updated.  It should block submit.  Otherwise running presubmit before committing a different change will result in unrelated files being changed.

**Comment by jeremyje** [comment]
If you're worried about go.mod then use `GOPROXY=off` It's already used in CI for building the binaries.

**Comment by thisisnotapril** [comment]
Closed due to inactivity
