### ISSUE TITLE
Improve current test infrastructure code

### ISSUE THREAD

**Issue by yfei1** [googleforgames/open-match#492]
This issue tracks the progress we made to improve open-match's test infra code. The ideal test infra code should satisfy the following criteria.

1. Be able to manage the test resource (e.g. the process closers) without adding them manually through the callback function.
2. Be able to test the service under TLS mode. This is possible once we have the prow server setup. We can generate pub/pri key pair files for testing in the prow server.
3. Separate the config and bind step. Current test infra code do the bind and config in one callback function, which may result in possible bugs from ordering problems.

**Comment by jeremyje** [comment]
Ping. Is this done?
