### ISSUE TITLE
Documentation for Open Match v0.6

### ISSUE THREAD

**Issue by sawagh** [googleforgames/open-match#506]
Open Match v0.6 should ship with the following documentation:

1. Developer documentation 
      - How to build Open Match (OSX, Linux)
      - Run Tests
      - CI checks and processes

2. Demo documentation - How to set up a E2E demo

3. Customer documentation - How to write your MMFs, test them with Open Match

4. Overview and concepts of Open Match.

**Comment by sawagh** [comment]
https://github.com/googleforgames/open-match/issues/284

**Comment by sawagh** [comment]
See more details from: https://github.com/googleforgames/open-match/issues/168

**Comment by jeremyje** [comment]
I think this issue can be moved to open-match-docs. And this one be closed.

**Comment by Laremere** [comment]
sawagh and I were just discussing, there's a little doc cleanup in this repo, so work for v0.6.0 is not quite done.

**Comment by sawagh** [comment]
submitted PR for dev documentation update.
