### ISSUE TITLE
Demo for Open Match v0.6

### ISSUE THREAD

**Issue by sawagh** [googleforgames/open-match#509]
Issue tracks any changes for making an E2E demo for Open Match. This includes implementation and documentation of the demo steps.

**Comment by jeremyje** [comment]
@Laremere Is this done?

**Comment by Laremere** [comment]
Documentation isn't quite done.

**Comment by jeremyje** [comment]
Since that's in a different repository there should be an issue in open-match-docs and this issue should be closed.
