### ISSUE TITLE
Stack Driver Metrics Export rate is too high.

### ISSUE THREAD

**Issue by jeremyje** [googleforgames/open-match#569]
2019/06/21 19:29:52 Failed to export to Stackdriver: rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: One or more points were written more frequently than the maximum sampling period configured for the metric. {Metric: custom.googleapis.com/opencensus/grpc.io/client/completed_rpcs, Timestamps: {Youngest Existing: '2019/06/21-12:29:46.439', New: '2019/06/21-12:29:51.439'}}: timeSeries[6-10]; One or more points were written more frequently than the maximum sampling period configured for the metric. {Metric: custom.googleapis.com/opencensus/grpc.io/client/received_bytes_per_rpc, Timestamps: {Youngest Existing: '2019/06/21-12:29:46.439', New: '2019/06/21-12:29:51.439'}}: timeSeries[11-13]; One or more points were written more frequently than the maximum sampling period configured for the metric. {Metric: custom.googleapis.com/opencensus/grpc.io/client/received_messages_per_rpc, Timestamps: {Youngest Existing: '2019/06/21-12:29:46.439', New: '2019/06/21-12:29:51.439'}}: timeSeries[14-16]; One or more points were written more frequently than the maximum sampling period configured for the metric. {Metric: custom.googleapis.com/opencensus/grpc.io/client/roundtrip_latency, Timestamps: {Youngest Existing: '2019/06/21-12:29:46.439', New: '2019/06/21-12:29:51.439'}}: timeSeries[17-19]; One or more points were written more frequently than the maximum sampling period configured for the metric. {Metric: custom.googleapis.com/opencensus/grpc.io/client/sent_bytes_per_rpc, Timestamps: {Youngest Existing: '2019/06/21-12:29:46.439', New: '2019/06/21-12:29:51.439'}}: timeSeries[0-2]; One or more points were written more frequently than the maximum sampling period configured for the metric. {Metric: custom.googleapis.com/opencensus/grpc.io/client/sent_messages_per_rpc, Timestamps: {Youngest Existing: '2019/06/21-12:29:46.439', New: '2019/06/21-12:29:51.439'}}: timeSeries[3-5]"

**Comment by yfei1** [comment]
Investigated this issue a bit. Found the sentence below from [Creating custom metrics in GCP](https://cloud.google.com/monitoring/custom-metrics/creating-metrics)
> If you want to write more than one point to the same time series, then use a separate call to the timeSeries.create method for each point. Don't make the calls faster than one time per minute. If you are adding data points to different time series, then there is no rate limitation.

This seems like a bug result from the `.Values.global.telemetry.reportingPeriod` parameter that we set.

**Comment by jeremyje** [comment]
Fixed by https://github.com/googleforgames/open-match/pull/695
