### ISSUE TITLE
Add C# Solo Duel Example MFF

### ISSUE THREAD

**Issue by jeremyje** [googleforgames/open-match#617]
We need to prove that MFFs can be written in any language other than Golang. To do this we'll port solo duel to C#.

There's an immediate blocker via https://github.com/googleforgames/open-match/issues/616 which prevents MMFs from working because the database needs to be queried.

**Comment by sawagh** [comment]
Out of Open Match core scope. We need a lot more documentation, libraries, guides / samples for C# - not in scope for v1.0

**Comment by dzmitry-lahoda** [comment]
is it still not prio?
