### ISSUE TITLE
Simplify Configuration

### ISSUE THREAD

**Issue by jeremyje** [googleforgames/open-match#623]
The configuration is pretty large. There's a few TODOs related to it as well.

We should fix them:
* Unify pullPolicy for images.
* Add relevant timeouts to RPC calls.
* Use constants for configuration aliases.
* Stop using environment variables for Redis connection.

**Comment by yfei1** [comment]
Aiming to close this issue next week. Also found something that might be useful in helm3
https://github.com/helm/community/blob/master/helm-v3/001-charts.md#library-charts
