### ISSUE TITLE
Generated Swagger for struct fields is incorrect.

### ISSUE THREAD

**Issue by Laremere** [googleforgames/open-match#636]
The properties fields of type gooogle.protbuf.Struct in the json/rest api actually takes any json object.  The swagger says that it should be in the Struct's direct proto translation.  This is a bug with https://github.com/grpc-ecosystem/grpc-gateway

I spent some time trying to figure out a fix, and it seems grpc-gateway/protoc-gen-swagger/template.go needs to have struct added as a well known type.  The difficulty is that I can't find a way to express "any json object" in swagger.

**Comment by jeremyje** [comment]
Should this be a bug in github.com/grpc-ecosystem/grpc-gateway?

**Comment by Laremere** [comment]
I was following their contributor guidelines which asked I raise the issue in slack first.  They've agreed it's a real issue, so I will be posting there now.

**Comment by yfei1** [comment]
This bug is fixed in https://github.com/grpc-ecosystem/grpc-gateway/pull/990 but their latest release doesn't include this change yet. Will do a version upgrade to our `go.mod` file once they have a new release.
