### ISSUE TITLE
Methods of frontendapi and backendapi not implemented

### ISSUE THREAD

**Issue by h0mjam** [googleforgames/open-match#641]
Setup k8s cluster and up match-making, try call methods but I get back `rpc error: code = Unimplemented desc = unknown method CreateTicket for service api.Frontend`.

clientloadgen & backendclient from examples fine work onto cluster. But they call methods other than those generated by protobuf.

Images:
gcr.io/open-match-public-images/openmatch-backendapi:0.5.0
gcr.io/open-match-public-images/openmatch-backendclient:0.5.0

gcr.io/open-match-public-images/openmatch-frontendapi:0.5.0
gcr.io/open-match-public-images/openmatch-clientloadgen

Our code:
```golang
client := newClient(*serverAddr)

r := &pb.CreateTicketRequest{
	Ticket: &pb.Ticket{
		Properties: structs.Struct{
			"name":      structs.String("Victor"),
			"mode.demo": structs.Number(1),
		}.S(),
	},
}

resp, err := client.CreateTicket(context.Background(), r)

if err != nil {
	fmt.Printf("error create a ticket: %v\n", err)
	return
}

// error create a ticket: rpc error: code = Unimplemented desc = unknown method CreateTicket for service api.Frontend
```

**Comment by jeremyje** [comment]
Thanks for the report. To get you unstuck you may want to look at 0.6.0-preview1 at this point. We are close to releasing 0.6.0 which has a different API.

https://groups.google.com/forum/#!topic/open-match-discuss/ZMYNP0Log0I

https://development.open-match.dev/site/blog/2019/06/28/0.6.0-preview/

**Comment by Laremere** [comment]
Yeah, it looks like you're running 0.5 images, but using the 0.6 api.

**Comment by h0mjam** [comment]
Really, cluster will up with images 0.5, but use protobuf specs from master.
