### ISSUE TITLE
Jaeger does not deploy in 0.6.0 install.yaml

### ISSUE THREAD

**Issue by jeremyje** [googleforgames/open-match#672]
a container name must be specified for pod open-match-jaeger-query-578cc99b4d-qtxgt, choose one of: [open-match-jaeger-query open-match-jaeger-agent-sidecar]
jager collector fails for: dns error: lookup open-match-cassandra on 10.24.0.10:53: no such host

**Comment by yfei1** [comment]
Mark as closed. Tested Open Match deployment with Jaeger in three runs and it seems like everything spinned up correctly.
