### ISSUE TITLE
Go get does not work for open-match.dev/open-match

### ISSUE THREAD

**Issue by djsell** [googleforgames/open-match#675]
I tried to use go get to use the pb package to make a director that works with agones.  I ran into a couple issues.

1) Go get does not work for open-match.dev/open-match

```
$ go get -v open-match.dev/open-match
Fetching https://open-match.dev/open-match?go-get=1
Parsing meta tags from https://open-match.dev/open-match?go-get=1 (status code 200)
get "open-match.dev/open-match": found meta tag get.metaImport{Prefix:"open-match.dev/open-match", VCS:"git", RepoRoot:"https://github.com/googleforgames/open-match.git"} at https://open-match.dev/open-match?go-get=1
go: open-match.dev/open-match@v0.5.1: parsing go.mod: unexpected module path "github.com/GoogleCloudPlatform/open-match"
go: error loading module requirements
```

So I went ahead and got go get to work by using GoogleCloudPlatform/open-match
```
$ go get -v github.com/GoogleCloudPlatform/open-match
go: finding github.com/GoogleCloudPlatform/open-match v0.5.1
go: downloading github.com/GoogleCloudPlatform/open-match v0.5.1
go: extracting github.com/GoogleCloudPlatform/open-match v0.5.1
github.com/GoogleCloudPlatform/open-match
```

2)  There seems to be some problem when trying to use the agones API and open-match API in the same project.  I was seemingly having problems with kubernetes client version dependencies once I had both included in a single project using go modules.

```
$ go run main.go director
go: finding k8s.io/api/admissionregistration/v1alpha1 latest
go: finding k8s.io/api/admissionregistration latest
go: finding k8s.io/api latest
build command-line-arguments: cannot load k8s.io/api/admissionregistration/v1alpha1: cannot find module providing package k8s.io/api/admissionregistration/v1alpha1
```

Kubernetes api was working just fine when I had only agones integrated.

**Comment by Laremere** [comment]
Thanks for trying open match and reporting this issue.

I was able to repo the first issue.  It looks like we never updated the url for the 0.5, though that seems fine (imo) as the old go get does work.

We're in the process of releasing 0.6.0, which (among other things) has a reworked API.  So I recommend running instead:
```
go get -v open-match.dev/open-match@v0.6.0-rc.1
```

If you use this version, does it fix your other problem?  Otherwise please include a concrete list of steps that I can run in an empty folder for reproduction.  Given that I don't have contents of your directory, it would take random guessing to reproduce your issue.

Thanks!

**Comment by Laremere** [comment]
Also I should note that once we release v0.6.0, that will fix the go get problem without needing to tag the version.  It's only that go get by default picks that latest version but ignores release candidates.

**Comment by djsell** [comment]
Using `go get -v open-match.dev/open-match@v0.6.0-rc.1` fixed both issues!

Thanks for the fast response.

**Comment by Laremere** [comment]
Jeremy wanted to look at this to see if we can improve the user experience while we are in the 0.6 rc process.

**Comment by jeremyje** [comment]
This looks like fallout from the transition to googleforgames org. You might have to delete your `rm -rf $GOPATH/pkg` (make sure that `$GOPATH` is actually set otherwise you'll delete `/pkg`!) directory and rebuild as the proper workaround here.
