### ISSUE TITLE
Benchmark Open Match characteristics for several high scale usage scenarios

### ISSUE THREAD

**Issue by sawagh** [googleforgames/open-match#678]
1. Identify real world high scale scenarios.
2. Apply these to an Open Match deployment
3. Benchmark Open Match performance characteristics
4. Identify any bottlenecks, performance enhancements

Examples of some of the input parameters to vary are: Incoming Ticket rate, Index counts, Pools per match / Pending Ticket Pool size / Ticket assignment rate

**Comment by Unimax** [comment]
Just wanted to inform when the demo was scaled with more than 1000 players, tested with 10000, 5000 and 1000 with increased sleep timing (last step in the demo) the front-end and back-end both starts to fail.

**Comment by sawagh** [comment]
Thanks a bunch for trying to scale the demo and for the information Sunil. I am trying out some scale benchmarking and have found some bugs (and some patterns) that prevent OM from currently scaling. I will target some of those for v0.7 (will create separate issues in a few days once I m done and have concrete evidence). 

Do feel free to create issues, or add any other scale observations to this issue itself. Appreciate the effort!

**Comment by yfei1** [comment]
I'll close this for v0.9 since we have addressed most of the concerns in the original issues. Will publish all the numbers in v.10.
