### ISSUE TITLE
Split Open Match configuration into infrastructure v/s application configuration

### ISSUE THREAD

**Issue by sawagh** [googleforgames/open-match#680]
Currently, All of Open Match configuration is bundled together and is stored in a config file accessed using Viper. We should consider splitting out the application configuration from the infrastructure configuration. Potentially consider enabling API access to set / update Application configuration?

**Comment by sawagh** [comment]
Moving this to v0.8 since we do not clearly understand the requirements here.

**Comment by Laremere** [comment]
Please move the evaluator and synchronizer configuration to the override (removing from defaults.)  Then provide an additional yaml which only include the override, removing the override from the core yaml.
