### ISSUE TITLE
demos projects using : The Great Ghoul Duel (Google Halloween 2018)  !!

### ISSUE THREAD

**Issue by DevJoseWeb** [googleforgames/open-match#718]
Where I find a project or how to do some tests using Unity, Google has an 8 player game using this technology.

The Great Ghoul Duel (Google Halloween 2018)  Source code !!

**Comment by Laremere** [comment]
There are no examples using unity at this time.  You can see instructions for a generic demo here: https://open-match.dev/site/docs/getting-started/first_match/ which you can use as a starting point for your project.

The Google doodle code is not open source.
