### ISSUE TITLE
Assignment.Error as a gRPC standard error?

### ISSUE THREAD

**Issue by calebatwd** [googleforgames/open-match#719]
The assignment.error field of the ticket assignment is a contract directly managed between the match function and the frontend contract consumer, both of which fall in the developer domain. While the gRPC error is useful and somewhat standard for services, is the Details `Any` field enough for developers to customize the contract?

As an alternative, we could consider following the same shape as Properties, which has similar function. Right now, I believe that is a protobuf.struct?

Just looking for a discussion.

**Comment by calebatwd** [comment]
ah... that's good documentation :)
message Assignment {
// An Assignment object represents the assignment associated with a Ticket. Open
// match does not require or inspect any fields on assignment.

Since it's not used by open match directly, these are usability fields that we've identified as common uses. It makes more sense now.

**Comment by sawagh** [comment]
As we update some of the data contract fields, might be nice to tie this together to changes in https://github.com/googleforgames/open-match/issues/765 (Do we care about connection string / user errors at all as first class components? or just assignment data in the Any?)

**Comment by Laremere** [comment]
OM has standardized on using Any fields for custom data.  The grpc error aligns with this, so we should keep it.
