### ISSUE TITLE
Should the proto package be open-match?

### ISSUE THREAD

**Issue by Laremere** [googleforgames/open-match#723]
Currently the proto package is "api", or "api.internal".  This means if another project includes anything (such as assignment) in it's protos, then it will need to reference it as "api.assignment", which feels off.  Shouldn't it be "openmatch.assignment"?  Why was the name api chosen in the first place?

**Comment by yfei1** [comment]
We are following the conventions at here https://github.com/golang-standards/project-layout/tree/master/api

**Comment by Laremere** [comment]
Yes, that's where the proto files are.  However I'm talking about the proto package (https://developers.google.com/protocol-buffers/docs/proto3#packages) declaration.
