### ISSUE TITLE
Fatal error reading config file global_config

### ISSUE THREAD

**Issue by Unimax** [googleforgames/open-match#730]
Hi, when i run 
`open-match.dev/open-match/cmd/demo-first-match$ go run main.go
`
it's giving me following error. (the same error is coming out of  pod if I create image using the given docker files and deploy on gkc)

time="2019-08-07T10:23:36Z" level=fatal msg="Fatal error reading config file" app=openmatch component=config error="Config File \"global_config\" Not Found in \"[/app /app/config/global]\""

![Screenshot from 2019-08-07 03-55-31](https://user-images.githubusercontent.com/4117562/62617700-4957bc00-b8c7-11e9-8a07-dd20b6152fc1.png)

i also wanted to tell that when i deploy current release 0.6.0 using cloud yaml file 2 pods are not working (but as they are not important we can leave this issue):-
![Screenshot from 2019-08-07 03-57-41](https://user-images.githubusercontent.com/4117562/62617827-a3588180-b8c7-11e9-98bc-4221c0af0ba0.png)

errors:-
![image](https://user-images.githubusercontent.com/4117562/62617889-c08d5000-b8c7-11e9-9c71-5dbfbc6b77c8.png)

**Comment by yfei1** [comment]
Hi, thanks for opening the issue!

> Hi, when i run
open-match.dev/open-match/cmd/demo-first-match$ go run main.go 
it's giving me following error. (the same error is coming out of pod if I create image using the given docker files and deploy on gkc)

It seems like you were running the demo code in our master branch. We have some configuration changes after v.6 and also the demo expects having Open Match running in the same cluster as itself. Could you possibly try to follow [the steps at our website](https://open-match.dev/site/docs/getting-started/first_match/) and see if it works?

> i also wanted to tell that when i deploy current release 0.6.0 using cloud yaml file 2 pods are not working (but as they are not important we can leave this issue):-

Open Match uses the official helm charts from prometheus and grafana. We have encountered the grafana-test error before and is working on investigate this issue in v.7.

For the prometheus server server error, since promethues requires some stand-up time, I believe the unschedulable error should be resolved if you give it enough time with enough cluster resource. It took me 1m25.474s to deploy everything (except the LoadBalancers) in a 2-node n1-standard-4 GKE cluster.

**Comment by Unimax** [comment]
> Hi @Unimax, thanks for opening the issue!
> 
> > Hi, when i run
> > open-match.dev/open-match/cmd/demo-first-match$ go run main.go
> > it's giving me following error. (the same error is coming out of pod if I create image using the given docker files and deploy on gkc)
> 
> It seems like you were running the demo code in our master branch. We have some configuration changes after v.6 and also the demo expects having Open Match running in the same cluster as itself. Could you possibly try to follow [the steps at our website](https://open-match.dev/site/docs/getting-started/first_match/) and see if it works?
> 
> > i also wanted to tell that when i deploy current release 0.6.0 using cloud yaml file 2 pods are not working (but as they are not important we can leave this issue):-
> 
> Open Match uses the official helm charts from prometheus and grafana. We have encountered the grafana-test error before and is working on investigate this issue in v.7.
> 
> For the prometheus server server error, since promethues requires some stand-up time, I believe the unschedulable error should be resolved if you give it enough time with enough cluster resource. It took me 1m25.474s to deploy everything (except the LoadBalancers) in a 2-node n1-standard-4 GKE cluster.

Thank you for quick reply,

yes, the standard demo from 0.6.0 does work. but I wanted to have 10 player deathmatch as MMF and about 100-1000 players with pings and MMR details. that's why i have edited the code and created the images. and yes i am deploying them on the same cluster.

so should i clone from the tag 0.6 and edit it from there? or how can i fix this global_config error?

**Comment by Laremere** [comment]
Ah, thanks for the details.
A couple important things:

- We don't have any compatibility guarantees yet.  That will come with 1.0, and there's going to be a few (hopefully small) changes for 0.7.  So if you're running the cluster with the 0.6 yamls, you'll want to edit the demo from the 0.6 tag.
- The demo reads a configuration file.  (To know how to connect to servers, etc.)  This file is typically provided through kubernetes config maps.

The best way to proceed is to modify the demo yaml files to use your images.
The install yaml files are linked from the release page: https://github.com/googleforgames/open-match/releases/tag/v0.6.0
and here is the install-demo.yaml
https://github.com/googleforgames/open-match/releases/download/v0.6.0/install-demo.yaml

You'll primarily need to change which images are used, see this line for the demo:
```
 image: "gcr.io/open-match-public-images/openmatch-demo:0.6.0"
```
Which specifies using the provided demo image.  If you build your own demo image, upload it to your container registry and change the url before applying that yaml.  This is also how you'd change the matchmaking function image.

Also in this yaml file you can see where the configuration files are mounted:
```
        volumeMounts:
        - name: om-config-volume
          mountPath: /app/config
```

There's also some makefile commands for doing these actions, but those are undocumented for the time being.

**Comment by Unimax** [comment]
@Laremere thanks again for the quick reply.
That is how I exactly did it, i.e. using 0.6 open-match YAML and editing the demo YAML with my images. Thanks for the confirmation that i am on the right path.
I don't understand what I have to do with the config file thing. I can see the path but I don't have anything or any custom config file.

Note: I haven't tried to build from 0.6 tag with my changes. if that works without any issue I probably will close this issue asap.
