### ISSUE TITLE
Investigate Streaming v.s. Unary RPCs in Open Match

### ISSUE THREAD

**Issue by yfei1** [googleforgames/open-match#731]
gRPC has a 4MB default size limit for each unary rpc call ([ref](https://discuss.dgraph.io/t/grpc-message-limit-for-a-single-transaction/1947)). This might lead to some bottlenecks since the synchronizor will hold off any incoming requests in its `proposalCollection` phase and result in large chunk of data being sent in one call when entering its `evaluation` phase. We should consider the following things before switching to streaming RPCs.

1. Investigate how does grcp-gateway plugin handle streaming in HTTP.
2. Calculate the size of the prototext in Open Match and estimate the potential bottleneck of using unary RPC calls.
3. Investigate how does timeout work in gRPC streaming. It seems like gRPC timeout is not for a single send or receive operation but for the entire stream ([ref](https://groups.google.com/forum/#!topic/grpc-io/cpPgMMRyDuc)). If that is the case, we might need to come up with a way to prevent having a single transaction taking too long to respond.

**Comment by yfei1** [comment]
> 1. Investigate how does grcp-gateway plugin handle streaming in HTTP.

It seems like grpc-gateway supports two-way streaming. Here is the example [proto](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/examples/proto/examplepb/stream.proto#L23) and [test](https://github.com/grpc-ecosystem/grpc-gateway/blob/21fa8c30c8ffd9511ebcfc4695f0d079e8aa53fa/examples/integration/integration_test.go#L956) to do it.

> 3. Investigate how does timeout work in gRPC streaming. It seems like gRPC timeout is not for a single send or receive operation but for the entire stream ([ref](https://groups.google.com/forum/#!topic/grpc-io/cpPgMMRyDuc)). If that is the case, we might need to come up with a way to prevent having a single transaction taking too long to respond.

According to the website it also supports `Setting gRPC timeouts through inbound HTTP "Grpc-Timeout" header`. We could potentially have users setting up grpc time out for their RPC calls.

**Comment by yfei1** [comment]
The APIs that need to be changed from unary into streaming are: 

- [ ] `backend.FetchMatches` @sawagh does the request need to be in stream? Do we support 
 use case having a fetch matches request with a large chunk (more than 4MB) of MatchProfiles?
```diff
-rpc FetchMatches(FetchMatchesRequest) returns (FetchMatchesResponse) {
+rpc FetchMatches(FetchMatchesRequest) returns (stream FetchMatchesResponse) {
```
- [ ] `evaluator.Evaluate` - This will be the bottleneck if the synchronizer is enabled and do the evaluation in batch.
```diff
-rpc Evaluate(EvaluateRequest) returns (EvaluateResponse) {
+rpc Evaluate(stream EvaluateRequest) returns (stream EvaluateResponse) {
```
- [ ] `matchfunction.Run` - This might be a bottleneck if we have too many proposals being returned in one call
```diff
-rpc Run(RunRequest) returns (RunResponse) {
+rpc Run(RunRequest) returns (stream RunResponse) {
```

**Comment by sawagh** [comment]
FetchMatchesRequest - We do not need to stream the request in. I think the requirement of profile(s) fitting under 4MB is fine - there is always an option to break into multiple FetchMatches calls if that does not suffice.

You may need streaming on the synchronizer too though:
rpc EvaluateProposals(stream EvaluateProposalsRequest) returns (stream EvaluateProposalsResponse)
