### ISSUE TITLE
MMFs on Knative

### ISSUE THREAD

**Issue by joeholley** [googleforgames/open-match#75]
In prep for the glorious serverless function futuretimes, we'd like to get a prototype working that runs MMFs as Knative functions instead of k8s jobs (as mentioned in the [roadmap](docs/roadmap.md)).  Plan is currently to get this in for 0.4.0 RC in late Feb 2019.

**Goals**:
- Stay as close to the simplicity of the current MMFs-as-jobs system as possible.  From the perspective of a user developing against OM we'd like to stay as close to 'write code | trigger build | push code | run code' as possible.  This may mean some extra scaffolding via gRPC harnesses.
- Attempt to make building/runtime harnesses for both knative and k8s job MMFs.  The goal will be to give a shared foundation such that the custom code we expect devs to write could easily be used in either way.  (This is related to the next point.)
- Establish a new way to pass in the environment variable values.  Env vars won't be a good way to communicate with serverless functions so we should see if we can unify both knative and k8s job MMFs to use a common way of passing in the critical state storage keys to read and write.  [The current prototype](https://github.com/GoogleCloudPlatform/open-match/compare/calebatwd/knative-rest-mmf) passes the env vars to a serverless function through a input argument, but this bifurcates the implementation to 'MMFs that read from input arguments' and 'MMFs that read from env vars'.  This can probably be handled using k8s job harnesses that put env vars into an input argument but it's open for discussion.

**Current implementation thoughts**:
- Everything else in OM uses gRPC and the latest knative serving release just added [limited gRPC support](https://github.com/knative/serving/pull/2539#issue-233293556).  We should see if we can build on this and avoid having to support multiple protocols for knative functions.
- For now we probably don't want to deal with knative functions hosted outside of the OM k8s cluster, so for the first pass we likely want all the knative services to be run as [cluster-local](https://github.com/knative/docs/blob/master/serving/cluster-local-route.md)
- The core contributors agree that we don't want to take on knative eventing at this time.  MMF results have a very small amount of  time before they become stale and if knative serving isn't ready to run a function, in most cases we would prefer to get a failure rather than queueing the request.  We can adjust which MMFs are being called on-the-fly to get better results this way. (This one probably merits more discussion)

**Things to evaluate**:
- We need to seriously evaluate knative build and see if it can be useful for MMFs.
- Are different MMFs different knative **services**? Different knative **revisions**? Do we make 'families' of MMFs that are different **services** with multiple members of the family as different **revisions**?
- Additional resource overhead of running the knative components in the cluster should be watched.
- Istio and Knative have opinions about metrics collection (Prometheus) and tracing (Jaeger).  We should check to see what if any changes need to be made to OM to fit with the systems they are using.  We definitely want to avoid a situation where someone using Knative MMFs has two prometheus instances running: one for knative and one for OM.

I'm sure we'll add to this as we go and lots more thoughts will come up once 0.4.0 RC comes out with an implementation we can all mess around with, so please add your comments as you encounter things we should consider.

**Comment by joeholley** [comment]
[https://github.com/ericbottard/knative-grpc](https://github.com/ericbottard/knative-grpc) for more context into current gRPC implementation limitations.

**Comment by joeholley** [comment]
This will require knative serving 0.4, which is coming out this week, so this won't fit in our timeline until 0.5.  We'll work on getting MMF serving in using standard k8s service+deployment resources, and then rework it for knative later.

**Comment by sawagh** [comment]
How the MMFs are run is out of scope for Open Match core. Post 1.0, we will focus on ecosystem efforts to simplify / recommend running components that Open Match interacts with. Closing this as it is out of scope of Open Match core.
