### ISSUE TITLE
Make helm support deployment with multi mmfs

### ISSUE THREAD

**Issue by yfei1** [googleforgames/open-match#757]

**Comment by yfei1** [comment]
This requires having one additional configmap per new MMFs which is cumbersome. MMFs need to read their `grpcport`/`httpport` from the config unless we specify a well known unified ports for these MMFs.

**Comment by Laremere** [comment]
I'm going to close this.  The recommendation is that you just deploy it like you would any other k8s deployment.  There is no need to use the customize chart, so there's no limiting to just one mmf.
