### ISSUE TITLE
Add metadata field to ticket

### ISSUE THREAD

**Issue by yfei1** [googleforgames/open-match#758]
The metadata field can provide `createTimestamp`/`lastUpdateTimestamp`/other ticket information that might be useful for the upcoming Open Match stat server. This change also enable Open Match users to write MMFs that take wait time into account.

**Comment by yfei1** [comment]
The current plan is to add a `metadata` field to our Ticket proto. This field is able to reflect the latest changes to the ticket whenever some fields get updated and is read only for Open Match users.
 
```proto
message Ticket {
   ...
   google.protobuf.Struct metadata = 4;
   ...
}
```

**Comment by Laremere** [comment]
Do we need a metadata field?
I have concerns:
- This makes referencing "metadata" fields separate from other fields.  How does this interact with filters.
- I think tickets are tending towards being immutable.  So the only relevant field would be creation time.

If we do need a metadata field, then it shouldn't be a struct because we'll know what fields are present.

**Comment by yfei1** [comment]
> * This makes referencing "metadata" fields separate from other fields.  How does this interact with filters.

My current implementation treats fields in the metadata field as read-only so that users can query them with the filters. I have a draft implementation at [here](https://github.com/googleforgames/open-match/pull/760). I agree we need more thoughts at here since not every meta-index is sort-able.

> * I think tickets are tending towards being immutable.  So the only relevant field would be creation time.

For now the metadata type only supports creationTimestamp, but I think having a separate structure for the ticket could preserve some flexibility for things like `lastModifiedTimestamp`/`contentMD5`/`ticketDeindexedTimestamp`/`multitenencyId` etc 

> If we do need a metadata field, then it shouldn't be a struct because we'll know what fields are present.

I was thinking about using `protobuf.struct` for backward compatibility since we'll be adding more fields to the metadata structure.

**Comment by sawagh** [comment]
I am not sure if this is really needed. Something we started discussing as earlier versions of OM used to support this - but I ve not heard any users complain about this with it being missing in the last 3 releases.
