### ISSUE TITLE
Synchronizer should return when all registered MMFs have submitted proposals

### ISSUE THREAD

**Issue by sawagh** [googleforgames/open-match#762]
Currently, the synchronizer waits for the entire configured time duration before it triggers evaluation. This is not great - lots of wasted dead time. Synchronizer should be able to have a quick return if all the 'registered' calls have submitted proposals - and we are done with the registration window.

**Comment by yfei1** [comment]
Closed as this no longer applies given we are moving to the new synchronizer.
