### ISSUE TITLE
Provide ability to delete all the tickets in Open Match

### ISSUE THREAD

**Issue by sawagh** [googleforgames/open-match#764]
This came up when Psyonix was analyzing some of the failure conditions. Given that Open Match expects tickets to players mapping to be maintained outside of Open Match, it is totally possible that the entity retaining this information loses it (crash?). At this point, say the game lost all information about what Tickets are present in Open Match. This would then have two side effects:
- These leaked tickets would continue to be matched
- There would be no good way to delete this state

Plenty of options:
1. Open Match Provides DeleteAllTickets() <-- Self Explanatory
2. Open Match Provides GetAllTickets() <-- returns all ticket IDs

(2) Provides some information that only Open Match knows and knowing that information may be useful in other scenarios. (1) could be built on top of (2) externally. So in the original problem, when starting up, if the game service (frontend / director) wants to get openmatch to a clean state - GetAllTickets --> followed by delete each could help.

DeleteAllTickets as a functionality may save the user the pain of getting and looping delete - my concern would be conveying the guarantees we provide when this happens - do we prevent any other activity to happen when this is in progress? Is it transnational? I prefer providing a basic GetAllTickets functionality and have the user build scenarios such as delete all using that.

**Comment by rib** [comment]
A convenient way to delete all tickets would be handy during development. I've just ended up in a sitation where I've put a ticket into the system that triggers an error in my director (the ticket has an Any Extension with a type_url that Go doesn't like) and now that I've fixed the issue in my frontend it'd be good to clean out all old tickets.

It's also caught me out when updating my frontend/director that I sometimes have left-over tickets that then interfere with testing.

**Comment by rib** [comment]
I ended up with this sledgehammer as a workaround for now:

```go
func deleteAllTickets() error {
	log.Println("Deleting all pre-existing tickets")

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	mmlogicAddr := "om-mmlogic.open-match.svc.cluster.local:50503"
	conn, err := grpc.Dial(mmlogicAddr, grpc.WithInsecure())
	if err != nil {
		log.Fatalf("Failed to connect to Matchmaker Logic, got %v", err)
	}
	defer conn.Close()

	mml := pb.NewMmLogicClient(conn)

	frontendAddr := "om-frontend.open-match.svc.cluster.local:50504"
	conn, err = grpc.Dial(frontendAddr, grpc.WithInsecure())
	if err != nil {
		log.Fatalf("Failed to connect to Matchmaker Logic, got %v", err)
	}
	defer conn.Close()

	frontend := pb.NewFrontendClient(conn)

	everythingPool := pb.Pool{}
	req := pb.QueryTicketsRequest{
		Pool: &everythingPool,
	}
	stream, err := mml.QueryTickets(ctx, &req)
	if err != nil {
		return fmt.Errorf("Failed to query tickets: %w", err)
	}

	for {
		resp, err := stream.Recv()
		if err == io.EOF {
			break
		}
		if err != nil {
			return fmt.Errorf("error streaming response from mml.QueryTickets call: %w", err)
		}

		for _, ticket := range resp.Tickets {
			req := pb.DeleteTicketRequest{
				TicketId: ticket.GetId(),
			}
			log.Printf("> Deleting ticket %s", req.TicketId)
			ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
			defer cancel()
			_, err := frontend.DeleteTicket(ctx, &req)
			if err != nil {
				log.Printf("Failed to delete ticket %s: %v", req.TicketId, err)
			}
		}
	}

	return nil
}
```

**Comment by sawagh** [comment]
Propose moving to v0.10 - Definitely a fix to consider, not a blocker for adoption.

**Comment by Laremere** [comment]
Moved to 1.0  Robert's "workaround" does the job.  What we want here is probably a general OM tool which has a delete all option (with lots of warnings and safeguards).  Not a specific API endpoint.

**Comment by sawagh** [comment]
Wont https://github.com/googleforgames/open-match/issues/766 give the primitives to do this efficiently? If yes - I can close this issue as #766 is prioritized for v0.10

**Comment by yfei1** [comment]
Reopened for v1.0
