### ISSUE TITLE
API change: Document-style structure to compositional contracts

### ISSUE THREAD

**Issue by calebatwd** [googleforgames/open-match#765]
## Overview
Currently, open match apis rely heavily on loosely-structured `struct` (json-style) contracts, similar to a document database. The implication is that open match will, in some way shape or form, care about some _or all_ of the paths and types of the underlying data stored in the ticket documents (today, that's string value, number value, null value, and boolean value). We do this for custom ticket indexing... Spoken: here's my ticket document, the current indexes are "player.[0].skill" and "party.modeSelection". In this way, open match can use custom indexing policies to read and interpret the tickets schema and built-in types and build indexes without needing to infer the type or search for it in the document.

Pros:
1. The built-in types are easily supported without additional work (they can be inferred, which enables wildcard indexing /*)
2. Follows existing document model index policy styles (less invention).
3. Less duplication of data if the developer commits to using the data format in their match function

Cons:
1. Requires the developer use struct in their match functions... any binary data formats (commonly used in games) needs to be serialized into a string, and deserialized from a string back during match function execution. Struct doesn't support *any*, so we're stuck with Base91 (possibly 128) string encoding. 
2. While the types (number, string, boolean, and null) are initially sufficient types for indexing, any additional types (like vector) would require a type field be introduced to any structuring, or the custom index policy would need to map paths to type. (I also think this will be necessary anyways... imagine: "attributes.spacialSkill": "vector". See config proposal coming...)
3. If the developer chooses another format, they have to duplicate data anyways

## Proposal
Adopt a `multipart/form-data`-style api, where there's both a document, and a blob
- Rename `Properties` to `Attributes`... arguably, this is pedantic, but I kinda think about them in reverse of what we currently have. Open to feedback on that.
- Add a `Properties` as an `Any` that the developer can use to bypass open match serialization for their match function. (Any is better than byte[] in this case because the type field can be used to describe the contract and version the developer needs to interpret during match function execution)
```
google.protobuf.Any properties  // An indexable document provided by the game client
google.protobuf.Struct attributes // Whatever data the developer wants to deserialize in their match function, which open match doesn't care about. This can be put into the database hash as is, which is convenient.
```

Pros:
1. Still get the benefits of `struct` for document style indexing policies
2. I think these are a bit more common sense to use (attributes are things for open match to index, properties are mine to use in match functions (my "developer" contract))
3. Reduce serialization and smaller format on the wire if the developer wants (no in and out of string with binary data)

Cons:
1. The developer may need to duplicate data from their formatted data into the attribute fields.
2. The developer now has multiple options for passing data which requires additional education and instruction

## Other Areas
We should also look at how `struct` is used in the `Match` object that the match function has to populate. Arguably, anything that open match doesn't care about, can be `Any`... which could be most of that contract.

## Impact
MMFs and frontend clients would need to move off of struct and to their own serialization method.
The rest-proxies may not fully support `Any` very easily. Need help investigating.

## Change Proto
```
// Assignment to be associated with this Ticket.
message Ticket {
  // The Ticket ID generated by Open Match.
  string id = 1;

  // Attributes contains custom info about the ticket. Any fields in attributes can be indexed by open match
  google.protobuf.Struct attributes = 2;

  // Assignment associated with the Ticket.
  Assignment assignment = 3;

// Properties contains custom formatted info about the ticket, passed directly through to the match function
    google.protobuf.Any properties = 4;  
}
```

**Comment by Laremere** [comment]
Some properties which I think are important in this discussion:

# Consistency Across calling patterns.
There are currently four places in OM api that use struct to allow plumbing for arbitrary data:  Ticket, Profile, Match, and Assignment.  It's important that these interfaces and best practices remain consistent.  This makes OM easier to learn and use.  It also allows easy moving of data from one component to another.  Eg, copying player data from a ticket to a match.

# System Composability
One of the key advantages of Open Match is its interface.  This will in the future allow other system to plug and connect to Open Match.  Components will connect to Open Match through many surfaces: Frontend, Backend, MMF, Evaluator, and Stats.  In a mature ecosystem which preserves composability, users would be able to take OM and several other off the self components and connect them.  Eg, a default elevator might use a score field, and a standard directory know how to take a match definition and allocate a server using region and game parameters (mode, players).  The MMF needs to be able to populate the match with this data.

# Deduplication
I think opinions differ, but I would prefer not requiring any duplication of data.  There is a large overlap between the data required for indexing/filtering, and the data required for running the MMF.  Soon it's likely that data will be exposed to a stats service endpoint from the same source as for indexing/filtering.  The choices around whether or not to duplicate data is not trivial, and easy to get wrong.  Too much added = more code copying data, more increased ticket size.  Too little = can't do ad hock investigation into stats of playerbase.

# Rest/JSON compatibility (or deprecation)
Struct has a very nice compatibility with JSON (honestly being better for JSON than proto.)

For any, my understanding is that the current library requires the any type to have been compiled into the binary doing the translation for any to properly convert the object.  So they're not very compatible.  Though using an any of struct may be an option for that use case.  (but that would have poor system composability.)

However it may be that we shouldn't be trying to make the rest/json endpoints work.  If the any approach is enough of a benefit for proto users, we should explore deprecating rest/json.  A holistic approach should be taken, looking at why people are asking for it, and if there are alternatives (such as education into using protobuffers.)

# Wire and in memory space usage, decoding speed
Moving things around and having things in memory is likely to be most of what OM is doing.  (besides MMF logic)  Protos are a good improvement over using JSON.  I'm a little concerned about the number of duplicate strings used by field names for index-able fields.  Proto any would be more efficient.

**Comment by Laremere** [comment]
Two alternatives for discussion:
```protobuf
// Assignment to be associated with this Ticket.
message Ticket {
  // The Ticket ID generated by Open Match.
  string id = 1;

  // Indexable and filterable float values.
  map<string, float64> fargs = 3;
 
  // Filterable string values.
  map<string, string> sargs = 4;
 
  // Filterable on presence or absence of given value.
  repeated string tags = 5;

  // Assignment associated with the Ticket.
  Assignment assignment = 6;

  // Properties contains custom formatted info about the ticket, passed directly through to the match function
  google.protobuf.Any properties = 7;  
}
```

This is an alternative which removes the complexity of having struct.  Since Any would support more complex data structures, the complexity of struct can be removed.  True/False is removed for simple tags which may or may not be present.

Another alternative:
```protobuf
// Assignment to be associated with this Ticket.
message Ticket {
  // The Ticket ID generated by Open Match.
  string id = 1;

  // Properties contains custom info about the ticket.  Top level values can be
  // used in indexing and filtering to find tickets.
  google.protobuf.Any properties = 2

  // Assignment associated with the Ticket.
  Assignment assignment = 3;
;
}
```

It is possible to read some fields from protobufs without knowing the whole datastructure.  Eg, if I had my ticket format of:

```protobuf
message TicketInfo {
  float64 skill = 1;
  string player_id = 2;
  float64 latency_us_east = 3;
  float64 latency_us_west = 4;
// etc...
}
```
By specifying in the index or filter that field tags 1, 3, and 4 are floats that we care about, they can be directly extracted from the any's bytes.  The encoding of protobufs allows ignoring of fields we don't care or know about.  Accessing nested fields could be supported as well.

**Comment by sawagh** [comment]
Detailed proposals and options! :) Thanks @calebatwd, @Laremere for the clarity in the explanations. Here are my thoughts on the alternatives, pros / cons:

I do like the idea of separating out the attributes Open Match cares about - from the properties it does not. I think it makes the API usage a bit more obvious. Also, if we do that for tickets, we should follow a similar pattern for Match, Profile etc., as @Laremere pointed out (Consistency). 

About the duplication related cons, I agree that the API providing the ability increases the possibility for duplication but it is still up to the developer to trade-off duplication disadvantages with the alternatives. (the API providing two fields to separate out the attributes from the properties itself does not necessitate duplication) 

For the attributes for Open Match, lets discuss in TSC meeting, the proposals. 

For the choice of Any for the data blob, I am definitely concerned about losing REST support and am not in favor of deprecating REST just for using Any. 

**Can we go back to using a 'string' for the the properties (that Open Match does not care about?) - Thoughts?**

**Comment by Laremere** [comment]
Here's a more thorough proposal for a solution which does duplication/separation of concerns.

```protobuf

message Ticket {
  // The Ticket ID generated by Open Match.
  string id = 1;

  // Values used for filtering tickets, and stats gathering.  Not
  // passed to the Match Making Function.
  SearchFields search_fields = 2;

  // Details of the ticket which are passed to the Match Making Function.
  google.protobuf.Any details = 3;

  // Assignment associated with the Ticket.
  Assignment assignment = 4;
}

message SearchFields {
  // Indexable and filterable float values.
  map<string, float64> fargs = 1;
 
  // Filterable string values.
  map<string, string> sargs = 2;
 
  // Filterable on presence or absence of given value.
  repeated string tags = 3;
}

message Assignment {
  // Connection information for this Assignment.
  string connection = 1;

  // Other details to be sent to the players.
  google.protobuf.Any details = 2;

  // Error when finding an Assignment for this Ticket.
  google.rpc.Status error = 3;
}

message MatchProfile {
  // Name of this match profile.
  string name = 1;

  // Details associated with this MatchProfile. (Optional)
  // Open Match does not interpret these properties but passes them through to
  // the MatchFunction.
  google.protobuf.Any details = 2;

  // Set of pools to be queried when generating a match for this MatchProfile.
  // The pool names can be used in empty Rosters to specify composition of a
  // match.
  repeated Pool pools = 3;

  // Set of Rosters for this match request. Could be empty Rosters used to
  // indicate the composition of the generated Match or they could be partially
  // pre-populated Ticket list to be used in scenarios such as backfill / join
  // in progress.
  repeated Roster rosters = 4;
}

message Match {
  // A Match ID that should be passed through the stack for tracing.
  string match_id = 1;

  // Name of the match profile that generated this Match.
  string match_profile = 2;

  // Name of the match function that generated this Match.
  string match_function = 3;

  // Tickets belonging to this match.
  repeated Ticket tickets = 4;

  // Set of Rosters that comprise this Match
  repeated Roster rosters = 5;

  // Details for removing collisions between matches.
  google.protobuf.Any evaluation_criteria = 6;

  // Additional details about the match passed to
  // the caller of Open Match.
  google.protobuf.Any details = 7;
}

message StandardEvaluationCriteria {
  float64 score = 1;
  repeated string resource = 2;
}

message Evaluation {
  repeated string ticket_ids = 1;
  google.protobuf.Any evaluation_criteria = 2;
}

```

**Comment by Laremere** [comment]
I have done some testing related to compatibility between http/json and Any:
A conversion between Json and Any requires that the type the compiled in with the converter.  (Though I think theoretically it should be possible to configure the converter with FileDescriptorProto at runtime, I haven't seen any way to do this with the current implementation.)

So if you had arbitrary protobuf types, you would not be able to use the http/json capability of Open Match without compiling it yourself.  However json support is still very close to what it is today by using struct as your any type.  For example,
```json
{
  "ticket": {
    "details": {
      "@type": "google.protobuf.Struct",
      "value": {
        "mmr": 123,
        "name": "foobar"
      }
    }
  }
}
```

Is converted to an any value containing the protobuf struct.  With this solution, all of your components would have to work with the struct value (just like today.)  In comparison to how we're using struct in 0.7, this adds a single extra wrapping layer for those who wish to use http/json and struct, but allows anyone who wants to use their own protos and grpc the ability to efficiently do so.

**Comment by Laremere** [comment]
My recommendation here:
# For all client defined fields, switch to using Any.

Pros:
- It is as compatible with rest/json as it today. 
- grpc users get all of the proto advantages, such as more efficent transmission,
   and removing most boiler plate transformation code.
- Binary data can be efficiently transmitted.
- The "standard" way to extend protos.

Cons:
- For json users, it is an extra required nesting.
- Future systems may only support custom protos, making it harder for rest users
  to integrate with the larger ecosystem.

# Seperate custom data fields on message by transmiter / reciever combination

This means, as demonstrated in [my prevoius comment](https://github.com/googleforgames/open-match/issues/765#issuecomment-527997636),
that some messages will have multiple fields for data, split by the usage.  Everything
but search_fields are customization points, so will use Any.

The purpose of this duplication is that there are several configurable / pluggable
surfaces:  FE Client, mmf, director, statestore indexing, evaluator.

I think it's expected that most instances of OM will not implement all of these
surfaces.  Instead standard solutions should be sufficient for most use cases.
We also don't want to prescribe solutions at the OM level (though the community
may settle on a solution.)  As such, if two different plugable components require
a specific data format for the entirity of the implementation despite not
directly communicating, then they'll be incompatible.

This conflict is most easily demonstrated with the current match's properties.
This field contains both details for the evaluator as well as the director.  We
want to ship a standard evaluator, which uses score to choose which matches to
select.  So the properties must be compatible with this evaluator.  If my
director (which might also be out of the box) wants to use a conflicting field
name, then you'd be out of luck.  That we have talked about adding a standard
score field to match also demonstrates this problem.

ticket
- search_fields - specifies the names values than can be used to filter tickets.
   Will also be used by the stats service. eg: elo, region.
- matchmaking_criteria - used by the matchmaking function to decide on good matches.
   eg: elo, player id, blocked player ids.
- resolution_details - used by the director to help processes the match returned
  by OM, and to give the assignment to the ticket's source. eg: which service instance holds the player's request and should be informed of the match found.

match
- evaluation_criteria - what is passed to the evaluator when resolving ticket
  conflicts.  eg: quality score.
- resolution_details - used by the director to help process the match returned.
  eg: what location get a game server from.

assignment
- ???? - assignment details from the mmf (eg, what map to start loading, team to join)
- ???? - assignment details from the director (eg, what server to connnect to)

I'm considering whether the ticket's resolution_details should be sent to the mmf.
If it is, it saves a ticket lookup for the backend (though this could be done while
waiting for the synchronizer anyways), but it is less consistent with
not passing data where not nessisary.  If the match simply had a list of ticket ids,
mmfs couldn't send the matchmaking_criteria back to the frontend, saving some data
encoding and transfer there.

Also missing in this flow is the mmf passing info back to the ticket directly.
It can do it by passing to the match's resolution details, and that passing
data onto the assignment, but it may be worth standardizing that with a unique
field on match.

Also, as a reasonably significant bonus, reducing the amount of data sent to
the evaluator (which current includes all of the ticket data, even specifics 
maybe only useful to the MMF or filtering) improves system performance.  The
synchronizer and evaluator are the least horizontaly scalable (ie: not) pieces
in the whole system.

**Comment by Laremere** [comment]
Comments from discussion:
- Want index fields in MMF.
- Unsure about only sending evaluation criteria and ticket ids to evaluator.  Current tests don't show this as a bottleneck.  Premature optimization?
- Yes to splitting the anys though.
- Concern with indexing all search fields: Game clients want to send everything.  Now the frontend needs to do this.  Concern is about people who aren't Unity.
- Director is not concerned with ticket, don't put resolution_details on the ticket.
- Only one any on the assignment.

**Comment by Laremere** [comment]
This proposal has been implemented.
