### ISSUE TITLE
API change: Add QueryTicketIds to mmlogic

### ISSUE THREAD

**Issue by Laremere** [googleforgames/open-match#766]
## Overview

This change would add a new service rpc endpoint which takes a pool (like QueryTicketsRequest), but only returns a list of Ticket ids.

## Motivation

There are some system level operations when working with open-match which require only the ticket ids.  These are also operations which are likely to require a large number of tickets be returned.  Examples:

- Delete all tickets in Open Match.
- Get all of the tickets, and reconcile actual OM state with what I expect to be in OM.

These operations are useful when recovering from system failures.

## Impact

New RPC endpoint, does not break any existing users.  

## Change Proto

```protobuf
message QueryTicketIdsRequest {
  // The Pool representing the set of Filters to be queried.
  Pool pool = 1;
}

message QueryTicketIdsResponse {
  // The ids of tickets that meet the Filter criteria requested by the Pool.
  repeated string ids = 1;
}

service MmLogic {
  // ... existing rpc here ...

  // QueryTicketId gets the list of ticket ids that match all Filters in the
  // specified Pool.
  rpc QueryTicketIds(QueryTicketIdsRequest) returns (stream QueryTicketIdsResponse) {
    option (google.api.http) = {
      post: "/v1/mmlogic/ticketids:query"
      body: "*"
    };
  }
}
```

**Comment by calebatwd** [comment]
Could you explain the second example a bit more? What's the "ensure reconcile actual OM state"? Is this just for debugging?
Is delete all tickets a function supported by open match mmlogic, and if so, is the intention also a debugging mechanic? I have several "drop table" named friends who may accidentally do this in a production environment if the api is automated to this degree :)

**Comment by Laremere** [comment]
Fixed the wording in the second example.  For example, the system populating tickets could crash.  In that event, it may want to scan tickets, and for any ids that it sees but doesn't understand (eg, created the ticket but crashed before saving it), it would delete those tickets.  Or it might query those tickets to find out what player they belong to, and correct the data on its side.

Delete all tickets is not currently supported as its own API call.  This would be a primitive which would simplify any caller which wants to perform that task.

**Comment by sawagh** [comment]
Lets visit this when we look at the Stats API?

**Comment by sawagh** [comment]
Discussed in TSC - there were no concerns implementing this. Removing the TSC discuss tag and we can now implement the changes here.

**Comment by Laremere** [comment]
Ok, implementation wise, this should be straight forward:
Add the above protos, and add an implementation to query_service.go.  It should follow fairly close to QueryTickets' implementation, with only what's being returned changing...
