### ISSUE TITLE
API change: Return all tickets when no filters are specified

### ISSUE THREAD

**Issue by Laremere** [googleforgames/open-match#767]
## Overview

When mmlogic is queried, but the pool contains no filters, return all currently indexed tickets in open-match.

## Motivation

Along with #766, this allows systems which need to correct the entirety of open-match's system state to see all tickets.

It reduces the minimal demo complexity, allowing mmf writers which have small enough player populations to simply work with the entire pool by simply not specifying any filters. (Unlike today, where a dummy index is required.)

This also aligns better with other query formats, eg SQL, where no "where" clause returns all values.

## Impact

This is no a breaking change.

## Change Proto

No changes to protos.

**Comment by calebatwd** [comment]
This is pretty neat. Does it return every ticket as the full hash read as well?
This gets around the dummy issue, but with a few built-in indexes, the dummy one goes away as well... namely `created`. I suppose the created field could also just be used by this api though under the hood (get me all things where created is greater than -forever).
Sweet, sounds cool.

**Comment by calebatwd** [comment]
I think for the proposal, it'd be nice to hear how this will be achieved and if there's any performance impact based on how the scan or lack-of would work

**Comment by Laremere** [comment]
Proposed implementation (roughly):

- When indexing a ticket, additionally add it to a redis set of all tickets.
- When de-indexing a ticket, additionally remove it from that set of all tickets.
- When performing a query: If there are filters present, use existing logic (with those characteristics) to get the list of ticket ids.  If there are no filters present, instead get all ticket ids using the all-tickets set.  As is the current implementation, once the tickets ids are identified, query the tickets in batches to return to the caller.
