### ISSUE TITLE
New Feature: Index Configuration API

### ISSUE THREAD

**Issue by calebatwd** [googleforgames/open-match#768]
## Motivation
Index configuration is currently managed through a config yaml on open match. It's designed to watch a locally mounted volume file for changes in order to read for index changes. Indexes currently look like:
- key1
- key2

While **Agones** is able to use kubernetes for config (it's an extension on kubernetes), open match uses kubernetes purely as a service's infrastructure, but not for anything else. If the volume mount config-syncing mechanism were to fail for some reason, debugging kubernetes to re-enable open match seems like a difficult support issue. Ideally, open match would support ad-hoc configuration through its own api/data-storage design.

On the api itself, it would be nice to support:
- wildcards (also gives automatic `*`)
- exclusions
and stretch
- new types as we need them (beyond bool, number, and string)

## Changes
We need
- a way to store the index policy (could be redis or a configurable storage provider)
- an api endpoint for manipulating the index policy, and receiving validation feedback
- index policy reading (and caching w/expiration) on the frontdoor or mmlogic service (whichever is performing the indexing)

Out of scope v1
- immutable index versioning
- version policy lists and therefor policy combining
- rehydration of current tickets on policy changes
- clean up of stale indexes (arguably in scope, but it depends on the requirement to do index-cleans realtime or not)
- list indexing ... lists aren't order-guaranteed

## Contract
I imagine eventually doing something like for field policies:
```
// An indexing policy for the open match data layer
message PutIndexPolicyRequest {
...
    // Fields and types to include in indexing. Overpowers excludes
    repeated FieldPolicy include = 1;
...

// A description of a path and the desired index type and precision
message FieldPolicy{

    // A string representing the dotnotation path to the field
    string path = 1;

    // An instruction for how to index the field for supported types
    repeated TypePolicy types = 2 [default = AUTOMATIC]

    // Supported indexable types
    enum TypePolicy {
        AUTOMATIC = 0; // An inferable type (number, string bool)
        NUMBER = 1;
        STRING = 2;
        BOOL = 3;
        DATETIME = 4;
        VECTOR = 5;
    }

    // other index-binding things like precision and range...
}
```

**HOWEVER**, I don't think we have a use case today for additional type policies.
In the meantime, we can rely on `structs` current types to get us by. This would make the full contract...

```
// An indexing policy for the open match data layer
message IndexPolicyPutRequest {

    // Fields and types to include in indexing. Overpowers excludes. e.g. "*", "player.*", "player.skill", "skill"
    repeated string include = 1;

    // Fields not to index. Also supports wildcard. e.g. "*", "player.*", "player.skill", "skill"
    optional repeated string exclude = 2;
}

message CreateTicketResponse{
    Status status = 1;
}

message GetIndexPolicyRequest {}

message GetIndexPolicyResponse{
    Status status = 1;

    // Fields and types to include in indexing. Overpowers excludes
    repeated string include = 1;

    // Fields not to index
    optional repeated string exclude = 2;
}
```

## Example
include: ["*", "player.skill"]
exclude: ["player.*"]
In the above example, we index everything in the ticket by default, however, we only index _skill_ from within the player object, assuming there are more fields in the player object that we don't want to index at this time.

## Concerns
Wildcards may be too expensive to infer on every ticket (though, tickets should look somewhat predictable for a deployed game, so I would expect the developer to start using index targeting for production).

**Comment by Laremere** [comment]
I think there are some prerequisites

**Comment by sawagh** [comment]
Open Match configuration spans more than just the index configuration. **Is the motivation to dynamically be able to configure indexes - or to replace config maps (to avoid debugging Kubernetes as the current motivation description states?).** 

Exposing all of the configuration to be via API will expose many more methods than listed in the contract - and may not be useful. Furthermore, given that the services are hosted in Kubernetes, you may not be able to completely avoid debugging kubernetes when investigating operational issues. 

That said, if the motivation is to have ability to configure indexes dynamically via API instead of necessarily directly calling into Kubernetes APIs to update config maps, that sounds reasonable.

In that case, we could still expose the APIs to update the indexes, but could still use configmaps to store the configs. Then we wont necessarily have to look for a different data-storage but could use viper to update the index configuration when updated via api
(https://github.com/spf13/viper#writing-config-files)

Thoughts?

**Comment by calebatwd** [comment]
How will we validate a person setting up new index configurations through config maps? What happens when the configuration is wrong? Does the service detect the config map change and just reject it or does it just hard-fail and stop running?

**Comment by sawagh** [comment]
@Laremere - please close this with some details on index configuration plan for v0.8 based on 
https://github.com/googleforgames/open-match/issues/765

**Comment by Laremere** [comment]
As of completing the work in https://github.com/googleforgames/open-match/issues/765, all of the fields in search_fields are now indexed.  As such, no configuration of the indexing is required.
