### ISSUE TITLE
Consider making synchronizer a stateful set

### ISSUE THREAD

**Issue by Laremere** [googleforgames/open-match#771]
Currently the synchronizer is a deployment.  However we really only want run running at a time.  Making it a stateful set might make it clearer, and it may be possible to connect to it directly, instead of using a service.  Other there other implications for making it a stateful set?

**Comment by yfei1** [comment]
A StatefulSet resource requires having a persistentVolume defined in the host machine. However, the synchronizer depends on Redis as its storage service, so I think perhaps StatefulSet may not be the ideal resource type for the synchronizer

**Comment by Laremere** [comment]
Leader election looks like a better solution.
