### ISSUE TITLE
Proposal: Distribute 3 scale levels of Open Match helm charts

### ISSUE THREAD

**Issue by Laremere** [googleforgames/open-match#777]
There's been some discussion about what the default resource values should be for Open Match.  It's hard to come up with a good answer because we lack data, and there are different use cases.  I propose we define 3 levels, which suit the different use cases:

# 1 Minimatch for Demo
We want it to be cheap and easy to evaluate OM.  The demo uses barely any resources.  Instead of running all of the OM components, we can use the Minimatch bundle to ship OM as a single deployment (probably actually stateful set.)  As long as the demo is reasonably performant, reduce resource usage as much as possible.

# 2 Development and Medium Game Deployment
For standard OM development, I often just up the chart.  It's good to have a full system set up, so we encounter issues caused by distributed deployment, but we also don't need OM at maximum power.

This should fit in the "standard" GKE cluster with at least a little headroom.  For reference on the possible standards:
- Default when using the pantheon ui: 3 nodes, 1 cpu each, 3.75 GB memory each.
- Default from OM's Makefile: n1-standard-4 (4 cpus, 15 gigs each), 2 nodes (w/ auto scaling from 1 to 10 nodes).
- Default from OM's documentation website:  n1-standard-2 (2 cpus, 7.5 gigs each), 3 nodes

It's also good to have a reasonably sized deployment for a real production traffic that most games can use.  For some numbers, the #10th most popular game on stream right now is football manager 2019.  https://store.steampowered.com/stats/

It's max concurrent players today was 62,562.  I don't even know how this game works, but if we assume 10 minute matches, that gives us:  
- 62,562 / 10 minutes =~100 new players searching per second
- 100p/s * 30 seconds (reasonable average wait time) = 3000 tickets in the pool.

We should be able to handle that scale within such a deployment.  

# 3 Scale testing and Large Game Deployment
Occasionally we'll want to brag about how awesome OM is at scaling.  We shouldn't use the everyday deployment to get those numbers.  If we need to add a bunch more resources to scale to, eg, A Fortnite, then use a third set of resource numbers for this.

# Other notes
It should be possible to swap out the scale of OM without affecting logical configuration (eg, indexes.)  This would be a good litmus test that things are separated properly.

**Comment by yfei1** [comment]
I agree with you. When I am benchmarking Open Match, it *seems like* some of the pods got OOM killed because their required too much memorys.

**Comment by thisisnotapril** [comment]
Closed for inactivity
