### ISSUE TITLE
Investigate use in Godot Game Engine

### ISSUE THREAD

**Issue by fire** [googleforgames/open-match#8]
This is an issue tracking my investigation for use with the Godot Game Engine.

**Comment by fire** [comment]
Investigating kubernetes setup.

**Comment by sawagh** [comment]
Given that this issue references investigating use of Open Match in GoDot engine, I dont anticipate any work in Open Match itself as of now. Am closing the current issue. Please reopen with a specific feature ask from Open Match if any upon this investigation.
