### ISSUE TITLE
Unify helm chart image tags

### ISSUE THREAD

**Issue by yfei1** [googleforgames/open-match#812]

**Comment by Laremere** [comment]
I actually have an opposing feature request: It would be nice if we used specific shas for the images.  This would be different for each image.  When developing, it would be nice to rebuild an image, and do a kubectl apply which just changes that image tag to the new sha, forcing an update.

**Comment by yfei1** [comment]
> I actually have an opposing feature request: It would be nice if we used specific shas for the images. This would be different for each image. When developing, it would be nice to rebuild an image, and do a kubectl apply which just changes that image tag to the new sha, forcing an update.

Ah I've thought about this, but this will make the release process hard to deal with since we have 15 services defined in the helm chart

**Comment by yfei1** [comment]
After some thinking, for v0.8 I'll unify these image tags. Although having specific shas for different images works, but the root cause of this feature request is from our image build process, while helm is a tool focusing on template yamls and deploy applications. skaffold or ko can help us completely mitigate this issue.
