### ISSUE TITLE
statestore.CreateTicket does not expire ticket indices when redis.expiration is set

### ISSUE THREAD

**Issue by yfei1** [googleforgames/open-match#815]

**Comment by sawagh** [comment]
Does redis.expiration get handled at all today? 

What scenario do we think we would need to expire indices at all? rather than have them cleaned up during assign / delete?

**Comment by sawagh** [comment]
The resolution was to remove this all-together. Did we decide to reassign this to @yfei1 to handle?

**Comment by Laremere** [comment]
Yup, that's correct.  It's not clear what value this option adds, so we're going to remove it.
