### ISSUE TITLE
Implement a Community/Governance policy

### ISSUE THREAD

**Issue by jeremyje** [googleforgames/open-match#83]
We'll need a formalized process that details how contributors can officially be onboarded as Open Match approvers or have read-write access to commit PRs.

Agones has a good starting point policy: https://github.com/GoogleCloudPlatform/agones/blob/master/docs/governance/community_membership.md.

**Comment by sawagh** [comment]
@thisisnotapril - Is there anything to be tracked here?

**Comment by Laremere** [comment]
Per @thisisnotapril this is for the open-match-community, not this repo.

We can also handle this when people are more seriously showing they'll be contributing to OM.
