### ISSUE TITLE
Documentation: Quickstart - write you own match function

### ISSUE THREAD

**Issue by markmandel** [googleforgames/open-match#840]
I should be able to write a match function, host it on Open Match and test it within an hour, with no previous knowledge of open match.

I cannot do this with the current documentation. We need a clear guide on how to do this.

**Comment by sawagh** [comment]
Added tutorial to OM Repo - and documentation here: https://github.com/googleforgames/open-match-docs/commit/2f322c06cdbbad55d39fc1ec9fb1fbf9bd3ddb45
