### ISSUE TITLE
Documentation - Quickstart - write your own evaluator

### ISSUE THREAD

**Issue by markmandel** [googleforgames/open-match#841]
This feels like an advanced topic (I think?), but a step by step how to write your own evaluator (and why you would want to do so - that's not clear either), host it and test it, from first principles.

**Comment by sawagh** [comment]
Added tutorial to OM Repo - and documentation here: https://github.com/googleforgames/open-match-docs/commit/2f322c06cdbbad55d39fc1ec9fb1fbf9bd3ddb45

**Comment by sawagh** [comment]
Ah that comment adds a default one - I think writing your own is advanced topic - tackle in future release.

**Comment by yfei1** [comment]
Closed by https://github.com/googleforgames/open-match-docs/commit/c922e200c2851c1a84b1f6aadcf0cf560ee8df3d
