### ISSUE TITLE
Preliminary analysis of OM failure consequences.

### ISSUE THREAD

**Issue by Laremere** [googleforgames/open-match#848]
This issue is going to serve as a hub for any issues or PRs that result from this analysis.

This is a sequence diagram covering the common operations in a running Open Match.  Boxes are labeled over components as the consequence of that component failing (crashing, kub rescheduling, server on fire, etc) during that time period.

Green is "this is fine"
Yellow is undesirable, but eventually recovers by itself.
Red is bad things: Clients never finding matches, client visible errors, or memory leaks.

![OM Failure States (2)](https://user-images.githubusercontent.com/202599/66243328-13616900-e6b9-11e9-875c-189f37dc19ab.png)

**Comment by sawagh** [comment]
The issues highlighted here lead to recommendations / best practices for Client FE right? Do you anticipate solutions here to be in say Game Frontend - or to Open Match core? 

I propose moving this to v0.10 unless there are some specific fixes that we want to target for v0.9

**Comment by sawagh** [comment]
There seem to be recommendations for Ecosystem interactions with Open Match. If there are specific Open Match core issues here, please file back as issues and we can revisit the milestone.
