### ISSUE TITLE
Inability to select indexes may lead to poor performance

### ISSUE THREAD

**Issue by Laremere** [googleforgames/open-match#869]
The problem is:
1. All fields passed to search fields are indexed.
2. Indexing takings time.
3. Some clients want to talk to OM directly.
4. Updating game clients can be very expensive (roll out logistics, and console certification costs)
5. It's likely changes are going to be wanted to be made to matchmaking independent of game client release cycles.

Combined, these facts are a problem.

@sawagh Is proposing that there is an optional config value which limits which fields are actually indexed. This removes point 1, and solves the overall problem.

I'm leaning to instead address point 3 by providing a common component which is between the game client and OM that handles creating the ticket itself.

Either way (or a way not listen here), the problem should be addressed.

**Comment by sawagh** [comment]
propose moving to v0.10 - not an adoption blocker (unless a current Open Match user strongly only wants to index subset of specified search fields)

**Comment by Laremere** [comment]
With query cache, this is now obsolete, as tickets are only added to the all-tickets index.
