### ISSUE TITLE
Proposal: Switch from gRPC client side load balancing to Linkerd

### ISSUE THREAD

**Issue by yfei1** [googleforgames/open-match#878]
#864 Used a gRPC client-side load balancer along with a DNS resolver to split the traffic into k8s headless services. While this workaround works for in-cluster setup, gRPC is unable to send traffic to new pods spawned by the HorizontalAutoScaler since it is built on HTTP/2's long-lived connections - a connection won't change once it is established. The change submitted in #864 manually config the connection expiration time to 1min to improve this issue a bit yet is still not an ideal solution, we should consider switching to Linkerd to resolve this issue.

**Comment by sawagh** [comment]
Is switching to Linkerd for gRPC load balancing still the POA? If yes, we should still try to target this one for v0.9

**Comment by yfei1** [comment]
Yup, will investigate this issue once we are done with the scale numbers.

**Comment by yfei1** [comment]
Closing this as we are proposing Envoy as an alternative. I just got the prototype working, will publish a proposal to discuss the pros and cons of using Envoy.
