### ISSUE TITLE
Proposal: Explore out-of-cluster load balancing solutions using k8s Ingress

### ISSUE THREAD

**Issue by yfei1** [googleforgames/open-match#879]
Our current client-side round-robin load balancing story doesn't work if one tries to talk to Open Match via an out-of-cluster client. We should investigate a possible solution under such a scenario using k8s Ingress - or at least have some references to resources that may help with this problem.

**Comment by sawagh** [comment]
Is this a documentation problem? As in, should we have guidance and documentation on how to set up out-of-cluster load balancing using k8s ingress? or do you anticipate us making any changes in core to support this out of box for our default installation?

**Comment by yfei1** [comment]
Closing this as we are proposing Envoy as an alternative. I just got the prototype working, will publish a proposal to discuss the pros and cons of using Envoy.
