### ISSUE TITLE
Add end-to-end and scale testing support.

### ISSUE THREAD

**Issue by jeremyje** [googleforgames/open-match#88]
Proposal:
https://docs.google.com/document/d/13ligVygwQ__1liFZdHpMLwGCXb35T-5QzQ6daf6r_JM/edit

**Comment by jeremyje** [comment]
The document discusses the approach to get scale testing and the refactoring changes necessary to make it happen.

**Comment by yfei1** [comment]
Closing this issue since most of the goals listed in the doc are resolved.
