### ISSUE TITLE
Prometheus doesn't work in Open Match two-step installation

### ISSUE THREAD

**Issue by yfei1** [googleforgames/open-match#882]
`kubectl apply -f 01-open-match-core.yaml && kubectl apply -f open-match-telemetry.yaml` does not activate Prometheus scraping process.

**Comment by sawagh** [comment]
@yfei1 - Do we need do fix this? in v1.0? I am moving it further out - close if not relevant any more.

**Comment by thisisnotapril** [comment]
No longer relevant
