### ISSUE TITLE
Prometheus scraping process doesn't work well when scale down deployments

### ISSUE THREAD

**Issue by yfei1** [googleforgames/open-match#883]
Prometheus will lose some data points due to pod shutdowns if we manually scale down an Open Match deployment.

**Comment by sawagh** [comment]
@yfei1 - please check if this is still valid and needs fixing in v1.0 timeframe.

**Comment by Laremere** [comment]
@yfei1 Are there any more details here?  What is causing the problem?

**Comment by yfei1** [comment]
> @yfei1 Are there any more details here? What is causing the problem?

It's not clear what is the root cause of this issue. Our current Prometheus setup already have persistent volume claim turned on so unfortunatelyI don't have more clues for this bug.

How to reproduce this bug:

1. Deploy the setups for scale testing, let it run for 10 mins - Prometheus should show you a large number
2. Scale down the backend & frontend deployment - Prometheus is losing some data points, there numbers are now much smaller than before.

I haven't digged into this issue for a while, but given we don't have anything changed related to Prometheus in v0.10. I think this issue still persists.

**Comment by thisisnotapril** [comment]
Closing for staleness
