### ISSUE TITLE
Documentation: Backend talks to `om-evaluator` by default but this behavior is not well documented

### ISSUE THREAD

**Issue by yfei1** [googleforgames/open-match#892]
Our backend by default talks to an evaluator - `om-evaluator`, but this behavior is not documented and will lead to extremely bad user experience if user choose to customize their own evaluator. We need more documentations to direct users how to write and customize their own evaluator and mmfs.

**Comment by yfei1** [comment]
@Laremere @sawagh Could you resolve this issue when writing the Getting Started guide/Tutorials for Open Match?

**Comment by sawagh** [comment]
Override configs should handle this - now Open Match only talks to the evaluator that is set up explicitly as a part of override config. There is no more - use default evaluator endpoint hoping that that the evaluator is installed there :)
