### ISSUE TITLE
Disable all subcharts by default, default installation should only deploy core openmatch.

### ISSUE THREAD

**Issue by sawagh** [googleforgames/open-match#911]
Currently demo, customize are enabled by default. This makes it harder to understand (less readable) when looking at the makefile. I propose only enabling core by default and disabling all else - and per scenario, enabling these charts.

**Comment by Laremere** [comment]
I would suggest actually everything is turned off by default.  That way it's explicit that if you want it, you ask for it.

**Comment by sawagh** [comment]
+1 open-match-telemetry is probably the other one on by default. I ll rename this issue to reflect the suggestion.

**Comment by Laremere** [comment]
For clarity, I was saying that even the core open match config should be disabled.  As in if you do a helm command with no options, then you get nothing.  This is relevant in, eg, when building a yaml to install the demo on top of an existing OM deployment.

**Comment by sawagh** [comment]
Hmm. My original intent (badly worded in first attempt) was to disable other subcharts when deploying core (today install-chart in makefile has side-effects). I do get your point around - there ll be more scenarios than just deploying core. Is there an issue where I can see the details of how the new proposal will work from a developer / user experience perspective?
