### ISSUE TITLE
Proposal: Containerize some subcommands to simplify the Makefile

### ISSUE THREAD

**Issue by yfei1** [googleforgames/open-match#924]
The current Makefile is pretty verbose - over 100 lines without useful comments, which sets a high standard for people who wanna contributes to Open Match. It would be great if we could containerize some of the Makefile steps - proto-gen, install-toolchain into Dockerfiles, provide shell scripts to run these Dockerfiles and call the shell scripts directly inside the Makefile.

**Comment by thisisnotapril** [comment]
Dup of #905
