### ISSUE TITLE
API change: Have evaluator return only match ids

### ISSUE THREAD

**Issue by Laremere** [googleforgames/open-match#939]
## Overview

Instead of the evaluator returning a stream of matches, only return the ids of the matches it wants to form.

## Motivation and  Impact

Currently, the evaluator returns the entire protobuf of the matches it wishes to form.  This means that the entire protobuf is re-serialized and sent back to the caller which sent the protobuf in the first place.  (The same thing happens in the backend to synchronizer call, but that's internal, so can be changed without an externally visible breaking change.)  It would be much more efficient to only return the id.

One downside is that the evaluator can't change the contents of any matches (eg, dropping a player seen in another match, but still making the match as a whole.)  It's not clear that it's supported anyway (I don't know what the code does today.)  Generally, I think it's better if things are treated as immutable.

## Change Proto

From:
```protobuf
message EvaluateResponse {
  // A Match shortlisted by the evaluator representing one of the final results.
  Match match = 1;
}
```

To:
```protobuf
message EvaluateResponse {
  // A Match shortlisted by the evaluator representing one of the final results.
  string match_id = 1;
}
```

**Comment by calebatwd** [comment]
Sticking to just returning matchids should be fine! If we need to make a future extension point, we can justify it then :)

**Comment by Laremere** [comment]
# Execution plan

As seperate PRs for each of the steps, do the following:

1. First handle the changes for calling the mmf from the backend for https://github.com/googleforgames/open-match/issues/940  This will touch the same code, so it makes sense to rework first.

2. Add a sync.map to the backend fetch matches call.  When a match is returned from the MMF, add it to the map before sending it to the synchronizer.  When a match is returned from the synchronizer, take its id and use the value from the map.  This means we'll ignore changes on the match made by the evaluator during this intermediate step, but the evaluator will still return the full match.

3. Change the interal API for the synchronizer to only return the id from the match, instead of the full match.  Basically the match should be returned from the evaluator and immediately turned into only the id.

4. Change the external evaluator API to only return the id.

The goal of breaking up the changes here is to keep them small.  4 will involve changes to the callers of the API, so keeping the change to the internal syncrhonizer small as possible makes the change easier to review.
