### ISSUE TITLE
Start streaming where possible in more places.

### ISSUE THREAD

**Issue by Laremere** [googleforgames/open-match#940]
Currently, the synchronizer waits for all proposals to be known before starting to send them to the evaluator.  Since serializing and streaming objects obviously takes time, this could be easily done while waiting for everything to be finished.  It would only end the stream once the last MMF had completed.
I haven't checked all of these, but the chains:
mmf to backend to synchronizer to evaluator
evaluator to synchronizer to backend to director
Should all stream as results are available on each instance.

**Comment by sawagh** [comment]
@Laremere changed APIs in most of the components to utilize streaming. Can this be closed?

**Comment by Laremere** [comment]
No, the changes aren't fully complete.  The MMF and evaluator calls still buffer.

**Comment by yfei1** [comment]
Closed by #1082
