### ISSUE TITLE
Create a install template that uses the default Evaluator

### ISSUE THREAD

**Issue by sawagh** [googleforgames/open-match#950]
Currently, each of our getting started / tutorials use their own 'default' evaluator. The basic installation steps leave you with ContainerCreating and then explain how you can override with custom configuration. 

Though having ability to customize is great - can we have a chart for core + default evalutor? 

Or atleast abstract that in installation of a 'default custom config' yaml? That way, our default installation will apply both? Currently, the basic installation exposes the users to understand the evaluator customization - too much to begin with?

**Comment by Laremere** [comment]
I think it makes most sense for the default evaluator to be its own yaml.  However it certainly should have a yaml that is specifies it.  Currently there's the customize yaml, but that also includes an MMF, which is more commonly configured differently.

We already have a yaml for default config: 06-open-match-override-configmap.yaml

Suggestion: The "default" install of open match should be:
01-open-match-core.yaml
07-open-match-default-evaluator.yaml  <- doesn't exist yet
06-open-match-override-configmap.yaml

As users go from basic to advanced, they start with an apply command with all three yamls, then start looking at the config.  Maybe after also swapping out the default evaluator.

**Comment by sawagh** [comment]
+1 - well phrased - That is what I mean by 'core + default evalutor' option. Yes - I think we should have 07-open-match-default-evaluator.yaml for v0.8 and update the basic install option (atleast for the tutorials) to install 01 + 07 + 06.

**Comment by yfei1** [comment]
Closed by #958 and #959
