### ISSUE TITLE
Re-enable workload identity feature

### ISSUE THREAD

**Issue by yfei1** [googleforgames/open-match#951]
Workload identity is blocked by issuetracker.google.com/issues/143944398. Re-enable it when the fix is checked-in.

**Comment by Laremere** [comment]
Can you please go into more detail about what is workload identity, and why it was disabled?

**Comment by yfei1** [comment]
Workload Identity is a feature that allows users to authorize their gcloud accounts using their GKE rbac setups instead of mounting their gcloud credentials as an environment variable. This feature was enabled and added backed in Open Match v0.6.0/0.7.0 for convenience purposes, but it introduces several bugs when installing along with the pod security policy feature such that Redis was unable to install/talk to its slaves. #947 disabled this feature.

I don't think this impact the usability of Open Match unless any of our customers explicitly ask for the WI feature.
