### ISSUE TITLE
Create Open Match best practices guide for production environment

### ISSUE THREAD

**Issue by yfei1** [googleforgames/open-match#952]
This should include the steps to enable Redis initContainers settings for linux users, and etc.

**Comment by sawagh** [comment]
Although the milestone to completely finish this is 1.0, we should make progress on this in v0.9 - Does this issue belong here or in the docs repo? (or may be both - there is a documenting aspect for the best practices - but also a we may have some examples / changes etc. in Core Open Match itself)

**Comment by yfei1** [comment]
Closed as it is resolved by open-match-docs#153
