### ISSUE TITLE
Update Getting Started (First Match) Demo for v0.8

### ISSUE THREAD

**Issue by sawagh** [googleforgames/open-match#953]
The current instructions use 02-open-match-demo.yaml  - which for v0.8RC has the following problems:

1. The namespace for the components is set to open-match. The goal is to have demo components deployed in om-demo namespace (does specifying on command line override the yaml configuration? even then, yaml should have om-demo)

2. The demo yaml assumes evaluator is installed. The core yaml does not install it any more. The demo thus needs to now also install the evaluator and configure the core. I propose this be done as a part of the common installation steps. We need to answer the following:
- Should this evaluator be in OM namespace (will have to be if it is a part of common steps)
- Should this evaluator be standalone and not use harness? (the reason this needs to be answered is because the tutorial today uses a standalone one - and we may want to standardize the usage of evaluator across Getting Started and Tutorials)

**Comment by yfei1** [comment]
Closed by #958 and #959
