### ISSUE TITLE
API change: Assignment.error should be Assignment.status, and always returned

### ISSUE THREAD

**Issue by Laremere** [googleforgames/open-match#960]
The proto type itself is Status, which has an "ok" code.  Instead of indicating that this is always an error, it should instead be used properly as a status.  If the backend client doesn't set it, OM should set it as Ok.

**Comment by sawagh** [comment]
Sounds reasonable to me. Let us pass breaking API changes through either a community / TSC meeting explicitly for communicating before we implement it - just for awareness.

**Comment by Laremere** [comment]
TSC discussion points:
Renaming makes sense.
However, it being the type of rpc.Status isn't intuitive.  Maybe rework.

**Comment by sawagh** [comment]
Lets consider removing status - and use extensions for this?
