### ISSUE TITLE
Sample Game

### ISSUE THREAD

**Issue by cppleon** [googleforgames/open-match#986]
At the moment, it is very difficult to figure out how to use **open-match**, with the latest updates #840 #842 it has become clearer, but It would be great if we had a sample game, there is [paddle-soccer)](https://github.com/markmandel/paddle-soccer) from @markmandel, but it is a very primitive example

**Comment by Laremere** [comment]
If you happen to be going to Kubecon, there's a workshop happening this Monday: https://events19.linuxfoundation.org/events/kubecon-cloudnativecon-north-america-2019/schedule/#

If not, the sample game for the workshop is already available: https://github.com/Laremere/space-agon

Rough edges warning: Though the commands to run in the README are not the workshop that is going to be given.  Just my commands for iteration.  The workshop is a step by step guide explaining what the different pieces are.  I imagine going to end up public in one form or another at some point.  If you don't want to wait, you could dig through the repo's source.

**Comment by Laremere** [comment]
Given that we have the sample game, I'm going to close this.  The sample could be improved, but I don't see anything that's directly actionable in your issue.  If you have further comments, please re-open this issue or create new issues with specific requests.  Thanks for your input!
