### ISSUE TITLE
Open Match should generate unique match identifiers 

### ISSUE THREAD

**Issue by sawagh** [googleforgames/open-match#990]
Currently, Open Match lets the MMF generate a Match id. However, during evaluation and synchronization, the logic in Open Match expects  the Match id to be unique. (It aggregates all matches from 'n' calls, sends them to the evaluator while maintaining mapping of a call's context id to match ids - and when results are returned, knows which calls had what matches approved)

If an mmf does not set a unique Match Id, currently, the synchronizer would be incapable of correctly mapping approved matches back to their fetchmatch calls.

One option to do this is to generate a unique id for the match that Open Match sets - while still letting the mmf specify some identifier (may be match name?)

We can discuss alternatives - but the current mechanism is definitely fragile.

**Comment by Laremere** [comment]
+1 to this being an issue.

I see two alternatives:
1. Don't allow the ID to be set by the MMF, and erroring if it was. (I think we need to do this for ticket creation too?)  If we need to have information about which mmf run it was from, we can add a profile name field, which OM could copy from the MatchProfile message's name field to the Match message. 

2. Require unique IDs to be set by the MMF.  This puts more burden on the MMF writer.  However, it makes it easier to track from logs of the MMF, through the evaluator, and to the Director.

I strongly prefer not having OM set the field only if the MMF didn't.  Either we should always set it, or the mmf author should.

**Comment by sawagh** [comment]
https://github.com/googleforgames/open-match/issues/1079 should address some concern here. This change in behavior is complex and not a required change.
