### ISSUE TITLE
Get Match information in GameFrontend

### ISSUE THREAD

**Issue by Cyansilver** [googleforgames/open-match#995]
hi all,

I wonder how we can get the matches created by Director in GameFrontend?
Besides, not sure how we can use open match for the case that client would like to create a new match or join an existing match? Or it's out of open match scope?

Thank you

**Comment by Laremere** [comment]
Match isn't an object stored in OM, so there isn't a get match API request.  Otherwise, this sounds like a backfill scenario, which will be covered by documenting how to do backfill: https://github.com/googleforgames/open-match/issues/1148
