### ISSUE TITLE
API change: Move AssignTickets to the FE, rename services

### ISSUE THREAD

**Issue by Laremere** [googleforgames/open-match#996]
## Overview

Move Backend.AssignTickets to the grpc service Frontend (TicketApi).

Rename the following:
Backend -> MatchApi
Frontend -> TicketApi
MmLogic -> QueryApi

## Motivation

We've known for awhile that these names were bad, but weren't sure what better ones were.  Lets fix that before going much further.

The move of AssignTickets is also to rationalize what the endpoints are doing a little bit.  The original inception was that different pieces of the game architecture would talk to specific pieces of OM.  So the frontend wasn't the "frontend", but instead is the API surface that the frontend talk to.  This has proved to not be intuitive, as well as confusing when we've tried to start talking about the /actual/ frontend component.

This split aligns much more closely with what the endpoints are actually doing:
MatchApi = calling the MMF and synchronizer, doing batch processing.  Large long lived requests.
TicketApi = Modifications and gets (by id) to tickets.  Small short term requests modifying redis.
QueryApi = Getting bulk data of or about tickets.  Likely to have caching and other optimizations in the future.  Very large streaming requests.

## Impact

The director type components will need an additional connection to the TicketApi, where they previously would only have a connection to the Backend (MatchApi).  Some renaming in client libraries required as well.

## Change Proto

Following the guidelines at: https://cloud.google.com/apis/design/naming_convention#interface_names

The names are appended with Api, as Match, Ticket, and Query are all names used elsewhere in the proto definitions.

```proto
// The QueryApi service implements helper APIs for Match Function to query Tickets from state storage.
service QueryApi {
```

```proto
// The MatchApi service implements APIs to generate matches and handle ticket assignments.
service MatchApi {
```

```proto
// The TicketApi service implements APIs to manage and query status of a Tickets.
service TicketApi {
```

**Comment by sawagh** [comment]
I like the overall change proposal. I propose 'Service' over 'Api' in the name since these are fully functional services and exposed APIs are just a part of that.

MatchService
TicketService
QueryService

**Comment by rib** [comment]
Just out of curiosity will GetAssignments streams/queries continue to be served by the 'TicketApi' as something that sounds a bit like "Getting bulk data of or about tickets" and so maybe a frontend might also want a connection to the QueryApi/service?

**Comment by sawagh** [comment]
Summarizing the discussion in the last Open Match TSC meeting: The current services split the APIs based on which component needs to access them (Game Frontend may need to call Open Match Frontend, Director may need to call Open Match Backend). This enables setting up role based access control to these services simple in a production setup. Splitting the services based on the data they serve (Match, Ticket .. ) may need both the Game Frontend and Game Backend to access the Ticket API which would make setting up access control tricky. 

The conclusion was to keep the Frontend, Backend services intact but to rename the MMLogic API to QueryService (Given MMLogic is just outright confusing and unintuitive)
